<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GraphingImpl</RootNamespace>
    <AssemblyName>GraphingImpl.Managed</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphingInterfaces\GraphingInterfaces.csproj" />
    <ProjectReference Include="..\GraphingRaster.Skia\GraphingRaster.Skia.csproj" />
    <ProjectReference Include="..\JsMath.Port\JsMath.Port.csproj" />
  </ItemGroup>
</Project>
