namespace GraphingImpl;

public enum SyntaxErrorCode
{
    None = 0,
    ParenthesisMismatch = 1,
    UnmatchedParenthesis = 2,
    TooManyDecimalPoints = 3,
    DecimalPointWithoutDigits = 4,
    UnexpectedEndOfExpression = 5,
    UnexpectedToken = 6,
    InvalidToken = 7,
    TooManyEquals = 8,
    EqualWithoutGraphVariable = 10,
    InvalidEquationSyntax = 11,
    EmptyExpression = 12,
    EqualWithoutEquation = 14,
    InvalidEquationFormat = 15,
    ExpectParenthesisAfterFunctionName = 25,
    IncorrectNumParameter = 26,
    InvalidVariableNameFormat = 32,
    BracketMismatch = 34,
    UnmatchedBracket = 35,
    InvalidMathMLFormat = 40,
    UnknownMathMLEntity = 41,
    UnknownMathMLElement = 42,
    CannotUseIInReal = 48,
    GeneralError = 52,
    InvalidNumberDigit = 55,
    InvalidNumberBase = 56,
    InvalidVariableSpecification = 57,
    ExpectingLogicalOperands = 58,
    ExpectingScalarOperands = 59,
    CannotMixLogicalScalarInList = 60,
    CannotUseIndexVarInOpLimits = 61,
    CannotUseIndexVarInLimPoint = 62,
    CannotUseComplexInfinityInReal = 72,
    CannotUseIInInequalitySolving = 123,
    RichEditSerializationError = 201,
    RichEditInitialization = 202,
    RichEditInlineObjectStructure = 203,
    RichEditMissingArgument = 204,
    RichEditGeneralError = 210
}
