<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GraphControl</RootNamespace>
    <AssemblyName>GraphControl.Managed</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GraphingTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphingInterfaces\GraphingInterfaces.csproj" />
    <ProjectReference Include="..\GraphingImpl\GraphingImpl.csproj" />
    <PackageReference Include="Avalonia" Version="9999.0.0-localbuild" />
  </ItemGroup>
</Project>
