// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

//----------------------------------------------------------------------------
//  Package Title  ratpak
//  File           support.c
//  Copyright      (C) 1995-96 Microsoft
//  Date           10-21-96
//
//
//  Description
//
//     Contains support functions for rationals and numbers.
//
//  Special Information
//
//
//
//----------------------------------------------------------------------------

// #include <string>
// #include <cmath>
// #include <cstring>  // for memmove
// #include <iostream> // for wostream
// #include "ratpak.h"
//


using System.Runtime.InteropServices;
using uint8_t = System.Byte;
using uint32_t = System.UInt32;
using uint64_t = System.UInt64;
using int32_t = System.Int32;
using wchar_t = System.Char;
using wstring_view = string;
using wstring = string;
using MANTTYPE = System.UInt32;
using TWO_MANTTYPE = System.UInt64;
using PNUMBER = CalcEngine.RatPak.NUMBER;
using PPNUMBER = CalcEngine.RatPak.NUMBER;
using PRAT = CalcEngine.RatPak.RAT;

namespace CalcEngine;

public partial class RatPak
{
//
// void _readconstants();
//
// #if defined(GEN_CONST)
// static int cbitsofprecision = 0;
// #define READRAWRAT(v)
// #define READRAWNUM(v)
// #define DUMPRAWRAT(v) _dumprawrat(#v, v, wcout)
// #define DUMPRAWNUM(v)
//     fprintf(stderr, "// Autogenerated by _dumprawrat in support.cpp\n");
//     fprintf(stderr, "inline const NUMBER init_" #v "= {\n");
//     _dumprawnum(v, wcout);
//     fprintf(stderr, "};\n")
//
// #else
//
    void DUMPRAWRAT(RAT v)
    {
    }

    void DUMPRAWNUM(NUMBER v)
    {
    }

    void DUMPRAWNUM(int32_t v)
    {
    }

    void READRAWRAT(ref RAT v, NUMBER initp, NUMBER initq)
    {
        createrat(ref v);
        dupnum(ref (v).pp, initp);
        dupnum(ref (v).pq, initq);
    }

    void READRAWNUM(ref NUMBER v, NUMBER init) => dupnum(ref v, init);


    void INIT_AND_DUMP_RAW_NUM_IF_NULL(ref NUMBER r, int32_t v)
    {
        if (r == null)
        {
            r = i32tonum(v, BASEX);
            DUMPRAWNUM(r);
        }
    }

    void INIT_AND_DUMP_RAW_RAT_IF_NULL(ref RAT r, int32_t v)
    {
        if (r == null)
        {
            r = i32torat(v);
            DUMPRAWRAT(r);
        }
    }

    const int32_t RATIO_FOR_DECIMAL = 9;
    const int32_t DECIMAL = 10;
    const int32_t CALC_DECIMAL_DIGITS_DEFAULT = 32;

    int32_t cbitsofprecision = RATIO_FOR_DECIMAL * DECIMAL * CALC_DECIMAL_DIGITS_DEFAULT;

// #include "ratconst.h"
//
// #endif

    bool g_ftrueinfinite = false; // Set to true if you don't want
    // chopping internally
    // precision used internally

// PNUMBER num_one = nullptr;
// PNUMBER num_two = nullptr;
// PNUMBER num_five = nullptr;
// PNUMBER num_six = nullptr;
// PNUMBER num_ten = nullptr;
//
// PRAT ln_ten = nullptr;
// PRAT ln_two = nullptr;
// PRAT rat_zero = nullptr;
// PRAT rat_one = nullptr;
// PRAT rat_neg_one = nullptr;
// PRAT rat_two = nullptr;
// PRAT rat_six = nullptr;
// PRAT rat_half = nullptr;
// PRAT rat_ten = nullptr;
// PRAT pt_eight_five = nullptr;
// PRAT pi = nullptr;
// PRAT pi_over_two = nullptr;
// PRAT two_pi = nullptr;
// PRAT one_pt_five_pi = nullptr;
// PRAT e_to_one_half = nullptr;
// PRAT rat_exp = nullptr;
// PRAT rad_to_deg = nullptr;
// PRAT rad_to_grad = nullptr;
// PRAT rat_qword = nullptr;
// PRAT rat_dword = nullptr; // unsigned max ui32
// PRAT rat_word = nullptr;
// PRAT rat_byte = nullptr;
// PRAT rat_360 = nullptr;
// PRAT rat_400 = nullptr;
// PRAT rat_180 = nullptr;
// PRAT rat_200 = nullptr;
// PRAT rat_nRadix = nullptr;
// PRAT rat_smallest = nullptr;
// PRAT rat_negsmallest = nullptr;
// PRAT rat_max_exp = nullptr;
// PRAT rat_min_exp = nullptr;
// PRAT rat_max_fact = nullptr;
// PRAT rat_min_fact = nullptr;
// PRAT rat_min_i32 = nullptr; // min signed i32
// PRAT rat_max_i32 = nullptr; // max signed i32

//----------------------------------------------------------------------------
//
//  FUNCTION: ChangeConstants
//
//  ARGUMENTS:  base changing to, and precision to use.
//
//  RETURN: None
//
//  SIDE EFFECTS: sets a mess of constants.
//
//
//----------------------------------------------------------------------------

    public void ChangeConstants(uint32_t radix, int32_t precision)
    {
        // ratio is set to the number of digits in the current radix, you can get
        // in the internal BASEX radix, this is important for length calculations
        // in translating from radix to BASEX and back.

        g_ratio = (int32_t)(Math.Ceiling(BASEXPWR / Math.Log(radix, 2))) - 1;

        destroyrat(ref rat_nRadix);
        rat_nRadix = i32torat((int32_t)radix);

        // Check to see what we have to recalculate and what we don't
        if (cbitsofprecision < (g_ratio * (int32_t)(radix) * precision))
        {
            g_ftrueinfinite = false;

            INIT_AND_DUMP_RAW_NUM_IF_NULL(ref num_one, 1);
            INIT_AND_DUMP_RAW_NUM_IF_NULL(ref num_two, 2);
            INIT_AND_DUMP_RAW_NUM_IF_NULL(ref num_five, 5);
            INIT_AND_DUMP_RAW_NUM_IF_NULL(ref num_six, 6);
            INIT_AND_DUMP_RAW_NUM_IF_NULL(ref num_ten, 10);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_six, 6);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_two, 2);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_zero, 0);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_one, 1);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_neg_one, -1);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_ten, 10);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_word, 0xffff);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_word, 0xff);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_400, 400);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_360, 360);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_200, 200);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_180, 180);
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_max_exp, 100000);

            // 3248, is the max number for which calc is able to compute factorial, after that it is unable to compute due to overflow.
            // Hence restricted factorial range as at most 3248.Beyond that calc will throw overflow error immediately.
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_max_fact, 3249);

            // -1000, is the min number for which calc is able to compute factorial, after that it takes too long to compute.
            INIT_AND_DUMP_RAW_RAT_IF_NULL(ref rat_min_fact, -1000);

            duprat(ref rat_smallest, rat_nRadix);
            ratpowi32(ref rat_smallest, -precision, precision);
            duprat(ref rat_negsmallest, rat_smallest);
            rat_negsmallest.pp.sign = -1;
            DUMPRAWRAT(rat_smallest);
            DUMPRAWRAT(rat_negsmallest);

            if (rat_half == null)
            {
                createrat(ref rat_half);
                dupnum(ref rat_half.pp, num_one);
                dupnum(ref rat_half.pq, num_two);
                DUMPRAWRAT(rat_half);
            }

            if (pt_eight_five == null)
            {
                createrat(ref pt_eight_five);
                pt_eight_five.pp = i32tonum(85, BASEX);
                pt_eight_five.pq = i32tonum(100, BASEX);
                DUMPRAWRAT(pt_eight_five);
            }

            duprat(ref rat_qword, rat_two);
            numpowi32(ref (rat_qword.pp), 64, BASEX, precision);
            subrat(ref rat_qword, rat_one, precision);
            DUMPRAWRAT(rat_qword);

            duprat(ref rat_dword, rat_two);
            numpowi32(ref (rat_dword.pp), 32, BASEX, precision);
            subrat(ref rat_dword, rat_one, precision);
            DUMPRAWRAT(rat_dword);

            duprat(ref rat_max_i32, rat_two);
            numpowi32(ref (rat_max_i32.pp), 31, BASEX, precision);
            duprat(ref rat_min_i32, rat_max_i32);
            subrat(ref rat_max_i32, rat_one, precision); // rat_max_i32 = 2^31 -1
            DUMPRAWRAT(rat_max_i32);

            rat_min_i32.pp.sign *= -1; // rat_min_i32 = -2^31
            DUMPRAWRAT(rat_min_i32);

            duprat(ref rat_min_exp, rat_max_exp);
            rat_min_exp.pp.sign *= -1;
            DUMPRAWRAT(rat_min_exp);

            cbitsofprecision = unchecked(g_ratio * (int32_t)radix * precision);

            // Apparently when dividing 180 by pi, another (interna) digit of
            // precision is needed.
            int32_t extraPrecision = precision + g_ratio;
            duprat(ref pi, rat_half);
            asinrat(ref pi, radix, extraPrecision);
            mulrat(ref pi, rat_six, extraPrecision);
            DUMPRAWRAT(pi);

            duprat(ref two_pi, pi);
            duprat(ref pi_over_two, pi);
            duprat(ref one_pt_five_pi, pi);
            addrat(ref two_pi, pi, extraPrecision);
            DUMPRAWRAT(two_pi);

            divrat(ref pi_over_two, rat_two, extraPrecision);
            DUMPRAWRAT(pi_over_two);

            addrat(ref one_pt_five_pi, pi_over_two, extraPrecision);
            DUMPRAWRAT(one_pt_five_pi);

            duprat(ref e_to_one_half, rat_half);
            _exprat(ref e_to_one_half, extraPrecision);
            DUMPRAWRAT(e_to_one_half);

            duprat(ref rat_exp, rat_one);
            _exprat(ref rat_exp, extraPrecision);
            DUMPRAWRAT(rat_exp);

            // WARNING: remember lograt uses exponent constants calculated above...

            duprat(ref ln_ten, rat_ten);
            lograt(ref ln_ten, extraPrecision);
            DUMPRAWRAT(ln_ten);

            duprat(ref ln_two, rat_two);
            lograt(ref ln_two, extraPrecision);
            DUMPRAWRAT(ln_two);

            destroyrat(ref rad_to_deg);
            rad_to_deg = i32torat(180);
            divrat(ref rad_to_deg, pi, extraPrecision);
            DUMPRAWRAT(rad_to_deg);

            destroyrat(ref rad_to_grad);
            rad_to_grad = i32torat(200);
            divrat(ref rad_to_grad, pi, extraPrecision);
            DUMPRAWRAT(rad_to_grad);
        }
        else
        {
            _readconstants();

            duprat(ref rat_smallest, rat_nRadix);
            ratpowi32(ref rat_smallest, -precision, precision);
            duprat(ref rat_negsmallest, rat_smallest);
            rat_negsmallest.pp.sign = -1;
        }
    }

//----------------------------------------------------------------------------
//
//  FUNCTION: intrat
//
//  ARGUMENTS:  pointer to x PRAT representation of number
//
//  RETURN: no return value x PRAT is smashed with integral number
//
//
//----------------------------------------------------------------------------

    public void intrat(ref PRAT px, uint32_t radix, int32_t precision)
    {
        // Only do the intrat operation if number is nonzero.
        // and only if the bottom part is not one.
        if (!zernum((px).pp) && !equnum((px).pq, num_one))
        {
            flatrat(ref px, radix, precision);

            // Subtract the fractional part of the rational
            PRAT pret = null;
            duprat(ref pret, px);
            remrat(ref pret, rat_one);

            // Flatten pret in case it's not aligned with px after remrat operation
            if (!equnum((px).pq, pret.pq))
            {
                flatrat(ref pret, radix, precision);
            }

            subrat(ref px, pret, precision);
            destroyrat(ref pret);

            // Simplify the value if possible to resolve rounding errors
            flatrat(ref px, radix, precision);
        }
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: rat_equ
    //
    //  ARGUMENTS:  PRAT a and PRAT b
    //
    //  RETURN: true if equal false otherwise.
    //
    //
    //---------------------------------------------------------------------------
    public bool rat_equ(PRAT a, PRAT b, int32_t precision)

    {
        PRAT rattmp = null;
        duprat(ref rattmp, a);
        rattmp.pp.sign *= -1;
        addrat(ref rattmp, b, precision);
        bool bret = zernum(rattmp.pp);
        destroyrat(ref rattmp);
        return (bret);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: rat_ge
    //
    //  ARGUMENTS:  PRAT a, PRAT b and int32_t precision
    //
    //  RETURN: true if a is greater than or equal to b
    //
    //
    //---------------------------------------------------------------------------
    bool rat_ge(PRAT a, PRAT b, int32_t precision)

    {
        PRAT rattmp = null;
        duprat(ref rattmp, a);
        b.pp.sign *= -1;
        addrat(ref rattmp, b, precision);
        b.pp.sign *= -1;
        bool bret = (zernum(rattmp.pp) || SIGN(rattmp) == 1);
        destroyrat(ref rattmp);
        return (bret);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: rat_gt
    //
    //  ARGUMENTS:  PRAT a and PRAT b
    //
    //  RETURN: true if a is greater than b
    //
    //
    //---------------------------------------------------------------------------
    public bool rat_gt(PRAT a, PRAT b, int32_t precision)

    {
        PRAT rattmp = null;
        duprat(ref rattmp, a);
        b.pp.sign *= -1;
        addrat(ref rattmp, b, precision);
        b.pp.sign *= -1;
        bool bret = (!zernum(rattmp.pp) && SIGN(rattmp) == 1);
        destroyrat(ref rattmp);
        return (bret);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: rat_le
    //
    //  ARGUMENTS:  PRAT a, PRAT b and int32_t precision
    //
    //  RETURN: true if a is less than or equal to b
    //
    //
    //---------------------------------------------------------------------------
    bool rat_le(PRAT a, PRAT b, int32_t precision)

    {
        PRAT rattmp = null;
        duprat(ref rattmp, a);
        b.pp.sign *= -1;
        addrat(ref rattmp, b, precision);
        b.pp.sign *= -1;
        bool bret = (zernum(rattmp.pp) || SIGN(rattmp) == -1);
        destroyrat(ref rattmp);
        return (bret);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: rat_lt
    //
    //  ARGUMENTS:  PRAT a, PRAT b and int32_t precision
    //
    //  RETURN: true if a is less than b
    //
    //
    //---------------------------------------------------------------------------

    public bool rat_lt(PRAT a, PRAT b, int32_t precision)

    {
        PRAT rattmp = null;
        duprat(ref rattmp, a);
        b.pp.sign *= -1;
        addrat(ref rattmp, b, precision);
        b.pp.sign *= -1;
        bool bret = (!zernum(rattmp.pp) && SIGN(rattmp) == -1);
        destroyrat(ref rattmp);
        return (bret);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: rat_neq
    //
    //  ARGUMENTS:  PRAT a and PRAT b
    //
    //  RETURN: true if a is not equal to b
    //
    //
    //---------------------------------------------------------------------------

    public bool rat_neq(PRAT a, PRAT b, int32_t precision)
    {
        PRAT rattmp = null;
        duprat(ref rattmp, a);
        rattmp.pp.sign *= -1;
        addrat(ref rattmp, b, precision);
        bool bret = !(zernum(rattmp.pp));
        destroyrat(ref rattmp);
        return (bret);
    }

    //---------------------------------------------------------------------------
    //
    //  function: scale
    //
    //  ARGUMENTS:  pointer to x PRAT representation of number, and scaling factor
    //
    //  RETURN: no return, value x PRAT is smashed with a scaled number in the
    //          range of the scalefact.
    //
    //---------------------------------------------------------------------------

    public void scale(ref PRAT px, PRAT scalefact, uint32_t radix, int32_t precision)
    {
        PRAT pret = null;
        duprat(ref pret, px);

        // Logscale is a quick way to tell how much extra precision is needed for
        // scaling by scalefact.
        int32_t logscale = g_ratio * ((pret.pp.cdigit + pret.pp.exp) - (pret.pq.cdigit + pret.pq.exp));
        if (logscale > 0)
        {
            precision += logscale;
        }

        divrat(ref pret, scalefact, precision);
        intrat(ref pret, radix, precision);
        mulrat(ref pret, scalefact, precision);
        pret.pp.sign *= -1;
        addrat(ref px, pret, precision);

        destroyrat(ref pret);
    }

    //---------------------------------------------------------------------------
    //
    //  function: scale2pi
    //
    //  ARGUMENTS:  pointer to x PRAT representation of number
    //
    //  RETURN: no return, value x PRAT is smashed with a scaled number in the
    //          range of 0..2pi
    //
    //---------------------------------------------------------------------------

    public void scale2pi(ref PRAT px, uint32_t radix, int32_t precision)
    {
        PRAT pret = null;
        PRAT my_two_pi = null;
        duprat(ref pret, px);

        // Logscale is a quick way to tell how much extra precision is needed for
        // scaling by 2 pi.
        int32_t logscale = g_ratio * ((pret.pp.cdigit + pret.pp.exp) - (pret.pq.cdigit + pret.pq.exp));
        if (logscale > 0)
        {
            precision += logscale;
            duprat(ref my_two_pi, rat_half);
            asinrat(ref my_two_pi, radix, precision);
            mulrat(ref my_two_pi, rat_six, precision);
            mulrat(ref my_two_pi, rat_two, precision);
        }
        else
        {
            duprat(ref my_two_pi, two_pi);
            logscale = 0;
        }

        divrat(ref pret, my_two_pi, precision);
        intrat(ref pret, radix, precision);
        mulrat(ref pret, my_two_pi, precision);
        pret.pp.sign *= -1;
        addrat(ref px, pret, precision);

        destroyrat(ref my_two_pi);
        destroyrat(ref pret);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: inbetween
    //
    //  ARGUMENTS:  PRAT *px, and PRAT range.
    //
    //  RETURN: none, changes *px to -/+range, if px is outside -range..+range
    //
    //---------------------------------------------------------------------------

    public void inbetween(ref PRAT px, PRAT range, int32_t precision)
    {
        if (rat_gt(px, range, precision))
        {
            duprat(ref px, range);
        }
        else
        {
            range.pp.sign *= -1;
            if (rat_lt(px, range, precision))
            {
                duprat(ref px, range);
            }

            range.pp.sign *= -1;
        }
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: _dumprawrat
    //
    //  ARGUMENTS:  const wchar *name of variable, PRAT x, output stream out
    //
    //  RETURN: none, prints the results of a dump of the internal structures
    //          of a PRAT, suitable for READRAWRAT to stderr.
    //
    //---------------------------------------------------------------------------

    public void _dumprawrat(string varname, PRAT rat, TextWriter output)
    {
        _dumprawnum(varname, rat.pp, output);
        _dumprawnum(varname, rat.pq, output);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: _dumprawnum
    //
    //  ARGUMENTS:  const wchar *name of variable, PNUMBER num, output stream out
    //
    //  RETURN: none, prints the results of a dump of the internal structures
    //          of a PNUMBER, suitable for READRAWNUM to stderr.
    //
    //---------------------------------------------------------------------------

    public void _dumprawnum(string varname, PNUMBER num, TextWriter output)
    {
        output.WriteLine($"NUMBER {varname} = {{");
        output.WriteLine($"\t{num.sign},");
        output.WriteLine($"\t{num.cdigit},");
        output.WriteLine($"\t{num.exp},");
        output.Write("\t{ ");

        for (int i = 0; i < num.cdigit; i++)
        {
            output.Write($" {num.mant[i]},");
        }

        output.WriteLine("}");
        output.WriteLine("};");
    }

    void _readconstants()
    {
        READRAWNUM(ref num_one, init_num_one);
        READRAWNUM(ref num_two, init_num_two);
        READRAWNUM(ref num_five, init_num_five);
        READRAWNUM(ref num_six, init_num_six);
        READRAWNUM(ref num_ten, init_num_ten);

        READRAWRAT(ref pt_eight_five, init_p_pt_eight_five, init_q_pt_eight_five);
        READRAWRAT(ref rat_six, init_p_rat_six, init_q_rat_six);
        READRAWRAT(ref rat_two, init_p_rat_two, init_q_rat_two);
        READRAWRAT(ref rat_zero, init_p_rat_zero, init_q_rat_zero);
        READRAWRAT(ref rat_one, init_p_rat_one, init_q_rat_one);
        READRAWRAT(ref rat_neg_one, init_p_rat_neg_one, init_q_rat_neg_one);
        READRAWRAT(ref rat_half, init_p_rat_half, init_q_rat_half);
        READRAWRAT(ref rat_ten, init_p_rat_ten, init_q_rat_ten);
        READRAWRAT(ref pi, init_p_pi, init_q_pi);
        READRAWRAT(ref two_pi, init_p_two_pi, init_q_two_pi);
        READRAWRAT(ref pi_over_two, init_p_pi_over_two, init_q_pi_over_two);
        READRAWRAT(ref one_pt_five_pi, init_p_one_pt_five_pi, init_q_one_pt_five_pi);
        READRAWRAT(ref e_to_one_half, init_p_e_to_one_half, init_q_e_to_one_half);
        READRAWRAT(ref rat_exp, init_p_rat_exp, init_q_rat_exp);
        READRAWRAT(ref ln_ten, init_p_ln_ten, init_q_ln_ten);
        READRAWRAT(ref ln_two, init_p_ln_two, init_q_ln_two);
        READRAWRAT(ref rad_to_deg, init_p_rad_to_deg, init_q_rad_to_deg);
        READRAWRAT(ref rad_to_grad, init_p_rad_to_grad, init_q_rad_to_grad);
        READRAWRAT(ref rat_qword, init_p_rat_qword, init_q_rat_qword);
        READRAWRAT(ref rat_dword, init_p_rat_dword, init_q_rat_dword);
        READRAWRAT(ref rat_word, init_p_rat_word, init_q_rat_word);
        READRAWRAT(ref rat_byte, init_p_rat_byte, init_q_rat_byte);
        READRAWRAT(ref rat_360, init_p_rat_360, init_q_rat_360);
        READRAWRAT(ref rat_400, init_p_rat_400, init_q_rat_400);
        READRAWRAT(ref rat_180, init_p_rat_180, init_q_rat_180);
        READRAWRAT(ref rat_200, init_p_rat_200, init_q_rat_200);
        READRAWRAT(ref rat_smallest, init_p_rat_smallest, init_q_rat_smallest);
        READRAWRAT(ref rat_negsmallest, init_p_rat_negsmallest, init_q_rat_negsmallest);
        READRAWRAT(ref rat_max_exp, init_p_rat_max_exp, init_q_rat_max_exp);
        READRAWRAT(ref rat_min_exp, init_p_rat_min_exp, init_q_rat_min_exp);
        READRAWRAT(ref rat_max_fact, init_p_rat_max_fact, init_q_rat_max_fact);
        READRAWRAT(ref rat_min_fact, init_p_rat_min_fact, init_q_rat_min_fact);
        READRAWRAT(ref rat_min_i32, init_p_rat_min_i32, init_q_rat_min_i32);
        READRAWRAT(ref rat_max_i32, init_p_rat_max_i32, init_q_rat_max_i32);
    }

    //---------------------------------------------------------------------------
    //
    //  FUNCTION: trimit
    //
    //  ARGUMENTS:  PRAT *px, int32_t precision
    //
    //
    //  DESCRIPTION: Chops off digits from rational numbers to avoid time
    //  explosions in calculations of functions using series.
    //  It can be shown that it is enough to only keep the first n digits
    //  of the largest of p or q in the rational p over q form, and of course
    //  scale the smaller by the same number of digits.  This will give you
    //  n-1 digits of accuracy.  This dramatically speeds up calculations
    //  involving hundreds of digits or more.
    //  The last part of this trim dealing with exponents never affects accuracy
    //
    //  RETURN: none, modifies the pointed to PRAT
    //
    //---------------------------------------------------------------------------
    void trimit(ref PRAT px, int32_t precision)
    {
        if (!g_ftrueinfinite)
        {
            PNUMBER? pp = px.pp;
            PNUMBER? pq = px.pq;

            if (pp != null && pq != null)
            {
                int32_t trim = g_ratio * (Math.Min((pp.cdigit + pp.exp), (pq.cdigit + pq.exp)) - 1) - precision;

                if (trim > g_ratio)
                {
                    trim /= g_ratio;

                    if (trim <= pp.exp)
                    {
                        pp.exp -= trim;
                    }
                    else
                    {
                        Array.Copy(pp.mant, trim - pp.exp, pp.mant, 0, pp.cdigit - trim + pp.exp);
                        pp.cdigit -= trim - pp.exp;
                        pp.exp = 0;
                    }

                    if (trim <= pq.exp)
                    {
                        pq.exp -= trim;
                    }
                    else
                    {
                        Array.Copy(pq.mant, trim - pq.exp, pq.mant, 0, pq.cdigit - trim + pq.exp);
                        pq.cdigit -= trim - pq.exp;
                        pq.exp = 0;
                    }
                }

                trim = Math.Min(pp.exp, pq.exp);
                pp.exp -= trim;
                pq.exp -= trim;
            }
        }
    }
}
