namespace GraphingTests;

internal readonly record struct AffineMinMaxWindowsCompatibilityMatrixTestsLinePair(AffineMinMaxWindowsCompatibilityMatrixTestsLineSpec Left, AffineMinMaxWindowsCompatibilityMatrixTestsLineSpec Right);
