// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// #pragma once


namespace CalcEngine;

internal sealed partial class RatPak
{
    /*
     Converted to csharp using this monster regex:
     ```
     (static RatPakNUMBER init_[a-zA-Z_0-9]+)\s*=\s*\{\s*(-?[0-9]+),\s*(-?[0-9]+),\s*(-?[0-9]+),\s*\{\s*([\s\S]*?)\s*\}\s*\};
     ```

     Replacement pattern:
     ```
     $1 = new RatPakNUMBER(){ sign = $2,
                                            cdigit= $3,
                                           exp =  $4,
                                            mant =  [
                                                $5
                                            ] };
     ```
     */

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_num_one = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_num_two = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            2,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_num_five = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            5,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_num_six = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            6,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_num_ten = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            10,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_smallest = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_smallest = new()
    {
        sign = 1,
        cdigit = 4,
        exp = 0,
        mant =
        [
            0,
            190439170,
            901055854,
            10097,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_negsmallest = new()
    {
        sign = -1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_negsmallest = new()
    {
        sign = 1,
        cdigit = 4,
        exp = 0,
        mant =
        [
            0,
            190439170,
            901055854,
            10097,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_pt_eight_five = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            85,
        ]
    };

    static readonly RatPakNUMBER init_q_pt_eight_five = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            100,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_six = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            6,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_six = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_two = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            2,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_two = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_zero = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            0,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_zero = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_one = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_one = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_neg_one = new()
    {
        sign = -1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_neg_one = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_half = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_half = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            2,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_ten = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            10,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_ten = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_pi = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            125527896,
            283898350,
            1960493936,
            1672850762,
            1288168272,
            8,
        ]
    };

    static readonly RatPakNUMBER init_q_pi = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            1288380402,
            1120116153,
            1860424692,
            1944118326,
            1583591604,
            2,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_two_pi = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            251055792,
            567796700,
            1773504224,
            1198217877,
            428852897,
            17,
        ]
    };

    static readonly RatPakNUMBER init_q_two_pi = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            1288380402,
            1120116153,
            1860424692,
            1944118326,
            1583591604,
            2,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_pi_over_two = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            125527896,
            283898350,
            1960493936,
            1672850762,
            1288168272,
            8,
        ]
    };

    static readonly RatPakNUMBER init_q_pi_over_two = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            429277156,
            92748659,
            1573365737,
            1740753005,
            1019699561,
            5,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_one_pt_five_pi = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            1241201312,
            270061909,
            1051574664,
            1924965045,
            1340320627,
            70,
        ]
    };

    static readonly RatPakNUMBER init_q_one_pt_five_pi = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            1579671539,
            1837970263,
            1067644340,
            523549916,
            2119366659,
            14,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_e_to_one_half = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            256945612,
            216219427,
            223516738,
            477442596,
            581063757,
            23,
        ]
    };

    static readonly RatPakNUMBER init_q_e_to_one_half = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            1536828363,
            698484484,
            1127331835,
            224219346,
            245499408,
            14,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_exp = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            943665199,
            1606559160,
            1094967530,
            1759391384,
            1671799163,
            1123581,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_exp = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            879242208,
            2022880100,
            617392930,
            1374929092,
            1367479163,
            413342,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_ln_ten = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            2086268922,
            165794492,
            1416063951,
            1851428830,
            1893239400,
            65366841,
        ]
    };

    static readonly RatPakNUMBER init_q_ln_ten = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            26790652,
            564532679,
            783998273,
            216030448,
            1564709968,
            28388458,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_ln_two = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            1789230241,
            1057927868,
            715399197,
            908801241,
            1411265331,
            3,
        ]
    };

    static readonly RatPakNUMBER init_q_ln_two = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            1559869847,
            1930657510,
            1228561531,
            219003871,
            593099283,
            5,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rad_to_deg = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            2127722024,
            1904928383,
            2016479213,
            2048947859,
            1578647346,
            492,
        ]
    };

    static readonly RatPakNUMBER init_q_rad_to_deg = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            125527896,
            283898350,
            1960493936,
            1672850762,
            1288168272,
            8,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rad_to_grad = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            2125526288,
            684931327,
            570267400,
            129125085,
            1038224725,
            547,
        ]
    };

    static readonly RatPakNUMBER init_q_rad_to_grad = new()
    {
        sign = 1,
        cdigit = 6,
        exp = 0,
        mant =
        [
            125527896,
            283898350,
            1960493936,
            1672850762,
            1288168272,
            8,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_qword = new()
    {
        sign = 1,
        cdigit = 3,
        exp = 0,
        mant =
        [
            2147483647,
            2147483647,
            3,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_qword = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_dword = new()
    {
        sign = 1,
        cdigit = 2,
        exp = 0,
        mant =
        [
            2147483647,
            1,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_dword = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_p_rat_max_i32 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            2147483647,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_max_i32 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_p_rat_min_i32 = new()
    {
        sign = -1,
        cdigit = 2,
        exp = 0,
        mant =
        [
            0,
            1,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_min_i32 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    static readonly RatPakNUMBER init_p_rat_word = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            65535,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_word = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_byte = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            255,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_byte = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_400 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            400,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_400 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_360 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            360,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_360 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_200 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            200,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_200 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_180 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            180,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_180 = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_max_exp = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            100000,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_max_exp = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_min_exp = new()
    {
        sign = -1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            100000,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_min_exp = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_max_fact = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            3249,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_max_fact = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };

    // Autogenerated by _dumprawrat in support.cpp
    static readonly RatPakNUMBER init_p_rat_min_fact = new()
    {
        sign = -1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1000,
        ]
    };

    static readonly RatPakNUMBER init_q_rat_min_fact = new()
    {
        sign = 1,
        cdigit = 1,
        exp = 0,
        mant =
        [
            1,
        ]
    };
}
