// <auto-generated>
// Generated by Tools/Cldr/GenerateCurrencyData.cs. Do not edit by hand.
// Unicode CLDR 48.2 (release-48-2), Unicode License v3.
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/supplementalData.xml SHA-256: cd2af39aef82fdbfba4d591c87548203350538ad2318486d104b3b38b8d62f1a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/likelySubtags.xml SHA-256: b0049bc6420715b1e3010f43d95745dca227c5aa60357d1d89a1bdcb06287312
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/root.xml SHA-256: f69ab139130793ab721b6d1be8c1385b9a051e0b7c5893615533bcfa7bab0448
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en.xml SHA-256: 67607f4c9cf57157e70564987d8ae92a9ddcd73c00a2f1cd6abf79524a969cbd
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/af.xml SHA-256: 20b451a89365e131dea91d7d2d40e41080272b6f7c3316786da209bcff30398f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/af_ZA.xml SHA-256: 801902bcdee20e89b187a78e000ff4981820cc7fd3a8fbd3898a9c9b973e4dc1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/am.xml SHA-256: 3bc0a05c2a9d46ccee8916e0f21acf873d0d08f7c3264091b1a4f3f1b379b1a2
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/am_ET.xml SHA-256: 9c0768faa449f7b76bff9f7beee0ee8980173f643854f91cebe574e83b45160d
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ar.xml SHA-256: 94b2fea65038e61fa34b9b3efd728ab55e12c77644e61d283e63464ff57e13b7
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ar_SA.xml SHA-256: d73a53c609c4ba48079ef0d03d8a40b7da6d6c98e4d246d780ad09b8fd5c4d17
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az.xml SHA-256: 36a770b21b3a3d9eb2f93145539e446a2325feb11bd28e9a92890255a3024cce
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az_Latn.xml SHA-256: b6c1969b63c4697873232d780c90518adb9e881e842beb47b33048136f523868
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az_Latn_AZ.xml SHA-256: c859b9a884a5d0b0a1ac2ee9115fa5b5ff43f218ece53f8afb8d8ea859450d12
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/bg.xml SHA-256: 05bcf474ad3dc89fbc0216955a3a6279d1aad884e916cade8ff36a22dbca95b7
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/bg_BG.xml SHA-256: 2666dd2e18e5592c313668bf09f535bdd5fad573d51f0ce6887e20dd79fdb3ba
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ca.xml SHA-256: a9ff4dfaae2a5e3a649cbf0f636739943e3b8d25dab60cc35fd5b43a5230daae
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ca_ES.xml SHA-256: f551ca8ff440994082383f616c9c7220623699837c65ba1e635711e54de6ba01
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/cs.xml SHA-256: 151aa6e1d2e24c75e03b0332a8c41d7481fdc994c9b5b04c9e92da48142da063
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/cs_CZ.xml SHA-256: 3b4844952a606994368600b102fcd0fc9326e6d757cf94a64ccc24868e036050
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/da.xml SHA-256: b5aa90916fab9a53b85db89dd5a77ca24f6ec088e002be56493f9b11bd1a540a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/da_DK.xml SHA-256: 0cb179c3339dbe6d8c634f56be47c25a70e7ae0ef88a8c32a74bd293b4c7c2b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/de.xml SHA-256: 15dbc0a59d188b243b9bd781ae245267f700ec8cd1b1d93ed760e5dd1b3cc1c6
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/de_DE.xml SHA-256: 99f0946614cae7042b1ddfe8cc2c9dbdac4e2dae03737458b35f89e203123d12
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/el.xml SHA-256: 54726ba13bd4a441d71c63971595b96507719d977f1f37030d12d2afff90aeef
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/el_GR.xml SHA-256: aa13bf9f2da976ae559f311cf191bdd1a9fa8b0d87d44a6e34973b30cf985d98
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en_001.xml SHA-256: 193f863c209a257ceed90d112a59b43a994dde966e7c5d80c13c6477809dfc10
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en_GB.xml SHA-256: 5261b3507bf6a396ba22114d1ce5107760f5d14a1752b2689e082ef2958fe97c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es.xml SHA-256: 727d29597d9e0e4f7a1951ebb26aca2f063f89d07190c933ee56451c01334d27
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_419.xml SHA-256: 19b75df6f5c4961ef91cdb855d0f876726b6e2fc2a5b7c0c2a8c0694597f83ca
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_ES.xml SHA-256: d5111fc5c17d178837638fafe0b88573997e833972e3887fba71babe486e307c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_MX.xml SHA-256: b994e67254ce8d1435c7e8510d0481e6bebfa4d153cfe54f7125f236e971b292
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/et.xml SHA-256: f0c23e226c9fccf2f154ce5c49ccc788e3f6cb74ea2bee0669c2d79191ebcc5c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/et_EE.xml SHA-256: 7a2d20a32824022444db1f90fc1a10752892f1aeb92fd38c7fccde995ef6e3d9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/eu.xml SHA-256: 8d2775a2934e2c182b590410cde7ddf37e7307b750c2cbec11609abf97bcc44b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/eu_ES.xml SHA-256: 4318c639084c7edb46bd00bac9c289088b8b76a50ebc37b573c9d57d9f2ea146
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fa.xml SHA-256: f71b3b72c6713a4963213f2f1e7452131fa3a4f31201a6d9d6339bb3b340c8f5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fa_IR.xml SHA-256: 5a56adc9c1c28845abf2807548293d568c92364a45d4154493605c3b5d353fe9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fi.xml SHA-256: 62e1cb0f375342d128d4f0b2f2e8c014fdad3b3f891e2e476389c592fe1d5211
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fi_FI.xml SHA-256: 94802b05b89445098cf252a23f0c353c3adb3417952f1a123050b47c6a035137
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fil.xml SHA-256: 35db740e7e262d673979c2ffdbcd2aa1cd603bdc849f579bc47e272bc87304c0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fil_PH.xml SHA-256: 050ca9edbb90b7fffebdcb93b0d5afd9d1aa2debd3a5a0f8d144a15f609dbdd0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr.xml SHA-256: ebc67e303a56940609c892ededb3697e3b291466cf9622dd2c389ad48872e98f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr_CA.xml SHA-256: a97a8db94d3985e98153bccd654fcd3d561508a53dad6b643c2ff51d74743b5b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr_FR.xml SHA-256: 318de22de28f6311a2dfb2667d74487e77dc2b15c674d6b4722a08f88bb74fd0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/gl.xml SHA-256: b4bb8c58098d28595a46664dd4bb95c1bac4cc6f44854cd787bca1a45da39b7c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/gl_ES.xml SHA-256: ee882db01a31fa360cbd000b5361825d139373f9055d21ee4c451e372f295450
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/he.xml SHA-256: 7ad7f3e74991ad8f1114af6a17b282e6293a930479ff64c8198ea74786f125ac
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/he_IL.xml SHA-256: 96dea29e402000711a76fec89124cb0e640c8b7107d16aa0ff655b64994b781e
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hi.xml SHA-256: 5fa900f98f3f4ca70f73af23925783f73c62856d84892be9f364e05f4f10b261
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hi_IN.xml SHA-256: 304735ac18a0955ee910e726cab7c99c28ba090302b8a7e4d4f56850de5a522c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hr.xml SHA-256: 596312055725975849e4fe61de314a6457646a04c063daa90fe34da41e7512b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hr_HR.xml SHA-256: f2f47049eb174673601f214f77f5ebcafe319e7646ef6eae7f66b75d3dd0af5f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hu.xml SHA-256: 3bc035f25ceebbee050437f97f2021d18b6c8c818970978eb7f617e2a286eef5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hu_HU.xml SHA-256: 63c7f180d405d8fbc88f1ed7e65d3200263a6227311ef90335c41daeb946ae49
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/id.xml SHA-256: 361f434ecedb64caba5ab9be046d51540673f890a8d7b0c6a4ba8f9a960f21e5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/id_ID.xml SHA-256: 5357f507d0e2fdbca8d3701c58c86b3a96cc53567611db52d3cfb2f58a738072
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/is.xml SHA-256: 7c9ed6be258df6773db5eae302a77f134d0d674c727f29e5baee4699e418ce67
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/is_IS.xml SHA-256: 6e76fa55260447493bde0335e9efc805eff69ab3752cdaa55d06cb7db488c800
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/it.xml SHA-256: cf1e21c333efa6b61c769be824f8a410503f210f60ee157fa40ed12950dcd632
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/it_IT.xml SHA-256: 10c3b71698aefa3f2ca109728b1264ba1c1eac5e534afb1a554517813821c424
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ja.xml SHA-256: 24bc2347a4fc2d1d331f122f5f4c4f05ce435513f4f5280b16a428aad8753fdc
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ja_JP.xml SHA-256: 98e368020af382040bd1541b5cb718e6a9e6e1989bbfe9c5ca7b9180c2d32036
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kk.xml SHA-256: 6050ee58682d00307e51edcdeb3abe5daada9d3cf729917556c65b499a1a53e5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kk_KZ.xml SHA-256: 48e0343b68f35b6d381bb3b94e3df486ce91dba3552ca24da7e1561218c2335a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/km.xml SHA-256: aeae2c7371d91146ffe626ef4e038d443697055b106b48d964336428541531b8
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/km_KH.xml SHA-256: 452d6b0df9cb1e39b15380b7cd6fb35b6e88f85d30cb55298f271eb672d88ab9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kn.xml SHA-256: 913971145002f04c35fa0f8a439c11be7d761d5fc766462f8f829c2541a392af
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kn_IN.xml SHA-256: 1c049934ad5fd3f2590217dc77b808ed9e5f3da3d636e1cde2867db14c6baace
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ko.xml SHA-256: d2f0deacc2773eb4f5d9b6afc0f853a5dcd96ca1f0d26341a65c717407edde56
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ko_KR.xml SHA-256: 7d94aaf6deabbe8c1ef0f84876f4c75b53fcbeb6ae7a601ec991ff44678aa6a3
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lo.xml SHA-256: 44d5f488d09ff9c52b17d5ac717701105bdd01b3c62fcc6cefeb4f9e6277ac0a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lo_LA.xml SHA-256: cbc425642c092f8f3d9c70644ce1bc874ebeaa24451dab64143d61c9e2269245
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lt.xml SHA-256: da63b7b3e57e9a3910cb93bd736e897c0b33cf39762fd4e25bc41186c4d89911
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lt_LT.xml SHA-256: 7b5ee89b03bec5cb0cb7113451a678fcecf373d71f4852023cf74be259201ef5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lv.xml SHA-256: 9a246ca33dae57aa90cede63c3580c3690d10404f633dbf61daa6fd7dcd103d0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lv_LV.xml SHA-256: ee658897ceb7d0754ffb8d9e71b581195bd812353b5dddd5e69925ac592a2f6a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/mk.xml SHA-256: 4480bf96ff97782538a9ac40dd26cc0ff121809eeb348e84d193d9cbb6928faf
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/mk_MK.xml SHA-256: 4ea1787b13c68f2c77e87405cb419ffa9d211f7a66743fff521fb5a1977b71f1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ml.xml SHA-256: 592a92a419b0af7a87849c9bb64bbc212b6d59ad9d0dd9637e5f5473d0c92d3c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ml_IN.xml SHA-256: 5afa83559120845a6cf52ebb0a44266ab5454f09a003ec2f096217489a527da3
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ms.xml SHA-256: 19cf0c2f2e4126d1b4bb8f0b0c876ba932f0dec0757e845ef9bf8349a7fb6d15
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ms_MY.xml SHA-256: a36c83edb679f54088e52c325295c38cb829b10a27c9ddf8335f4abc97cabd60
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nb.xml SHA-256: 2218b336e54cd0b0474d628c36a88cda121cfaf433d4c82207a4c7a2c287061f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nb_NO.xml SHA-256: 2954184cfd1e331de63a58850aae73e37d63af7efeb6f5edac8342cf2605c5de
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nl.xml SHA-256: 34f1b135e0d5a27a8059c9a4183b54fc548e2b14a8211437d9717fff719203d0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nl_NL.xml SHA-256: 83a6233d31ae4dca4a05867e89ce566bbe40dde2e07e667d4e887ce0dd53aa0c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/no.xml SHA-256: 8440d3a2c31dcd172bbb8d36a503c338b0f2afa04c2f1b2e21ae47bdb7542a19
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pl.xml SHA-256: 57ebc68f595f449b56ca2a046a3045ff86f16194a45fc0c105e8fa5cae0fc66c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pl_PL.xml SHA-256: a0eb2483f1e1b65f054072808eed0ce0c9f25577e21aa8161faa79168c4c93cc
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt.xml SHA-256: 8e8bf8174c5b9138f32f6851a337877d175ca171e1a664f758f27f5d12e68b4f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt_BR.xml SHA-256: dc9db3e696e41e91b9c90fc5d4065d38fb5b3096d11676fd2150b6a2c40e9f74
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt_PT.xml SHA-256: 53a86f2bb02e7ff9fad112880f7660964f9abeeca0c3ea8b1ccd3a1d8a244ef9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ro.xml SHA-256: 31a9355f0fffde6c862c9da547b50dcd6913d142c8dc3d71b77c848ee3439a21
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ro_RO.xml SHA-256: 281eb0a628f216f525ead57a92636bf505bfc66d3f0bba6605e210a391e2c311
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ru.xml SHA-256: a90f5d3e76d18e00ee430c369809a1e19f3a1bdf32f86abc0cb3a5f416de18fb
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ru_RU.xml SHA-256: 03937ef221731348143fc9cc073a8ce2e4dde45e5def9c0b316087b408f9abb4
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sk.xml SHA-256: 566e9e95a16afed5b9666872c27895809f35bc513deb3af367f8dcc9d27dbf5b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sk_SK.xml SHA-256: 5c7738ba9edf247ddcc522b5c8800b1b112e49fe66acae451b3e9b96b4a75791
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sl.xml SHA-256: ad6125d044801afe5c9df6e827f8b49aa4d6cad391d748667e6f2c53f02649f6
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sl_SI.xml SHA-256: 8d41882d6f779a8a6813e696d72d68a6ea294d2e48ebcf52e917766ecc755353
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sq.xml SHA-256: 47717fccd8664c6b9798dcf156dc8baf1187d229f4915b94c0c5253444e51cb0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sq_AL.xml SHA-256: 43a5c40a9767ae9748523958571b3a7b5a806ca2d25503225376df0343948138
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sr_Latn.xml SHA-256: f2176e522d003a85d8b6a9d89939def82493ab6d618134286c15a998827e8f47
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sr_Latn_RS.xml SHA-256: d39c3c5575a90c68621ec0db28412ab95f5d089d512ded0b847bd708e6e80f93
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sv.xml SHA-256: 78a0810bda53074d3f612c2a4204c9181c4535af9d6390d81192e37022275124
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sv_SE.xml SHA-256: 2252b3c79fea6e76a7cd6e340e59b814f2c186501fe8d237845a33a4f6363016
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ta.xml SHA-256: 7f37db20018f0fd3d6590be9b3cdbda1c6829a53e971a7c5e6df3d314ebb4b15
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ta_IN.xml SHA-256: 6549ea4b47693b7aef53c279a0eb44bd986e4a7e22e0d107957a9ae84a7aadb0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/te.xml SHA-256: d429759810b8f472242ca348eeabf8541da7c48c56c81bd43ec5009790efba9a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/te_IN.xml SHA-256: b2b3f615d96cab28cc30029801cfad13656f47976a9757a0868ff671514e735f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/th.xml SHA-256: 01cfee1630fc9c0cdc8196ac8632d173493694e18e2ae9e061b945ecd91809ed
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/th_TH.xml SHA-256: 9fe9e0553c204137e122a0733a210901ff6a631e739c1a3390e0ab02cc8541aa
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/tr.xml SHA-256: 97a18c0727e1e34c297b3fc08ce5d1470ef1b87558fc0e81bdee3336d0241910
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/tr_TR.xml SHA-256: 548c04f06a9c3ff5c2e6b7976836ed9438469de7eed5700455c66ec904aba304
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/uk.xml SHA-256: e1f8b87b56985273082d496cbcf783c9085af854a8c0ed28d698b48e08d7b443
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/uk_UA.xml SHA-256: 9fc882934915c86ce0ccff5f4361fe8e7423e9662d1bc3646be1eab1975a31b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/vi.xml SHA-256: 750db13b9bd918fd30216a7508ef3635a12984354454430cdaa4ce419005e66f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/vi_VN.xml SHA-256: c5ca28c5fdb79539569f65ed6143cef05470efb8e53f4c951d6ce4015f600219
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh.xml SHA-256: b1ef8bcadcf19fa8914d9ba812a7bcec124c72fecbf4acea02e4c8bd2fe51866
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hans.xml SHA-256: 138d8d3b9b646ab10d30628911ce79426ed86d308b13e988fc69f57bc16c91e2
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hans_CN.xml SHA-256: 0a531ee82fcc7e4bfcb4dd2307d9f49ed5221491d178aa71c0d08037df042d0a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hant.xml SHA-256: 3af22c10d26b47fec92cbb1aeab62e057a45caf8760860dbbe6fdb548a24bc64
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hant_TW.xml SHA-256: b4caff023dae1663820c6eb8be3728748d3552e5d9f499279ca9d9e36903d64b
// </auto-generated>
#nullable enable
using CalculatorApp.ViewModel.Common;

namespace CalculatorApp.ViewModel.DataLoaders;
internal static class CldrCurrencyDataLocaleZhTW
{
    internal static readonly IReadOnlyDictionary<string, CldrCurrencyDisplayData> Values = new Dictionary<string, CldrCurrencyDisplayData>(StringComparer.OrdinalIgnoreCase)
    {
        ["ADP"] = new("安道爾陪士特", "ADP", false),
        ["AED"] = new("阿拉伯聯合大公國迪爾汗", "AED", false),
        ["AFA"] = new("阿富汗尼 (1927–2002)", "AFA", false),
        ["AFN"] = new("阿富汗尼", "AFN", false),
        ["ALK"] = new("阿爾巴尼亞列克 (1946–1965)", "ALK", false),
        ["ALL"] = new("阿爾巴尼亞列克", "ALL", false),
        ["AMD"] = new("亞美尼亞德拉姆", "AMD", false),
        ["ANG"] = new("荷屬安地列斯盾", "ANG", false),
        ["AOA"] = new("安哥拉寬扎", "AOA", false),
        ["AOK"] = new("安哥拉寬扎 (1977–1990)", "AOK", false),
        ["AON"] = new("安哥拉新寬扎 (1990–2000)", "AON", false),
        ["AOR"] = new("安哥拉新調寬扎 (1995–1999)", "AOR", false),
        ["ARA"] = new("阿根廷奧斯特納爾", "ARA", false),
        ["ARL"] = new("阿根廷披索 (1970–1983)", "ARL", false),
        ["ARM"] = new("阿根廷披索 (1881–1970)", "ARM", false),
        ["ARP"] = new("阿根廷披索 (1983–1985)", "ARP", false),
        ["ARS"] = new("阿根廷披索", "ARS", false),
        ["ATS"] = new("奧地利先令", "ATS", false),
        ["AUD"] = new("澳幣", "AU$", true),
        ["AWG"] = new("阿路巴盾", "AWG", false),
        ["AZM"] = new("亞塞拜然馬納特 (1993–2006)", "AZM", false),
        ["AZN"] = new("亞塞拜然馬納特", "AZN", false),
        ["BAD"] = new("波士尼亞-赫塞哥維納第納爾", "BAD", false),
        ["BAM"] = new("波士尼亞-赫塞哥維納可轉換馬克", "BAM", false),
        ["BAN"] = new("波士尼亞-赫塞哥維納新第納爾", "BAN", false),
        ["BBD"] = new("巴貝多元", "BBD", false),
        ["BDT"] = new("孟加拉塔卡", "BDT", false),
        ["BEC"] = new("比利時法郎（可轉換）", "BEC", false),
        ["BEF"] = new("比利時法郎", "BEF", false),
        ["BEL"] = new("比利時法郎（金融）", "BEL", false),
        ["BGL"] = new("保加利亞硬列弗", "BGL", false),
        ["BGM"] = new("保加利亞社會黨列弗", "BGM", false),
        ["BGN"] = new("保加利亞新列弗", "BGN", false),
        ["BGO"] = new("保加利亞列弗 (1879–1952)", "BGO", false),
        ["BHD"] = new("巴林第納爾", "BHD", false),
        ["BIF"] = new("蒲隆地法郎", "BIF", false),
        ["BMD"] = new("百慕達幣", "BMD", false),
        ["BND"] = new("汶萊元", "BND", false),
        ["BOB"] = new("玻利維亞諾", "BOB", false),
        ["BOL"] = new("玻利維亞玻利維亞諾 (1863–1963)", "BOL", false),
        ["BOP"] = new("玻利維亞披索", "BOP", false),
        ["BOV"] = new("玻利維亞幕多", "BOV", false),
        ["BRB"] = new("巴西克魯薩多農瓦 (1967–1986)", "BRB", false),
        ["BRC"] = new("巴西克魯賽羅 (1986–1989)", "BRC", false),
        ["BRE"] = new("巴西克魯賽羅 (1990–1993)", "BRE", false),
        ["BRL"] = new("巴西雷亞爾", "R$", false),
        ["BRN"] = new("巴西克如爾達農瓦", "BRN", false),
        ["BRR"] = new("巴西克魯賽羅 (1993–1994)", "BRR", false),
        ["BRZ"] = new("巴西克魯賽羅 (1942 –1967)", "BRZ", false),
        ["BSD"] = new("巴哈馬元", "BSD", false),
        ["BTN"] = new("不丹那特倫", "BTN", false),
        ["BUK"] = new("緬甸基雅特", "BUK", false),
        ["BWP"] = new("波札那普拉", "BWP", false),
        ["BYB"] = new("白俄羅斯新盧布 (1994–1999)", "BYB", false),
        ["BYN"] = new("白俄羅斯盧布", "BYN", false),
        ["BYR"] = new("白俄羅斯盧布 (2000–2016)", "BYR", false),
        ["BZD"] = new("貝里斯元", "BZD", false),
        ["CAD"] = new("加幣", "CA$", false),
        ["CDF"] = new("剛果法郎", "CDF", false),
        ["CHE"] = new("歐元 (WIR)", "CHE", false),
        ["CHF"] = new("瑞士法郎", "CHF", false),
        ["CHW"] = new("法郎 (WIR)", "CHW", false),
        ["CLE"] = new("智利埃斯庫多", "CLE", false),
        ["CLF"] = new("卡林油達佛曼跎", "CLF", false),
        ["CLP"] = new("智利披索", "CLP", false),
        ["CNH"] = new("人民幣（離岸）", "CNH", false),
        ["CNY"] = new("人民幣", "CN¥", false),
        ["COP"] = new("哥倫比亞披索", "COP", false),
        ["COU"] = new("哥倫比亞幣 (COU)", "COU", false),
        ["CRC"] = new("哥斯大黎加科朗", "CRC", false),
        ["CSD"] = new("舊塞爾維亞第納爾", "CSD", false),
        ["CSK"] = new("捷克斯洛伐克硬克朗", "CSK", false),
        ["CUC"] = new("古巴可轉換披索", "CUC", false),
        ["CUP"] = new("古巴披索", "CUP", false),
        ["CVE"] = new("維德角埃斯庫多", "CVE", false),
        ["CYP"] = new("賽普勒斯鎊", "CYP", false),
        ["CZK"] = new("捷克克朗", "CZK", false),
        ["DDM"] = new("東德奧斯特馬克", "DDM", false),
        ["DEM"] = new("德國馬克", "DEM", false),
        ["DJF"] = new("吉布地法郎", "DJF", false),
        ["DKK"] = new("丹麥克朗", "DKK", false),
        ["DOP"] = new("多明尼加披索", "DOP", false),
        ["DZD"] = new("阿爾及利亞第納爾", "DZD", false),
        ["ECS"] = new("厄瓜多蘇克雷", "ECS", false),
        ["ECV"] = new("厄瓜多爾由里達瓦康斯坦 (UVC)", "ECV", false),
        ["EEK"] = new("愛沙尼亞克朗", "EEK", false),
        ["EGP"] = new("埃及鎊", "EGP", false),
        ["ERN"] = new("厄利垂亞納可法", "ERN", false),
        ["ESA"] = new("西班牙比塞塔（會計單位）", "ESA", false),
        ["ESB"] = new("西班牙比塞塔（可轉換會計單位）", "ESB", false),
        ["ESP"] = new("西班牙陪士特", "ESP", false),
        ["ETB"] = new("衣索比亞比爾", "ETB", false),
        ["EUR"] = new("歐元", "€", false),
        ["FIM"] = new("芬蘭馬克", "FIM", false),
        ["FJD"] = new("斐濟元", "FJD", false),
        ["FKP"] = new("福克蘭群島鎊", "FKP", false),
        ["FRF"] = new("法國法郎", "FRF", false),
        ["GBP"] = new("英鎊", "£", false),
        ["GEK"] = new("喬治亞庫旁拉里", "GEK", false),
        ["GEL"] = new("喬治亞拉里", "GEL", false),
        ["GHC"] = new("迦納賽地 (1979–2007)", "GHC", false),
        ["GHS"] = new("迦納塞地", "GHS", false),
        ["GIP"] = new("直布羅陀鎊", "GIP", false),
        ["GMD"] = new("甘比亞達拉西", "GMD", false),
        ["GNF"] = new("幾內亞法郎", "GNF", false),
        ["GNS"] = new("幾內亞西里", "GNS", false),
        ["GQE"] = new("赤道幾內亞埃奎勒", "GQE", false),
        ["GRD"] = new("希臘德拉克馬", "GRD", false),
        ["GTQ"] = new("瓜地馬拉格查爾", "GTQ", false),
        ["GWE"] = new("葡屬幾內亞埃斯庫多", "GWE", false),
        ["GWP"] = new("幾內亞比索披索", "GWP", false),
        ["GYD"] = new("圭亞那元", "GYD", false),
        ["HKD"] = new("港幣", "HK$", false),
        ["HNL"] = new("洪都拉斯倫皮拉", "HNL", false),
        ["HRD"] = new("克羅埃西亞第納爾", "HRD", false),
        ["HRK"] = new("克羅埃西亞庫納", "HRK", false),
        ["HTG"] = new("海地古德", "HTG", false),
        ["HUF"] = new("匈牙利福林", "HUF", false),
        ["IDR"] = new("印尼盾", "IDR", false),
        ["IEP"] = new("愛爾蘭鎊", "IEP", false),
        ["ILP"] = new("以色列鎊", "ILP", false),
        ["ILR"] = new("以色列謝克爾 (1980–1985)", "ILR", false),
        ["ILS"] = new("以色列新謝克爾", "₪", false),
        ["INR"] = new("印度盧比", "₹", false),
        ["IQD"] = new("伊拉克第納爾", "IQD", false),
        ["IRR"] = new("伊朗里亞爾", "IRR", false),
        ["ISJ"] = new("冰島克朗 (1918–1981)", "ISJ", false),
        ["ISK"] = new("冰島克朗", "ISK", false),
        ["ITL"] = new("義大利里拉", "ITL", false),
        ["JMD"] = new("牙買加元", "JMD", false),
        ["JOD"] = new("約旦第納爾", "JOD", false),
        ["JPY"] = new("日圓", "¥", true),
        ["KES"] = new("肯尼亞先令", "KES", false),
        ["KGS"] = new("吉爾吉斯索姆", "KGS", false),
        ["KHR"] = new("柬埔寨瑞爾", "KHR", false),
        ["KMF"] = new("科摩羅法郎", "KMF", false),
        ["KPW"] = new("北韓元", "KPW", false),
        ["KRH"] = new("南韓圜", "KRH", false),
        ["KRO"] = new("南韓圓", "KRO", false),
        ["KRW"] = new("韓元", "￦", true),
        ["KWD"] = new("科威特第納爾", "KWD", false),
        ["KYD"] = new("開曼群島元", "KYD", false),
        ["KZT"] = new("哈薩克堅戈", "KZT", false),
        ["LAK"] = new("寮國基普", "LAK", false),
        ["LBP"] = new("黎巴嫩鎊", "LBP", false),
        ["LKR"] = new("斯里蘭卡盧比", "LKR", false),
        ["LRD"] = new("賴比瑞亞元", "LRD", false),
        ["LSL"] = new("賴索托洛蒂", "LSL", false),
        ["LTL"] = new("立陶宛立特", "LTL", false),
        ["LTT"] = new("立陶宛特羅", "LTT", false),
        ["LUC"] = new("盧森堡可兌換法郎", "LUC", false),
        ["LUF"] = new("盧森堡法郎", "LUF", false),
        ["LUL"] = new("盧森堡金融法郎", "LUL", false),
        ["LVL"] = new("拉脫維亞拉特銀幣", "LVL", false),
        ["LVR"] = new("拉脫維亞盧布", "LVR", false),
        ["LYD"] = new("利比亞第納爾", "LYD", false),
        ["MAD"] = new("摩洛哥迪拉姆", "MAD", false),
        ["MAF"] = new("摩洛哥法郎", "MAF", false),
        ["MCF"] = new("摩納哥法郎", "MCF", false),
        ["MDC"] = new("摩爾多瓦券", "MDC", false),
        ["MDL"] = new("摩爾多瓦列伊", "MDL", false),
        ["MGA"] = new("馬達加斯加阿里亞里", "MGA", false),
        ["MGF"] = new("馬達加斯加法郎", "MGF", false),
        ["MKD"] = new("馬其頓第納爾", "MKD", false),
        ["MKN"] = new("馬其頓第納爾 (1992–1993)", "MKN", false),
        ["MLF"] = new("馬里法郎", "MLF", false),
        ["MMK"] = new("緬甸元", "MMK", false),
        ["MNT"] = new("蒙古圖格里克", "MNT", false),
        ["MOP"] = new("澳門元", "MOP", false),
        ["MRO"] = new("茅利塔尼亞烏吉亞 (1973–2017)", "MRO", false),
        ["MRU"] = new("茅利塔尼亞烏吉亞", "MRU", false),
        ["MTL"] = new("馬爾他里拉", "MTL", false),
        ["MTP"] = new("馬爾他鎊", "MTP", false),
        ["MUR"] = new("模里西斯盧比", "MUR", false),
        ["MVP"] = new("馬爾地夫盧比", "MVP", false),
        ["MVR"] = new("馬爾地夫盧非亞", "MVR", false),
        ["MWK"] = new("馬拉維克瓦查", "MWK", false),
        ["MXN"] = new("墨西哥披索", "MX$", false),
        ["MXP"] = new("墨西哥銀披索 (1861–1992)", "MXP", false),
        ["MXV"] = new("墨西哥轉換單位 (UDI)", "MXV", false),
        ["MYR"] = new("馬來西亞令吉", "MYR", false),
        ["MZE"] = new("莫三比克埃斯庫多", "MZE", false),
        ["MZM"] = new("莫三比克梅蒂卡爾 (1980–2006)", "MZM", false),
        ["MZN"] = new("莫三比克梅蒂卡爾", "MZN", false),
        ["NAD"] = new("納米比亞元", "NAD", false),
        ["NGN"] = new("奈及利亞奈拉", "NGN", false),
        ["NIC"] = new("尼加拉瓜科多巴", "NIC", false),
        ["NIO"] = new("尼加拉瓜科多巴", "NIO", false),
        ["NLG"] = new("荷蘭盾", "NLG", false),
        ["NOK"] = new("挪威克朗", "NOK", false),
        ["NPR"] = new("尼泊爾盧比", "NPR", false),
        ["NZD"] = new("紐西蘭幣", "NZ$", false),
        ["OMR"] = new("阿曼里亞爾", "OMR", false),
        ["PAB"] = new("巴拿馬巴波亞", "PAB", false),
        ["PEI"] = new("祕魯因蒂", "PEI", false),
        ["PEN"] = new("秘魯太陽幣", "PEN", false),
        ["PES"] = new("秘魯太陽幣 (1863–1965)", "PES", false),
        ["PGK"] = new("巴布亞紐幾內亞基那", "PGK", false),
        ["PHP"] = new("菲律賓披索", "PHP", true),
        ["PKR"] = new("巴基斯坦盧比", "PKR", false),
        ["PLN"] = new("波蘭茲羅提", "PLN", false),
        ["PLZ"] = new("波蘭茲羅提 (1950–1995)", "PLZ", false),
        ["PTE"] = new("葡萄牙埃斯庫多", "PTE", false),
        ["PYG"] = new("巴拉圭瓜拉尼", "PYG", false),
        ["QAR"] = new("卡達里亞爾", "QAR", false),
        ["RHD"] = new("羅德西亞元", "RHD", false),
        ["ROL"] = new("舊羅馬尼亞列伊", "ROL", false),
        ["RON"] = new("羅馬尼亞列伊", "RON", false),
        ["RSD"] = new("塞爾維亞戴納", "RSD", false),
        ["RUB"] = new("俄羅斯盧布", "RUB", false),
        ["RUR"] = new("俄羅斯盧布 (1991–1998)", "RUR", false),
        ["RWF"] = new("盧安達法郎", "RWF", false),
        ["SAR"] = new("沙烏地里亞爾", "SAR", false),
        ["SBD"] = new("索羅門群島元", "SBD", false),
        ["SCR"] = new("塞席爾盧比", "SCR", false),
        ["SDD"] = new("蘇丹第納爾", "SDD", false),
        ["SDG"] = new("蘇丹鎊", "SDG", false),
        ["SDP"] = new("舊蘇丹鎊", "SDP", false),
        ["SEK"] = new("瑞典克朗", "SEK", false),
        ["SGD"] = new("新加坡幣", "SGD", false),
        ["SHP"] = new("聖赫勒拿鎊", "SHP", false),
        ["SIT"] = new("斯洛維尼亞托勒", "SIT", false),
        ["SKK"] = new("斯洛伐克克朗", "SKK", false),
        ["SLE"] = new("獅子山利昂", "SLE", false),
        ["SLL"] = new("獅子山利昂 (1964—2022)", "SLL", false),
        ["SOS"] = new("索馬利亞先令", "SOS", false),
        ["SRD"] = new("蘇利南元", "SRD", false),
        ["SRG"] = new("蘇利南基爾", "SRG", false),
        ["SSP"] = new("南蘇丹鎊", "SSP", false),
        ["STD"] = new("聖多美島和普林西比島多布拉 (1977–2017)", "STD", false),
        ["STN"] = new("聖多美島和普林西比島多布拉", "STN", false),
        ["SUR"] = new("蘇聯盧布", "SUR", false),
        ["SVC"] = new("薩爾瓦多科郎", "SVC", false),
        ["SYP"] = new("敘利亞鎊", "SYP", false),
        ["SZL"] = new("史瓦帝尼朗吉尼", "SZL", false),
        ["THB"] = new("泰銖", "THB", false),
        ["TJR"] = new("塔吉克盧布", "TJR", false),
        ["TJS"] = new("塔吉克索莫尼", "TJS", false),
        ["TMM"] = new("土庫曼馬納特 (1993–2009)", "TMM", false),
        ["TMT"] = new("土庫曼馬納特", "TMT", false),
        ["TND"] = new("突尼西亞第納爾", "TND", false),
        ["TOP"] = new("東加潘加", "TOP", false),
        ["TPE"] = new("帝汶埃斯庫多", "TPE", false),
        ["TRL"] = new("土耳其里拉 (1922–2005)", "TRL", false),
        ["TRY"] = new("土耳其里拉", "TRY", false),
        ["TTD"] = new("千里達及托巴哥元", "TTD", false),
        ["TWD"] = new("新台幣", "$", true),
        ["TZS"] = new("坦尚尼亞先令", "TZS", false),
        ["UAH"] = new("烏克蘭格里夫納", "UAH", false),
        ["UAK"] = new("烏克蘭卡本瓦那茲", "UAK", false),
        ["UGS"] = new("烏干達先令 (1966–1987)", "UGS", false),
        ["UGX"] = new("烏干達先令", "UGX", false),
        ["USD"] = new("美元", "$", false),
        ["USN"] = new("美元（次日）", "USN", false),
        ["USS"] = new("美元（當日）", "USS", false),
        ["UYI"] = new("烏拉圭披索（指數單位）", "UYI", false),
        ["UYP"] = new("烏拉圭披索 (1975–1993)", "UYP", false),
        ["UYU"] = new("烏拉圭披索", "UYU", false),
        ["UZS"] = new("烏茲別克索姆", "UZS", false),
        ["VEB"] = new("委內瑞拉玻利瓦 (1871–2008)", "VEB", false),
        ["VEF"] = new("委內瑞拉玻利瓦 (2008–2018)", "VEF", false),
        ["VES"] = new("委內瑞拉玻利瓦", "VES", false),
        ["VND"] = new("越南盾", "₫", false),
        ["VNN"] = new("越南盾 (1978–1985)", "VNN", false),
        ["VUV"] = new("萬那杜瓦圖", "VUV", false),
        ["WST"] = new("西薩摩亞塔拉", "WST", false),
        ["XAF"] = new("中非法郎", "FCFA", false),
        ["XAG"] = new("白銀", "XAG", false),
        ["XAU"] = new("黃金", "XAU", false),
        ["XBA"] = new("歐洲綜合單位", "XBA", false),
        ["XBB"] = new("歐洲貨幣單位 (XBB)", "XBB", false),
        ["XBC"] = new("歐洲會計單位 (XBC)", "XBC", false),
        ["XBD"] = new("歐洲會計單位 (XBD)", "XBD", false),
        ["XCD"] = new("格瑞那達元", "EC$", false),
        ["XCG"] = new("加勒比盾", "XCG", false),
        ["XDR"] = new("特殊提款權", "XDR", false),
        ["XEU"] = new("歐洲貨幣單位 (XEU)", "XEU", false),
        ["XFO"] = new("法國金法郎", "XFO", false),
        ["XFU"] = new("法國法郎 (UIC)", "XFU", false),
        ["XOF"] = new("西非法郎", "F CFA", false),
        ["XPD"] = new("帕拉狄昂", "XPD", false),
        ["XPF"] = new("太平洋法郎", "CFPF", false),
        ["XPT"] = new("白金", "XPT", false),
        ["XRE"] = new("RINET 基金", "XRE", false),
        ["XSU"] = new("蘇克雷貨幣", "XSU", false),
        ["XTS"] = new("測試用貨幣代碼", "XTS", false),
        ["XUA"] = new("亞洲開發銀行計價單位", "XUA", false),
        ["XXX"] = new("未知貨幣", "XXX", true),
        ["YDD"] = new("葉門第納爾", "YDD", false),
        ["YER"] = new("葉門里亞爾", "YER", false),
        ["YUD"] = new("南斯拉夫第納爾硬幣", "YUD", false),
        ["YUM"] = new("南斯拉夫挪威亞第納爾", "YUM", false),
        ["YUN"] = new("南斯拉夫可轉換第納爾", "YUN", false),
        ["YUR"] = new("南斯拉夫改革第納爾 (1992–1993)", "YUR", false),
        ["ZAL"] = new("南非蘭特（金融）", "ZAL", false),
        ["ZAR"] = new("南非蘭特", "ZAR", false),
        ["ZMK"] = new("尚比亞克瓦查 (1968–2012)", "ZMK", false),
        ["ZMW"] = new("尚比亞克瓦查", "ZMW", false),
        ["ZRN"] = new("薩伊新扎伊爾", "ZRN", false),
        ["ZRZ"] = new("薩伊扎伊爾", "ZRZ", false),
        ["ZWD"] = new("辛巴威元 (1980–2008)", "ZWD", false),
        ["ZWG"] = new("辛巴威金", "ZWG", false),
        ["ZWL"] = new("辛巴威元 (2009)", "ZWL", false),
        ["ZWR"] = new("辛巴威元 (2008)", "ZWR", false),
    };
    internal static readonly IReadOnlyDictionary<int, CldrUnitDisplayData> Units = new Dictionary<int, CldrUnitDisplayData>
    {
        [(int)UnitConverterUnits.LengthFoot] = new(true, false),
    };
}
