// <auto-generated>
// Generated by Tools/Cldr/GenerateCurrencyData.cs. Do not edit by hand.
// Unicode CLDR 48.2 (release-48-2), Unicode License v3.
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/supplementalData.xml SHA-256: cd2af39aef82fdbfba4d591c87548203350538ad2318486d104b3b38b8d62f1a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/likelySubtags.xml SHA-256: b0049bc6420715b1e3010f43d95745dca227c5aa60357d1d89a1bdcb06287312
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/root.xml SHA-256: f69ab139130793ab721b6d1be8c1385b9a051e0b7c5893615533bcfa7bab0448
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en.xml SHA-256: 67607f4c9cf57157e70564987d8ae92a9ddcd73c00a2f1cd6abf79524a969cbd
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/af.xml SHA-256: 20b451a89365e131dea91d7d2d40e41080272b6f7c3316786da209bcff30398f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/af_ZA.xml SHA-256: 801902bcdee20e89b187a78e000ff4981820cc7fd3a8fbd3898a9c9b973e4dc1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/am.xml SHA-256: 3bc0a05c2a9d46ccee8916e0f21acf873d0d08f7c3264091b1a4f3f1b379b1a2
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/am_ET.xml SHA-256: 9c0768faa449f7b76bff9f7beee0ee8980173f643854f91cebe574e83b45160d
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ar.xml SHA-256: 94b2fea65038e61fa34b9b3efd728ab55e12c77644e61d283e63464ff57e13b7
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ar_SA.xml SHA-256: d73a53c609c4ba48079ef0d03d8a40b7da6d6c98e4d246d780ad09b8fd5c4d17
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az.xml SHA-256: 36a770b21b3a3d9eb2f93145539e446a2325feb11bd28e9a92890255a3024cce
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az_Latn.xml SHA-256: b6c1969b63c4697873232d780c90518adb9e881e842beb47b33048136f523868
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az_Latn_AZ.xml SHA-256: c859b9a884a5d0b0a1ac2ee9115fa5b5ff43f218ece53f8afb8d8ea859450d12
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/bg.xml SHA-256: 05bcf474ad3dc89fbc0216955a3a6279d1aad884e916cade8ff36a22dbca95b7
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/bg_BG.xml SHA-256: 2666dd2e18e5592c313668bf09f535bdd5fad573d51f0ce6887e20dd79fdb3ba
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ca.xml SHA-256: a9ff4dfaae2a5e3a649cbf0f636739943e3b8d25dab60cc35fd5b43a5230daae
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ca_ES.xml SHA-256: f551ca8ff440994082383f616c9c7220623699837c65ba1e635711e54de6ba01
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/cs.xml SHA-256: 151aa6e1d2e24c75e03b0332a8c41d7481fdc994c9b5b04c9e92da48142da063
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/cs_CZ.xml SHA-256: 3b4844952a606994368600b102fcd0fc9326e6d757cf94a64ccc24868e036050
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/da.xml SHA-256: b5aa90916fab9a53b85db89dd5a77ca24f6ec088e002be56493f9b11bd1a540a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/da_DK.xml SHA-256: 0cb179c3339dbe6d8c634f56be47c25a70e7ae0ef88a8c32a74bd293b4c7c2b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/de.xml SHA-256: 15dbc0a59d188b243b9bd781ae245267f700ec8cd1b1d93ed760e5dd1b3cc1c6
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/de_DE.xml SHA-256: 99f0946614cae7042b1ddfe8cc2c9dbdac4e2dae03737458b35f89e203123d12
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/el.xml SHA-256: 54726ba13bd4a441d71c63971595b96507719d977f1f37030d12d2afff90aeef
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/el_GR.xml SHA-256: aa13bf9f2da976ae559f311cf191bdd1a9fa8b0d87d44a6e34973b30cf985d98
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en_001.xml SHA-256: 193f863c209a257ceed90d112a59b43a994dde966e7c5d80c13c6477809dfc10
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en_GB.xml SHA-256: 5261b3507bf6a396ba22114d1ce5107760f5d14a1752b2689e082ef2958fe97c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es.xml SHA-256: 727d29597d9e0e4f7a1951ebb26aca2f063f89d07190c933ee56451c01334d27
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_419.xml SHA-256: 19b75df6f5c4961ef91cdb855d0f876726b6e2fc2a5b7c0c2a8c0694597f83ca
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_ES.xml SHA-256: d5111fc5c17d178837638fafe0b88573997e833972e3887fba71babe486e307c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_MX.xml SHA-256: b994e67254ce8d1435c7e8510d0481e6bebfa4d153cfe54f7125f236e971b292
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/et.xml SHA-256: f0c23e226c9fccf2f154ce5c49ccc788e3f6cb74ea2bee0669c2d79191ebcc5c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/et_EE.xml SHA-256: 7a2d20a32824022444db1f90fc1a10752892f1aeb92fd38c7fccde995ef6e3d9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/eu.xml SHA-256: 8d2775a2934e2c182b590410cde7ddf37e7307b750c2cbec11609abf97bcc44b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/eu_ES.xml SHA-256: 4318c639084c7edb46bd00bac9c289088b8b76a50ebc37b573c9d57d9f2ea146
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fa.xml SHA-256: f71b3b72c6713a4963213f2f1e7452131fa3a4f31201a6d9d6339bb3b340c8f5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fa_IR.xml SHA-256: 5a56adc9c1c28845abf2807548293d568c92364a45d4154493605c3b5d353fe9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fi.xml SHA-256: 62e1cb0f375342d128d4f0b2f2e8c014fdad3b3f891e2e476389c592fe1d5211
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fi_FI.xml SHA-256: 94802b05b89445098cf252a23f0c353c3adb3417952f1a123050b47c6a035137
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fil.xml SHA-256: 35db740e7e262d673979c2ffdbcd2aa1cd603bdc849f579bc47e272bc87304c0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fil_PH.xml SHA-256: 050ca9edbb90b7fffebdcb93b0d5afd9d1aa2debd3a5a0f8d144a15f609dbdd0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr.xml SHA-256: ebc67e303a56940609c892ededb3697e3b291466cf9622dd2c389ad48872e98f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr_CA.xml SHA-256: a97a8db94d3985e98153bccd654fcd3d561508a53dad6b643c2ff51d74743b5b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr_FR.xml SHA-256: 318de22de28f6311a2dfb2667d74487e77dc2b15c674d6b4722a08f88bb74fd0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/gl.xml SHA-256: b4bb8c58098d28595a46664dd4bb95c1bac4cc6f44854cd787bca1a45da39b7c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/gl_ES.xml SHA-256: ee882db01a31fa360cbd000b5361825d139373f9055d21ee4c451e372f295450
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/he.xml SHA-256: 7ad7f3e74991ad8f1114af6a17b282e6293a930479ff64c8198ea74786f125ac
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/he_IL.xml SHA-256: 96dea29e402000711a76fec89124cb0e640c8b7107d16aa0ff655b64994b781e
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hi.xml SHA-256: 5fa900f98f3f4ca70f73af23925783f73c62856d84892be9f364e05f4f10b261
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hi_IN.xml SHA-256: 304735ac18a0955ee910e726cab7c99c28ba090302b8a7e4d4f56850de5a522c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hr.xml SHA-256: 596312055725975849e4fe61de314a6457646a04c063daa90fe34da41e7512b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hr_HR.xml SHA-256: f2f47049eb174673601f214f77f5ebcafe319e7646ef6eae7f66b75d3dd0af5f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hu.xml SHA-256: 3bc035f25ceebbee050437f97f2021d18b6c8c818970978eb7f617e2a286eef5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hu_HU.xml SHA-256: 63c7f180d405d8fbc88f1ed7e65d3200263a6227311ef90335c41daeb946ae49
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/id.xml SHA-256: 361f434ecedb64caba5ab9be046d51540673f890a8d7b0c6a4ba8f9a960f21e5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/id_ID.xml SHA-256: 5357f507d0e2fdbca8d3701c58c86b3a96cc53567611db52d3cfb2f58a738072
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/is.xml SHA-256: 7c9ed6be258df6773db5eae302a77f134d0d674c727f29e5baee4699e418ce67
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/is_IS.xml SHA-256: 6e76fa55260447493bde0335e9efc805eff69ab3752cdaa55d06cb7db488c800
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/it.xml SHA-256: cf1e21c333efa6b61c769be824f8a410503f210f60ee157fa40ed12950dcd632
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/it_IT.xml SHA-256: 10c3b71698aefa3f2ca109728b1264ba1c1eac5e534afb1a554517813821c424
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ja.xml SHA-256: 24bc2347a4fc2d1d331f122f5f4c4f05ce435513f4f5280b16a428aad8753fdc
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ja_JP.xml SHA-256: 98e368020af382040bd1541b5cb718e6a9e6e1989bbfe9c5ca7b9180c2d32036
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kk.xml SHA-256: 6050ee58682d00307e51edcdeb3abe5daada9d3cf729917556c65b499a1a53e5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kk_KZ.xml SHA-256: 48e0343b68f35b6d381bb3b94e3df486ce91dba3552ca24da7e1561218c2335a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/km.xml SHA-256: aeae2c7371d91146ffe626ef4e038d443697055b106b48d964336428541531b8
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/km_KH.xml SHA-256: 452d6b0df9cb1e39b15380b7cd6fb35b6e88f85d30cb55298f271eb672d88ab9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kn.xml SHA-256: 913971145002f04c35fa0f8a439c11be7d761d5fc766462f8f829c2541a392af
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kn_IN.xml SHA-256: 1c049934ad5fd3f2590217dc77b808ed9e5f3da3d636e1cde2867db14c6baace
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ko.xml SHA-256: d2f0deacc2773eb4f5d9b6afc0f853a5dcd96ca1f0d26341a65c717407edde56
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ko_KR.xml SHA-256: 7d94aaf6deabbe8c1ef0f84876f4c75b53fcbeb6ae7a601ec991ff44678aa6a3
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lo.xml SHA-256: 44d5f488d09ff9c52b17d5ac717701105bdd01b3c62fcc6cefeb4f9e6277ac0a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lo_LA.xml SHA-256: cbc425642c092f8f3d9c70644ce1bc874ebeaa24451dab64143d61c9e2269245
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lt.xml SHA-256: da63b7b3e57e9a3910cb93bd736e897c0b33cf39762fd4e25bc41186c4d89911
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lt_LT.xml SHA-256: 7b5ee89b03bec5cb0cb7113451a678fcecf373d71f4852023cf74be259201ef5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lv.xml SHA-256: 9a246ca33dae57aa90cede63c3580c3690d10404f633dbf61daa6fd7dcd103d0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lv_LV.xml SHA-256: ee658897ceb7d0754ffb8d9e71b581195bd812353b5dddd5e69925ac592a2f6a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/mk.xml SHA-256: 4480bf96ff97782538a9ac40dd26cc0ff121809eeb348e84d193d9cbb6928faf
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/mk_MK.xml SHA-256: 4ea1787b13c68f2c77e87405cb419ffa9d211f7a66743fff521fb5a1977b71f1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ml.xml SHA-256: 592a92a419b0af7a87849c9bb64bbc212b6d59ad9d0dd9637e5f5473d0c92d3c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ml_IN.xml SHA-256: 5afa83559120845a6cf52ebb0a44266ab5454f09a003ec2f096217489a527da3
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ms.xml SHA-256: 19cf0c2f2e4126d1b4bb8f0b0c876ba932f0dec0757e845ef9bf8349a7fb6d15
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ms_MY.xml SHA-256: a36c83edb679f54088e52c325295c38cb829b10a27c9ddf8335f4abc97cabd60
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nb.xml SHA-256: 2218b336e54cd0b0474d628c36a88cda121cfaf433d4c82207a4c7a2c287061f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nb_NO.xml SHA-256: 2954184cfd1e331de63a58850aae73e37d63af7efeb6f5edac8342cf2605c5de
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nl.xml SHA-256: 34f1b135e0d5a27a8059c9a4183b54fc548e2b14a8211437d9717fff719203d0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nl_NL.xml SHA-256: 83a6233d31ae4dca4a05867e89ce566bbe40dde2e07e667d4e887ce0dd53aa0c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/no.xml SHA-256: 8440d3a2c31dcd172bbb8d36a503c338b0f2afa04c2f1b2e21ae47bdb7542a19
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pl.xml SHA-256: 57ebc68f595f449b56ca2a046a3045ff86f16194a45fc0c105e8fa5cae0fc66c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pl_PL.xml SHA-256: a0eb2483f1e1b65f054072808eed0ce0c9f25577e21aa8161faa79168c4c93cc
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt.xml SHA-256: 8e8bf8174c5b9138f32f6851a337877d175ca171e1a664f758f27f5d12e68b4f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt_BR.xml SHA-256: dc9db3e696e41e91b9c90fc5d4065d38fb5b3096d11676fd2150b6a2c40e9f74
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt_PT.xml SHA-256: 53a86f2bb02e7ff9fad112880f7660964f9abeeca0c3ea8b1ccd3a1d8a244ef9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ro.xml SHA-256: 31a9355f0fffde6c862c9da547b50dcd6913d142c8dc3d71b77c848ee3439a21
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ro_RO.xml SHA-256: 281eb0a628f216f525ead57a92636bf505bfc66d3f0bba6605e210a391e2c311
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ru.xml SHA-256: a90f5d3e76d18e00ee430c369809a1e19f3a1bdf32f86abc0cb3a5f416de18fb
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ru_RU.xml SHA-256: 03937ef221731348143fc9cc073a8ce2e4dde45e5def9c0b316087b408f9abb4
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sk.xml SHA-256: 566e9e95a16afed5b9666872c27895809f35bc513deb3af367f8dcc9d27dbf5b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sk_SK.xml SHA-256: 5c7738ba9edf247ddcc522b5c8800b1b112e49fe66acae451b3e9b96b4a75791
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sl.xml SHA-256: ad6125d044801afe5c9df6e827f8b49aa4d6cad391d748667e6f2c53f02649f6
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sl_SI.xml SHA-256: 8d41882d6f779a8a6813e696d72d68a6ea294d2e48ebcf52e917766ecc755353
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sq.xml SHA-256: 47717fccd8664c6b9798dcf156dc8baf1187d229f4915b94c0c5253444e51cb0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sq_AL.xml SHA-256: 43a5c40a9767ae9748523958571b3a7b5a806ca2d25503225376df0343948138
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sr_Latn.xml SHA-256: f2176e522d003a85d8b6a9d89939def82493ab6d618134286c15a998827e8f47
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sr_Latn_RS.xml SHA-256: d39c3c5575a90c68621ec0db28412ab95f5d089d512ded0b847bd708e6e80f93
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sv.xml SHA-256: 78a0810bda53074d3f612c2a4204c9181c4535af9d6390d81192e37022275124
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sv_SE.xml SHA-256: 2252b3c79fea6e76a7cd6e340e59b814f2c186501fe8d237845a33a4f6363016
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ta.xml SHA-256: 7f37db20018f0fd3d6590be9b3cdbda1c6829a53e971a7c5e6df3d314ebb4b15
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ta_IN.xml SHA-256: 6549ea4b47693b7aef53c279a0eb44bd986e4a7e22e0d107957a9ae84a7aadb0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/te.xml SHA-256: d429759810b8f472242ca348eeabf8541da7c48c56c81bd43ec5009790efba9a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/te_IN.xml SHA-256: b2b3f615d96cab28cc30029801cfad13656f47976a9757a0868ff671514e735f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/th.xml SHA-256: 01cfee1630fc9c0cdc8196ac8632d173493694e18e2ae9e061b945ecd91809ed
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/th_TH.xml SHA-256: 9fe9e0553c204137e122a0733a210901ff6a631e739c1a3390e0ab02cc8541aa
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/tr.xml SHA-256: 97a18c0727e1e34c297b3fc08ce5d1470ef1b87558fc0e81bdee3336d0241910
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/tr_TR.xml SHA-256: 548c04f06a9c3ff5c2e6b7976836ed9438469de7eed5700455c66ec904aba304
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/uk.xml SHA-256: e1f8b87b56985273082d496cbcf783c9085af854a8c0ed28d698b48e08d7b443
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/uk_UA.xml SHA-256: 9fc882934915c86ce0ccff5f4361fe8e7423e9662d1bc3646be1eab1975a31b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/vi.xml SHA-256: 750db13b9bd918fd30216a7508ef3635a12984354454430cdaa4ce419005e66f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/vi_VN.xml SHA-256: c5ca28c5fdb79539569f65ed6143cef05470efb8e53f4c951d6ce4015f600219
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh.xml SHA-256: b1ef8bcadcf19fa8914d9ba812a7bcec124c72fecbf4acea02e4c8bd2fe51866
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hans.xml SHA-256: 138d8d3b9b646ab10d30628911ce79426ed86d308b13e988fc69f57bc16c91e2
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hans_CN.xml SHA-256: 0a531ee82fcc7e4bfcb4dd2307d9f49ed5221491d178aa71c0d08037df042d0a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hant.xml SHA-256: 3af22c10d26b47fec92cbb1aeab62e057a45caf8760860dbbe6fdb548a24bc64
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hant_TW.xml SHA-256: b4caff023dae1663820c6eb8be3728748d3552e5d9f499279ca9d9e36903d64b
// </auto-generated>
#nullable enable
using CalculatorApp.ViewModel.Common;

namespace CalculatorApp.ViewModel.DataLoaders;
internal static class CldrCurrencyData
{
    internal const string Version = "48.2";
    internal const string SourceReference = "release-48-2";
    internal const string SupplementalSource = "https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/supplementalData.xml";
    internal const string LikelySubtagsSource = "https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/likelySubtags.xml";
    internal const string RootSource = "https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/root.xml";
    internal const string EnglishSource = "https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en.xml";
    internal const string LocaleSourceRoot = "https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main";
    internal const int DefaultFractionDigits = 2;
    private static readonly IReadOnlyDictionary<string, CldrCurrencyDisplayData> English = new Dictionary<string, CldrCurrencyDisplayData>(StringComparer.OrdinalIgnoreCase)
    {
        ["ADP"] = new("Andorran Peseta", "ADP", false),
        ["AED"] = new("United Arab Emirates Dirham", "AED", false),
        ["AFA"] = new("Afghan Afghani (1927–2002)", "AFA", false),
        ["AFN"] = new("Afghan Afghani", "AFN", false),
        ["ALK"] = new("Albanian Lek (1946–1965)", "ALK", false),
        ["ALL"] = new("Albanian Lek", "ALL", false),
        ["AMD"] = new("Armenian Dram", "AMD", false),
        ["ANG"] = new("Netherlands Antillean Guilder", "ANG", false),
        ["AOA"] = new("Angolan Kwanza", "AOA", false),
        ["AOK"] = new("Angolan Kwanza (1977–1991)", "AOK", false),
        ["AON"] = new("Angolan New Kwanza (1990–2000)", "AON", false),
        ["AOR"] = new("Angolan Readjusted Kwanza (1995–1999)", "AOR", false),
        ["ARA"] = new("Argentine Austral", "ARA", false),
        ["ARL"] = new("Argentine Peso Ley (1970–1983)", "ARL", false),
        ["ARM"] = new("Argentine Peso (1881–1970)", "ARM", false),
        ["ARP"] = new("Argentine Peso (1983–1985)", "ARP", false),
        ["ARS"] = new("Argentine Peso", "ARS", false),
        ["ATS"] = new("Austrian Schilling", "ATS", false),
        ["AUD"] = new("Australian Dollar", "A$", false),
        ["AWG"] = new("Aruban Florin", "AWG", false),
        ["AZM"] = new("Azerbaijani Manat (1993–2006)", "AZM", false),
        ["AZN"] = new("Azerbaijani Manat", "AZN", false),
        ["BAD"] = new("Bosnia-Herzegovina Dinar (1992–1994)", "BAD", false),
        ["BAM"] = new("Bosnia-Herzegovina Convertible Mark", "BAM", false),
        ["BAN"] = new("Bosnia-Herzegovina New Dinar (1994–1997)", "BAN", false),
        ["BBD"] = new("Barbadian Dollar", "BBD", false),
        ["BDT"] = new("Bangladeshi Taka", "BDT", false),
        ["BEC"] = new("Belgian Franc (convertible)", "BEC", false),
        ["BEF"] = new("Belgian Franc", "BEF", false),
        ["BEL"] = new("Belgian Franc (financial)", "BEL", false),
        ["BGL"] = new("Bulgarian Hard Lev", "BGL", false),
        ["BGM"] = new("Bulgarian Socialist Lev", "BGM", false),
        ["BGN"] = new("Bulgarian Lev", "BGN", false),
        ["BGO"] = new("Bulgarian Lev (1879–1952)", "BGO", false),
        ["BHD"] = new("Bahraini Dinar", "BHD", false),
        ["BIF"] = new("Burundian Franc", "BIF", false),
        ["BMD"] = new("Bermudan Dollar", "BMD", false),
        ["BND"] = new("Brunei Dollar", "BND", false),
        ["BOB"] = new("Bolivian Boliviano", "BOB", false),
        ["BOL"] = new("Bolivian Boliviano (1863–1963)", "BOL", false),
        ["BOP"] = new("Bolivian Peso", "BOP", false),
        ["BOV"] = new("Bolivian Mvdol", "BOV", false),
        ["BRB"] = new("Brazilian New Cruzeiro (1967–1986)", "BRB", false),
        ["BRC"] = new("Brazilian Cruzado (1986–1989)", "BRC", false),
        ["BRE"] = new("Brazilian Cruzeiro (1990–1993)", "BRE", false),
        ["BRL"] = new("Brazilian Real", "R$", false),
        ["BRN"] = new("Brazilian New Cruzado (1989–1990)", "BRN", false),
        ["BRR"] = new("Brazilian Cruzeiro (1993–1994)", "BRR", false),
        ["BRZ"] = new("Brazilian Cruzeiro (1942–1967)", "BRZ", false),
        ["BSD"] = new("Bahamian Dollar", "BSD", false),
        ["BTN"] = new("Bhutanese Ngultrum", "BTN", false),
        ["BUK"] = new("Burmese Kyat", "BUK", false),
        ["BWP"] = new("Botswanan Pula", "BWP", false),
        ["BYB"] = new("Belarusian Ruble (1994–1999)", "BYB", false),
        ["BYN"] = new("Belarusian Ruble", "BYN", false),
        ["BYR"] = new("Belarusian Ruble (2000–2016)", "BYR", false),
        ["BZD"] = new("Belize Dollar", "BZD", false),
        ["CAD"] = new("Canadian Dollar", "CA$", false),
        ["CDF"] = new("Congolese Franc", "CDF", false),
        ["CHE"] = new("WIR Euro", "CHE", false),
        ["CHF"] = new("Swiss Franc", "CHF", false),
        ["CHW"] = new("WIR Franc", "CHW", false),
        ["CLE"] = new("Chilean Escudo", "CLE", false),
        ["CLF"] = new("Chilean Unit of Account (UF)", "CLF", false),
        ["CLP"] = new("Chilean Peso", "CLP", false),
        ["CNH"] = new("Chinese Yuan (offshore)", "CNH", false),
        ["CNX"] = new("Chinese People’s Bank Dollar", "CNX", false),
        ["CNY"] = new("Chinese Yuan", "CN¥", false),
        ["COP"] = new("Colombian Peso", "COP", false),
        ["COU"] = new("Colombian Real Value Unit", "COU", false),
        ["CRC"] = new("Costa Rican Colón", "CRC", false),
        ["CSD"] = new("Serbian Dinar (2002–2006)", "CSD", false),
        ["CSK"] = new("Czechoslovak Hard Koruna", "CSK", false),
        ["CUC"] = new("Cuban Convertible Peso", "CUC", false),
        ["CUP"] = new("Cuban Peso", "CUP", false),
        ["CVE"] = new("Cape Verdean Escudo", "CVE", false),
        ["CYP"] = new("Cypriot Pound", "CYP", false),
        ["CZK"] = new("Czech Koruna", "CZK", false),
        ["DDM"] = new("East German Mark", "DDM", false),
        ["DEM"] = new("German Mark", "DEM", false),
        ["DJF"] = new("Djiboutian Franc", "DJF", false),
        ["DKK"] = new("Danish Krone", "DKK", false),
        ["DOP"] = new("Dominican Peso", "DOP", false),
        ["DZD"] = new("Algerian Dinar", "DZD", false),
        ["ECS"] = new("Ecuadorian Sucre", "ECS", false),
        ["ECV"] = new("Ecuadorian Unit of Constant Value", "ECV", false),
        ["EEK"] = new("Estonian Kroon", "EEK", false),
        ["EGP"] = new("Egyptian Pound", "EGP", false),
        ["ERN"] = new("Eritrean Nakfa", "ERN", false),
        ["ESA"] = new("Spanish Peseta (A account)", "ESA", false),
        ["ESB"] = new("Spanish Peseta (convertible account)", "ESB", false),
        ["ESP"] = new("Spanish Peseta", "ESP", false),
        ["ETB"] = new("Ethiopian Birr", "ETB", false),
        ["EUR"] = new("Euro", "€", false),
        ["FIM"] = new("Finnish Markka", "FIM", false),
        ["FJD"] = new("Fijian Dollar", "FJD", false),
        ["FKP"] = new("Falkland Islands Pound", "FKP", false),
        ["FRF"] = new("French Franc", "FRF", false),
        ["GBP"] = new("British Pound", "£", false),
        ["GEK"] = new("Georgian Kupon Larit", "GEK", false),
        ["GEL"] = new("Georgian Lari", "GEL", false),
        ["GHC"] = new("Ghanaian Cedi (1979–2007)", "GHC", false),
        ["GHS"] = new("Ghanaian Cedi", "GHS", false),
        ["GIP"] = new("Gibraltar Pound", "GIP", false),
        ["GMD"] = new("Gambian Dalasi", "GMD", false),
        ["GNF"] = new("Guinean Franc", "GNF", false),
        ["GNS"] = new("Guinean Syli", "GNS", false),
        ["GQE"] = new("Equatorial Guinean Ekwele", "GQE", false),
        ["GRD"] = new("Greek Drachma", "GRD", false),
        ["GTQ"] = new("Guatemalan Quetzal", "GTQ", false),
        ["GWE"] = new("Portuguese Guinea Escudo", "GWE", false),
        ["GWP"] = new("Guinea-Bissau Peso", "GWP", false),
        ["GYD"] = new("Guyanaese Dollar", "GYD", false),
        ["HKD"] = new("Hong Kong Dollar", "HK$", false),
        ["HNL"] = new("Honduran Lempira", "HNL", false),
        ["HRD"] = new("Croatian Dinar", "HRD", false),
        ["HRK"] = new("Croatian Kuna", "HRK", false),
        ["HTG"] = new("Haitian Gourde", "HTG", false),
        ["HUF"] = new("Hungarian Forint", "HUF", false),
        ["IDR"] = new("Indonesian Rupiah", "IDR", false),
        ["IEP"] = new("Irish Pound", "IEP", false),
        ["ILP"] = new("Israeli Pound", "ILP", false),
        ["ILR"] = new("Israeli Shekel (1980–1985)", "ILR", false),
        ["ILS"] = new("Israeli New Shekel", "₪", false),
        ["INR"] = new("Indian Rupee", "₹", false),
        ["IQD"] = new("Iraqi Dinar", "IQD", false),
        ["IRR"] = new("Iranian Rial", "IRR", false),
        ["ISJ"] = new("Icelandic Króna (1918–1981)", "ISJ", false),
        ["ISK"] = new("Icelandic Króna", "ISK", false),
        ["ITL"] = new("Italian Lira", "ITL", false),
        ["JMD"] = new("Jamaican Dollar", "JMD", false),
        ["JOD"] = new("Jordanian Dinar", "JOD", false),
        ["JPY"] = new("Japanese Yen", "¥", false),
        ["KES"] = new("Kenyan Shilling", "KES", false),
        ["KGS"] = new("Kyrgyz Som", "KGS", false),
        ["KHR"] = new("Cambodian Riel", "KHR", false),
        ["KMF"] = new("Comorian Franc", "KMF", false),
        ["KPW"] = new("North Korean Won", "KPW", false),
        ["KRH"] = new("South Korean Hwan (1953–1962)", "KRH", false),
        ["KRO"] = new("South Korean Won (1945–1953)", "KRO", false),
        ["KRW"] = new("South Korean Won", "₩", false),
        ["KWD"] = new("Kuwaiti Dinar", "KWD", false),
        ["KYD"] = new("Cayman Islands Dollar", "KYD", false),
        ["KZT"] = new("Kazakhstani Tenge", "KZT", false),
        ["LAK"] = new("Laotian Kip", "LAK", false),
        ["LBP"] = new("Lebanese Pound", "LBP", false),
        ["LKR"] = new("Sri Lankan Rupee", "LKR", false),
        ["LRD"] = new("Liberian Dollar", "LRD", false),
        ["LSL"] = new("Lesotho Loti", "LSL", false),
        ["LTL"] = new("Lithuanian Litas", "LTL", false),
        ["LTT"] = new("Lithuanian Talonas", "LTT", false),
        ["LUC"] = new("Luxembourgian Convertible Franc", "LUC", false),
        ["LUF"] = new("Luxembourgian Franc", "LUF", false),
        ["LUL"] = new("Luxembourg Financial Franc", "LUL", false),
        ["LVL"] = new("Latvian Lats", "LVL", false),
        ["LVR"] = new("Latvian Ruble", "LVR", false),
        ["LYD"] = new("Libyan Dinar", "LYD", false),
        ["MAD"] = new("Moroccan Dirham", "MAD", false),
        ["MAF"] = new("Moroccan Franc", "MAF", false),
        ["MCF"] = new("Monegasque Franc", "MCF", false),
        ["MDC"] = new("Moldovan Cupon", "MDC", false),
        ["MDL"] = new("Moldovan Leu", "MDL", false),
        ["MGA"] = new("Malagasy Ariary", "MGA", false),
        ["MGF"] = new("Malagasy Franc", "MGF", false),
        ["MKD"] = new("Macedonian Denar", "MKD", false),
        ["MKN"] = new("Macedonian Denar (1992–1993)", "MKN", false),
        ["MLF"] = new("Malian Franc", "MLF", false),
        ["MMK"] = new("Myanmar Kyat", "MMK", false),
        ["MNT"] = new("Mongolian Tugrik", "MNT", false),
        ["MOP"] = new("Macanese Pataca", "MOP", false),
        ["MRO"] = new("Mauritanian Ouguiya (1973–2017)", "MRO", false),
        ["MRU"] = new("Mauritanian Ouguiya", "MRU", false),
        ["MTL"] = new("Maltese Lira", "MTL", false),
        ["MTP"] = new("Maltese Pound", "MTP", false),
        ["MUR"] = new("Mauritian Rupee", "MUR", false),
        ["MVP"] = new("Maldivian Rupee (1947–1981)", "MVP", false),
        ["MVR"] = new("Maldivian Rufiyaa", "MVR", false),
        ["MWK"] = new("Malawian Kwacha", "MWK", false),
        ["MXN"] = new("Mexican Peso", "MX$", false),
        ["MXP"] = new("Mexican Silver Peso (1861–1992)", "MXP", false),
        ["MXV"] = new("Mexican Investment Unit", "MXV", false),
        ["MYR"] = new("Malaysian Ringgit", "MYR", false),
        ["MZE"] = new("Mozambican Escudo", "MZE", false),
        ["MZM"] = new("Mozambican Metical (1980–2006)", "MZM", false),
        ["MZN"] = new("Mozambican Metical", "MZN", false),
        ["NAD"] = new("Namibian Dollar", "NAD", false),
        ["NGN"] = new("Nigerian Naira", "NGN", false),
        ["NIC"] = new("Nicaraguan Córdoba (1988–1991)", "NIC", false),
        ["NIO"] = new("Nicaraguan Córdoba", "NIO", false),
        ["NLG"] = new("Dutch Guilder", "NLG", false),
        ["NOK"] = new("Norwegian Krone", "NOK", false),
        ["NPR"] = new("Nepalese Rupee", "NPR", false),
        ["NZD"] = new("New Zealand Dollar", "NZ$", false),
        ["OMR"] = new("Omani Rial", "OMR", false),
        ["PAB"] = new("Panamanian Balboa", "PAB", false),
        ["PEI"] = new("Peruvian Inti", "PEI", false),
        ["PEN"] = new("Peruvian Sol", "PEN", false),
        ["PES"] = new("Peruvian Sol (1863–1965)", "PES", false),
        ["PGK"] = new("Papua New Guinean Kina", "PGK", false),
        ["PHP"] = new("Philippine Peso", "₱", false),
        ["PKR"] = new("Pakistani Rupee", "PKR", false),
        ["PLN"] = new("Polish Zloty", "PLN", false),
        ["PLZ"] = new("Polish Zloty (1950–1995)", "PLZ", false),
        ["PTE"] = new("Portuguese Escudo", "PTE", false),
        ["PYG"] = new("Paraguayan Guarani", "PYG", false),
        ["QAR"] = new("Qatari Riyal", "QAR", false),
        ["RHD"] = new("Rhodesian Dollar", "RHD", false),
        ["ROL"] = new("Romanian Leu (1952–2006)", "ROL", false),
        ["RON"] = new("Romanian Leu", "RON", false),
        ["RSD"] = new("Serbian Dinar", "RSD", false),
        ["RUB"] = new("Russian Ruble", "RUB", false),
        ["RUR"] = new("Russian Ruble (1991–1998)", "RUR", false),
        ["RWF"] = new("Rwandan Franc", "RWF", false),
        ["SAR"] = new("Saudi Riyal", "SAR", false),
        ["SBD"] = new("Solomon Islands Dollar", "SBD", false),
        ["SCR"] = new("Seychellois Rupee", "SCR", false),
        ["SDD"] = new("Sudanese Dinar (1992–2007)", "SDD", false),
        ["SDG"] = new("Sudanese Pound", "SDG", false),
        ["SDP"] = new("Sudanese Pound (1957–1998)", "SDP", false),
        ["SEK"] = new("Swedish Krona", "SEK", false),
        ["SGD"] = new("Singapore Dollar", "SGD", false),
        ["SHP"] = new("St. Helena Pound", "SHP", false),
        ["SIT"] = new("Slovenian Tolar", "SIT", false),
        ["SKK"] = new("Slovak Koruna", "SKK", false),
        ["SLE"] = new("Sierra Leonean Leone", "SLE", false),
        ["SLL"] = new("Sierra Leonean Leone (1964—2022)", "SLL", false),
        ["SOS"] = new("Somali Shilling", "SOS", false),
        ["SRD"] = new("Surinamese Dollar", "SRD", false),
        ["SRG"] = new("Surinamese Guilder", "SRG", false),
        ["SSP"] = new("South Sudanese Pound", "SSP", false),
        ["STD"] = new("São Tomé & Príncipe Dobra (1977–2017)", "STD", false),
        ["STN"] = new("São Tomé & Príncipe Dobra", "STN", false),
        ["SUR"] = new("Soviet Rouble", "SUR", false),
        ["SVC"] = new("Salvadoran Colón", "SVC", false),
        ["SYP"] = new("Syrian Pound", "SYP", false),
        ["SZL"] = new("Swazi Lilangeni", "SZL", false),
        ["THB"] = new("Thai Baht", "THB", false),
        ["TJR"] = new("Tajikistani Ruble", "TJR", false),
        ["TJS"] = new("Tajikistani Somoni", "TJS", false),
        ["TMM"] = new("Turkmenistani Manat (1993–2009)", "TMM", false),
        ["TMT"] = new("Turkmenistani Manat", "TMT", false),
        ["TND"] = new("Tunisian Dinar", "TND", false),
        ["TOP"] = new("Tongan Paʻanga", "TOP", false),
        ["TPE"] = new("Timorese Escudo", "TPE", false),
        ["TRL"] = new("Turkish Lira (1922–2005)", "TRL", false),
        ["TRY"] = new("Turkish Lira", "TRY", false),
        ["TTD"] = new("Trinidad & Tobago Dollar", "TTD", false),
        ["TWD"] = new("New Taiwan Dollar", "NT$", false),
        ["TZS"] = new("Tanzanian Shilling", "TZS", false),
        ["UAH"] = new("Ukrainian Hryvnia", "UAH", false),
        ["UAK"] = new("Ukrainian Karbovanets", "UAK", false),
        ["UGS"] = new("Ugandan Shilling (1966–1987)", "UGS", false),
        ["UGX"] = new("Ugandan Shilling", "UGX", false),
        ["USD"] = new("US Dollar", "$", false),
        ["USN"] = new("US Dollar (Next day)", "USN", false),
        ["USS"] = new("US Dollar (Same day)", "USS", false),
        ["UYI"] = new("Uruguayan Peso (Indexed Units)", "UYI", false),
        ["UYP"] = new("Uruguayan Peso (1975–1993)", "UYP", false),
        ["UYU"] = new("Uruguayan Peso", "UYU", false),
        ["UYW"] = new("Uruguayan Nominal Wage Index Unit", "UYW", false),
        ["UZS"] = new("Uzbekistani Som", "UZS", false),
        ["VEB"] = new("Venezuelan Bolívar (1871–2008)", "VEB", false),
        ["VED"] = new("Bolívar Soberano", "VED", false),
        ["VEF"] = new("Venezuelan Bolívar (2008–2018)", "VEF", false),
        ["VES"] = new("Venezuelan Bolívar", "VES", false),
        ["VND"] = new("Vietnamese Dong", "₫", false),
        ["VNN"] = new("Vietnamese Dong (1978–1985)", "VNN", false),
        ["VUV"] = new("Vanuatu Vatu", "VUV", false),
        ["WST"] = new("Samoan Tala", "WST", false),
        ["XAF"] = new("Central African CFA Franc", "FCFA", false),
        ["XAG"] = new("Silver", "XAG", false),
        ["XAU"] = new("Gold", "XAU", false),
        ["XBA"] = new("European Composite Unit", "XBA", false),
        ["XBB"] = new("European Monetary Unit", "XBB", false),
        ["XBC"] = new("European Unit of Account (XBC)", "XBC", false),
        ["XBD"] = new("European Unit of Account (XBD)", "XBD", false),
        ["XCD"] = new("East Caribbean Dollar", "EC$", false),
        ["XCG"] = new("Caribbean guilder", "XCG", false),
        ["XDR"] = new("Special Drawing Rights", "XDR", false),
        ["XEU"] = new("European Currency Unit", "XEU", false),
        ["XFO"] = new("French Gold Franc", "XFO", false),
        ["XFU"] = new("French UIC-Franc", "XFU", false),
        ["XOF"] = new("West African CFA Franc", "F CFA", false),
        ["XPD"] = new("Palladium", "XPD", false),
        ["XPF"] = new("CFP Franc", "CFPF", false),
        ["XPT"] = new("Platinum", "XPT", false),
        ["XRE"] = new("RINET Funds", "XRE", false),
        ["XSU"] = new("Sucre", "XSU", false),
        ["XTS"] = new("Testing Currency Code", "XTS", false),
        ["XUA"] = new("ADB Unit of Account", "XUA", false),
        ["XXX"] = new("Unknown Currency", "XXX", false),
        ["YDD"] = new("Yemeni Dinar", "YDD", false),
        ["YER"] = new("Yemeni Rial", "YER", false),
        ["YUD"] = new("Yugoslavian Hard Dinar (1966–1990)", "YUD", false),
        ["YUM"] = new("Yugoslavian New Dinar (1994–2002)", "YUM", false),
        ["YUN"] = new("Yugoslavian Convertible Dinar (1990–1992)", "YUN", false),
        ["YUR"] = new("Yugoslavian Reformed Dinar (1992–1993)", "YUR", false),
        ["ZAL"] = new("South African Rand (financial)", "ZAL", false),
        ["ZAR"] = new("South African Rand", "ZAR", false),
        ["ZMK"] = new("Zambian Kwacha (1968–2012)", "ZMK", false),
        ["ZMW"] = new("Zambian Kwacha", "ZMW", false),
        ["ZRN"] = new("Zairean New Zaire (1993–1998)", "ZRN", false),
        ["ZRZ"] = new("Zairean Zaire (1971–1993)", "ZRZ", false),
        ["ZWD"] = new("Zimbabwean Dollar (1980–2008)", "ZWD", false),
        ["ZWG"] = new("Zimbabwean Gold", "ZWG", false),
        ["ZWL"] = new("Zimbabwean Dollar (2009–2024)", "ZWL", false),
        ["ZWR"] = new("Zimbabwean Dollar (2008)", "ZWR", false),
    };
    private static readonly IReadOnlyDictionary<int, CldrUnitDisplayData> EnglishUnits = new Dictionary<int, CldrUnitDisplayData>
    {
        [(int)UnitConverterUnits.AngleDegree] = new(true, true),
        [(int)UnitConverterUnits.AngleGradian] = new(true, true),
        [(int)UnitConverterUnits.AngleRadian] = new(true, true),
        [(int)UnitConverterUnits.AreaAcre] = new(true, true),
        [(int)UnitConverterUnits.AreaCastle] = new(true, true),
        [(int)UnitConverterUnits.AreaHand] = new(true, true),
        [(int)UnitConverterUnits.AreaHectare] = new(true, true),
        [(int)UnitConverterUnits.AreaPaper] = new(true, true),
        [(int)UnitConverterUnits.AreaPyeong] = new(true, true),
        [(int)UnitConverterUnits.AreaSoccerField] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareCentimeter] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareFoot] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareInch] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareKilometer] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareMeter] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareMile] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareMillimeter] = new(true, true),
        [(int)UnitConverterUnits.AreaSquareYard] = new(true, true),
        [(int)UnitConverterUnits.DataBit] = new(true, true),
        [(int)UnitConverterUnits.DataByte] = new(true, true),
        [(int)UnitConverterUnits.DataCD] = new(true, true),
        [(int)UnitConverterUnits.DataDVD] = new(true, true),
        [(int)UnitConverterUnits.DataExabits] = new(true, true),
        [(int)UnitConverterUnits.DataExabytes] = new(true, true),
        [(int)UnitConverterUnits.DataExbibits] = new(true, true),
        [(int)UnitConverterUnits.DataExbibytes] = new(true, true),
        [(int)UnitConverterUnits.DataFloppyDisk] = new(true, true),
        [(int)UnitConverterUnits.DataGibibits] = new(true, true),
        [(int)UnitConverterUnits.DataGibibytes] = new(true, true),
        [(int)UnitConverterUnits.DataGigabit] = new(true, true),
        [(int)UnitConverterUnits.DataGigabyte] = new(true, true),
        [(int)UnitConverterUnits.DataKibibits] = new(true, true),
        [(int)UnitConverterUnits.DataKibibytes] = new(true, true),
        [(int)UnitConverterUnits.DataKilobit] = new(true, true),
        [(int)UnitConverterUnits.DataKilobyte] = new(true, true),
        [(int)UnitConverterUnits.DataMebibits] = new(true, true),
        [(int)UnitConverterUnits.DataMebibytes] = new(true, true),
        [(int)UnitConverterUnits.DataMegabit] = new(true, true),
        [(int)UnitConverterUnits.DataMegabyte] = new(true, true),
        [(int)UnitConverterUnits.DataNibble] = new(true, true),
        [(int)UnitConverterUnits.DataPebibits] = new(true, true),
        [(int)UnitConverterUnits.DataPebibytes] = new(true, true),
        [(int)UnitConverterUnits.DataPetabit] = new(true, true),
        [(int)UnitConverterUnits.DataPetabyte] = new(true, true),
        [(int)UnitConverterUnits.DataTebibits] = new(true, true),
        [(int)UnitConverterUnits.DataTebibytes] = new(true, true),
        [(int)UnitConverterUnits.DataTerabit] = new(true, true),
        [(int)UnitConverterUnits.DataTerabyte] = new(true, true),
        [(int)UnitConverterUnits.DataYobibits] = new(true, true),
        [(int)UnitConverterUnits.DataYobibytes] = new(true, true),
        [(int)UnitConverterUnits.DataYottabit] = new(true, true),
        [(int)UnitConverterUnits.DataYottabyte] = new(true, true),
        [(int)UnitConverterUnits.DataZebibits] = new(true, true),
        [(int)UnitConverterUnits.DataZebibytes] = new(true, true),
        [(int)UnitConverterUnits.DataZetabits] = new(true, true),
        [(int)UnitConverterUnits.DataZetabytes] = new(true, true),
        [(int)UnitConverterUnits.EnergyBanana] = new(true, true),
        [(int)UnitConverterUnits.EnergyBattery] = new(true, true),
        [(int)UnitConverterUnits.EnergyBritishThermalUnit] = new(true, true),
        [(int)UnitConverterUnits.EnergyCalorie] = new(true, true),
        [(int)UnitConverterUnits.EnergyElectronVolt] = new(true, true),
        [(int)UnitConverterUnits.EnergyFootPound] = new(true, true),
        [(int)UnitConverterUnits.EnergyJoule] = new(true, true),
        [(int)UnitConverterUnits.EnergyKilocalorie] = new(true, true),
        [(int)UnitConverterUnits.EnergyKilojoule] = new(true, true),
        [(int)UnitConverterUnits.EnergyKilowatthour] = new(true, true),
        [(int)UnitConverterUnits.EnergySliceOfCake] = new(true, true),
        [(int)UnitConverterUnits.LengthAngstrom] = new(true, true),
        [(int)UnitConverterUnits.LengthCentimeter] = new(true, true),
        [(int)UnitConverterUnits.LengthFoot] = new(true, true),
        [(int)UnitConverterUnits.LengthHand] = new(true, true),
        [(int)UnitConverterUnits.LengthInch] = new(true, true),
        [(int)UnitConverterUnits.LengthJumboJet] = new(true, true),
        [(int)UnitConverterUnits.LengthKilometer] = new(true, true),
        [(int)UnitConverterUnits.LengthMeter] = new(true, true),
        [(int)UnitConverterUnits.LengthMicron] = new(true, true),
        [(int)UnitConverterUnits.LengthMile] = new(true, true),
        [(int)UnitConverterUnits.LengthMillimeter] = new(true, true),
        [(int)UnitConverterUnits.LengthNanometer] = new(true, true),
        [(int)UnitConverterUnits.LengthNauticalMile] = new(true, true),
        [(int)UnitConverterUnits.LengthPaperclip] = new(true, true),
        [(int)UnitConverterUnits.LengthYard] = new(true, true),
        [(int)UnitConverterUnits.PowerBritishThermalUnitPerMinute] = new(true, true),
        [(int)UnitConverterUnits.PowerFootPoundPerMinute] = new(true, true),
        [(int)UnitConverterUnits.PowerHorse] = new(true, true),
        [(int)UnitConverterUnits.PowerHorsepower] = new(true, true),
        [(int)UnitConverterUnits.PowerKilowatt] = new(true, true),
        [(int)UnitConverterUnits.PowerLightBulb] = new(true, true),
        [(int)UnitConverterUnits.PowerTrainEngine] = new(true, true),
        [(int)UnitConverterUnits.PowerWatt] = new(true, true),
        [(int)UnitConverterUnits.PressureAtmosphere] = new(true, true),
        [(int)UnitConverterUnits.PressureBar] = new(true, true),
        [(int)UnitConverterUnits.PressureKiloPascal] = new(true, true),
        [(int)UnitConverterUnits.PressureMillimeterOfMercury] = new(true, true),
        [(int)UnitConverterUnits.PressurePSI] = new(true, true),
        [(int)UnitConverterUnits.PressurePascal] = new(true, true),
        [(int)UnitConverterUnits.SpeedCentimetersPerSecond] = new(true, true),
        [(int)UnitConverterUnits.SpeedFeetPerSecond] = new(true, true),
        [(int)UnitConverterUnits.SpeedHorse] = new(true, true),
        [(int)UnitConverterUnits.SpeedJet] = new(true, true),
        [(int)UnitConverterUnits.SpeedKilometersPerHour] = new(true, true),
        [(int)UnitConverterUnits.SpeedKnot] = new(true, true),
        [(int)UnitConverterUnits.SpeedMach] = new(true, true),
        [(int)UnitConverterUnits.SpeedMetersPerSecond] = new(true, true),
        [(int)UnitConverterUnits.SpeedMilesPerHour] = new(true, true),
        [(int)UnitConverterUnits.SpeedTurtle] = new(true, true),
        [(int)UnitConverterUnits.TemperatureDegreesCelsius] = new(true, false),
        [(int)UnitConverterUnits.TemperatureDegreesFahrenheit] = new(true, false),
        [(int)UnitConverterUnits.TemperatureKelvin] = new(true, true),
        [(int)UnitConverterUnits.TimeDay] = new(true, true),
        [(int)UnitConverterUnits.TimeHour] = new(true, true),
        [(int)UnitConverterUnits.TimeMicrosecond] = new(true, true),
        [(int)UnitConverterUnits.TimeMillisecond] = new(true, true),
        [(int)UnitConverterUnits.TimeMinute] = new(true, true),
        [(int)UnitConverterUnits.TimeSecond] = new(true, true),
        [(int)UnitConverterUnits.TimeWeek] = new(true, true),
        [(int)UnitConverterUnits.TimeYear] = new(true, true),
        [(int)UnitConverterUnits.VolumeBathtub] = new(true, true),
        [(int)UnitConverterUnits.VolumeCoffeeCup] = new(true, true),
        [(int)UnitConverterUnits.VolumeCubicCentimeter] = new(true, true),
        [(int)UnitConverterUnits.VolumeCubicFoot] = new(true, true),
        [(int)UnitConverterUnits.VolumeCubicInch] = new(true, true),
        [(int)UnitConverterUnits.VolumeCubicMeter] = new(true, true),
        [(int)UnitConverterUnits.VolumeCubicYard] = new(true, true),
        [(int)UnitConverterUnits.VolumeCupUS] = new(true, true),
        [(int)UnitConverterUnits.VolumeFluidOunceUK] = new(true, true),
        [(int)UnitConverterUnits.VolumeFluidOunceUS] = new(true, true),
        [(int)UnitConverterUnits.VolumeGallonUK] = new(true, true),
        [(int)UnitConverterUnits.VolumeGallonUS] = new(true, true),
        [(int)UnitConverterUnits.VolumeLiter] = new(true, true),
        [(int)UnitConverterUnits.VolumeMilliliter] = new(true, true),
        [(int)UnitConverterUnits.VolumePintUK] = new(true, true),
        [(int)UnitConverterUnits.VolumePintUS] = new(true, true),
        [(int)UnitConverterUnits.VolumeQuartUK] = new(true, true),
        [(int)UnitConverterUnits.VolumeQuartUS] = new(true, true),
        [(int)UnitConverterUnits.VolumeSwimmingPool] = new(true, true),
        [(int)UnitConverterUnits.VolumeTablespoonUK] = new(true, true),
        [(int)UnitConverterUnits.VolumeTablespoonUS] = new(true, true),
        [(int)UnitConverterUnits.VolumeTeaspoonUK] = new(true, true),
        [(int)UnitConverterUnits.VolumeTeaspoonUS] = new(true, true),
        [(int)UnitConverterUnits.WeightCarat] = new(true, true),
        [(int)UnitConverterUnits.WeightCentigram] = new(true, true),
        [(int)UnitConverterUnits.WeightDecagram] = new(true, true),
        [(int)UnitConverterUnits.WeightDecigram] = new(true, true),
        [(int)UnitConverterUnits.WeightElephant] = new(true, true),
        [(int)UnitConverterUnits.WeightGram] = new(true, true),
        [(int)UnitConverterUnits.WeightHectogram] = new(true, true),
        [(int)UnitConverterUnits.WeightKilogram] = new(true, true),
        [(int)UnitConverterUnits.WeightLongTon] = new(true, true),
        [(int)UnitConverterUnits.WeightMilligram] = new(true, true),
        [(int)UnitConverterUnits.WeightOunce] = new(true, true),
        [(int)UnitConverterUnits.WeightPound] = new(true, true),
        [(int)UnitConverterUnits.WeightShortTon] = new(true, true),
        [(int)UnitConverterUnits.WeightSnowflake] = new(true, true),
        [(int)UnitConverterUnits.WeightSoccerBall] = new(true, true),
        [(int)UnitConverterUnits.WeightStone] = new(true, true),
        [(int)UnitConverterUnits.WeightTonne] = new(true, true),
        [(int)UnitConverterUnits.WeightWhale] = new(true, true),
    };
    private static readonly IReadOnlyDictionary<string, int> FractionDigitExceptions = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
    {
        ["ADP"] = 0,
        ["AFN"] = 0,
        ["ALL"] = 0,
        ["BHD"] = 3,
        ["BIF"] = 0,
        ["BYR"] = 0,
        ["CLF"] = 4,
        ["CLP"] = 0,
        ["COP"] = 0,
        ["DJF"] = 0,
        ["ESP"] = 0,
        ["GNF"] = 0,
        ["HUF"] = 0,
        ["IDR"] = 0,
        ["IQD"] = 0,
        ["IRR"] = 0,
        ["ISK"] = 0,
        ["ITL"] = 0,
        ["JOD"] = 3,
        ["JPY"] = 0,
        ["KMF"] = 0,
        ["KPW"] = 0,
        ["KRW"] = 0,
        ["KWD"] = 3,
        ["LAK"] = 0,
        ["LBP"] = 0,
        ["LUF"] = 0,
        ["LYD"] = 3,
        ["MGA"] = 0,
        ["MGF"] = 0,
        ["MMK"] = 0,
        ["MRO"] = 0,
        ["OMR"] = 3,
        ["PKR"] = 0,
        ["PYG"] = 0,
        ["RWF"] = 0,
        ["SLL"] = 0,
        ["SOS"] = 0,
        ["STD"] = 0,
        ["SYP"] = 0,
        ["TMM"] = 0,
        ["TND"] = 3,
        ["TRL"] = 0,
        ["UGX"] = 0,
        ["UYI"] = 0,
        ["UYW"] = 4,
        ["VND"] = 0,
        ["VUV"] = 0,
        ["XAF"] = 0,
        ["XOF"] = 0,
        ["XPF"] = 0,
        ["YER"] = 0,
        ["ZMK"] = 0,
        ["ZWD"] = 0,
    };
    internal static bool TryGet(string cultureName, string isoCode, out CldrCurrencyDisplayData display)
    {
        display = default;
        bool found = cultureName switch
        {
            "af-ZA" => CldrCurrencyDataLocaleAfZA.Values.TryGetValue(isoCode, out display),
            "am-ET" => CldrCurrencyDataLocaleAmET.Values.TryGetValue(isoCode, out display),
            "ar-SA" => CldrCurrencyDataLocaleArSA.Values.TryGetValue(isoCode, out display),
            "az-Latn-AZ" => CldrCurrencyDataLocaleAzLatnAZ.Values.TryGetValue(isoCode, out display),
            "bg-BG" => CldrCurrencyDataLocaleBgBG.Values.TryGetValue(isoCode, out display),
            "ca-ES" => CldrCurrencyDataLocaleCaES.Values.TryGetValue(isoCode, out display),
            "cs-CZ" => CldrCurrencyDataLocaleCsCZ.Values.TryGetValue(isoCode, out display),
            "da-DK" => CldrCurrencyDataLocaleDaDK.Values.TryGetValue(isoCode, out display),
            "de-DE" => CldrCurrencyDataLocaleDeDE.Values.TryGetValue(isoCode, out display),
            "el-GR" => CldrCurrencyDataLocaleElGR.Values.TryGetValue(isoCode, out display),
            "en-GB" => CldrCurrencyDataLocaleEnGB.Values.TryGetValue(isoCode, out display),
            "es-ES" => CldrCurrencyDataLocaleEsES.Values.TryGetValue(isoCode, out display),
            "es-MX" => CldrCurrencyDataLocaleEsMX.Values.TryGetValue(isoCode, out display),
            "et-EE" => CldrCurrencyDataLocaleEtEE.Values.TryGetValue(isoCode, out display),
            "eu-ES" => CldrCurrencyDataLocaleEuES.Values.TryGetValue(isoCode, out display),
            "fa-IR" => CldrCurrencyDataLocaleFaIR.Values.TryGetValue(isoCode, out display),
            "fi-FI" => CldrCurrencyDataLocaleFiFI.Values.TryGetValue(isoCode, out display),
            "fil-PH" => CldrCurrencyDataLocaleFilPH.Values.TryGetValue(isoCode, out display),
            "fr-CA" => CldrCurrencyDataLocaleFrCA.Values.TryGetValue(isoCode, out display),
            "fr-FR" => CldrCurrencyDataLocaleFrFR.Values.TryGetValue(isoCode, out display),
            "gl-ES" => CldrCurrencyDataLocaleGlES.Values.TryGetValue(isoCode, out display),
            "he-IL" => CldrCurrencyDataLocaleHeIL.Values.TryGetValue(isoCode, out display),
            "hi-IN" => CldrCurrencyDataLocaleHiIN.Values.TryGetValue(isoCode, out display),
            "hr-HR" => CldrCurrencyDataLocaleHrHR.Values.TryGetValue(isoCode, out display),
            "hu-HU" => CldrCurrencyDataLocaleHuHU.Values.TryGetValue(isoCode, out display),
            "id-ID" => CldrCurrencyDataLocaleIdID.Values.TryGetValue(isoCode, out display),
            "is-IS" => CldrCurrencyDataLocaleIsIS.Values.TryGetValue(isoCode, out display),
            "it-IT" => CldrCurrencyDataLocaleItIT.Values.TryGetValue(isoCode, out display),
            "ja-JP" => CldrCurrencyDataLocaleJaJP.Values.TryGetValue(isoCode, out display),
            "kk-KZ" => CldrCurrencyDataLocaleKkKZ.Values.TryGetValue(isoCode, out display),
            "km-KH" => CldrCurrencyDataLocaleKmKH.Values.TryGetValue(isoCode, out display),
            "kn-IN" => CldrCurrencyDataLocaleKnIN.Values.TryGetValue(isoCode, out display),
            "ko-KR" => CldrCurrencyDataLocaleKoKR.Values.TryGetValue(isoCode, out display),
            "lo-LA" => CldrCurrencyDataLocaleLoLA.Values.TryGetValue(isoCode, out display),
            "lt-LT" => CldrCurrencyDataLocaleLtLT.Values.TryGetValue(isoCode, out display),
            "lv-LV" => CldrCurrencyDataLocaleLvLV.Values.TryGetValue(isoCode, out display),
            "mk-MK" => CldrCurrencyDataLocaleMkMK.Values.TryGetValue(isoCode, out display),
            "ml-IN" => CldrCurrencyDataLocaleMlIN.Values.TryGetValue(isoCode, out display),
            "ms-MY" => CldrCurrencyDataLocaleMsMY.Values.TryGetValue(isoCode, out display),
            "nb-NO" => CldrCurrencyDataLocaleNbNO.Values.TryGetValue(isoCode, out display),
            "nl-NL" => CldrCurrencyDataLocaleNlNL.Values.TryGetValue(isoCode, out display),
            "pl-PL" => CldrCurrencyDataLocalePlPL.Values.TryGetValue(isoCode, out display),
            "pt-BR" => CldrCurrencyDataLocalePtBR.Values.TryGetValue(isoCode, out display),
            "pt-PT" => CldrCurrencyDataLocalePtPT.Values.TryGetValue(isoCode, out display),
            "ro-RO" => CldrCurrencyDataLocaleRoRO.Values.TryGetValue(isoCode, out display),
            "ru-RU" => CldrCurrencyDataLocaleRuRU.Values.TryGetValue(isoCode, out display),
            "sk-SK" => CldrCurrencyDataLocaleSkSK.Values.TryGetValue(isoCode, out display),
            "sl-SI" => CldrCurrencyDataLocaleSlSI.Values.TryGetValue(isoCode, out display),
            "sq-AL" => CldrCurrencyDataLocaleSqAL.Values.TryGetValue(isoCode, out display),
            "sr-Latn-RS" => CldrCurrencyDataLocaleSrLatnRS.Values.TryGetValue(isoCode, out display),
            "sv-SE" => CldrCurrencyDataLocaleSvSE.Values.TryGetValue(isoCode, out display),
            "ta-IN" => CldrCurrencyDataLocaleTaIN.Values.TryGetValue(isoCode, out display),
            "te-IN" => CldrCurrencyDataLocaleTeIN.Values.TryGetValue(isoCode, out display),
            "th-TH" => CldrCurrencyDataLocaleThTH.Values.TryGetValue(isoCode, out display),
            "tr-TR" => CldrCurrencyDataLocaleTrTR.Values.TryGetValue(isoCode, out display),
            "uk-UA" => CldrCurrencyDataLocaleUkUA.Values.TryGetValue(isoCode, out display),
            "vi-VN" => CldrCurrencyDataLocaleViVN.Values.TryGetValue(isoCode, out display),
            "zh-CN" => CldrCurrencyDataLocaleZhCN.Values.TryGetValue(isoCode, out display),
            "zh-TW" => CldrCurrencyDataLocaleZhTW.Values.TryGetValue(isoCode, out display),
            _ => false
        };
        return found || English.TryGetValue(isoCode, out display);
    }

    internal static CldrUnitDisplayData GetUnitDisplay(string cultureName, int unitId)
    {
        IReadOnlyDictionary<int, CldrUnitDisplayData>? localized = cultureName switch
        {
            "af-ZA" => CldrCurrencyDataLocaleAfZA.Units,
            "am-ET" => CldrCurrencyDataLocaleAmET.Units,
            "ar-SA" => CldrCurrencyDataLocaleArSA.Units,
            "az-Latn-AZ" => CldrCurrencyDataLocaleAzLatnAZ.Units,
            "bg-BG" => CldrCurrencyDataLocaleBgBG.Units,
            "ca-ES" => CldrCurrencyDataLocaleCaES.Units,
            "cs-CZ" => CldrCurrencyDataLocaleCsCZ.Units,
            "da-DK" => CldrCurrencyDataLocaleDaDK.Units,
            "de-DE" => CldrCurrencyDataLocaleDeDE.Units,
            "el-GR" => CldrCurrencyDataLocaleElGR.Units,
            "en-GB" => CldrCurrencyDataLocaleEnGB.Units,
            "es-ES" => CldrCurrencyDataLocaleEsES.Units,
            "es-MX" => CldrCurrencyDataLocaleEsMX.Units,
            "et-EE" => CldrCurrencyDataLocaleEtEE.Units,
            "eu-ES" => CldrCurrencyDataLocaleEuES.Units,
            "fa-IR" => CldrCurrencyDataLocaleFaIR.Units,
            "fi-FI" => CldrCurrencyDataLocaleFiFI.Units,
            "fil-PH" => CldrCurrencyDataLocaleFilPH.Units,
            "fr-CA" => CldrCurrencyDataLocaleFrCA.Units,
            "fr-FR" => CldrCurrencyDataLocaleFrFR.Units,
            "gl-ES" => CldrCurrencyDataLocaleGlES.Units,
            "he-IL" => CldrCurrencyDataLocaleHeIL.Units,
            "hi-IN" => CldrCurrencyDataLocaleHiIN.Units,
            "hr-HR" => CldrCurrencyDataLocaleHrHR.Units,
            "hu-HU" => CldrCurrencyDataLocaleHuHU.Units,
            "id-ID" => CldrCurrencyDataLocaleIdID.Units,
            "is-IS" => CldrCurrencyDataLocaleIsIS.Units,
            "it-IT" => CldrCurrencyDataLocaleItIT.Units,
            "ja-JP" => CldrCurrencyDataLocaleJaJP.Units,
            "kk-KZ" => CldrCurrencyDataLocaleKkKZ.Units,
            "km-KH" => CldrCurrencyDataLocaleKmKH.Units,
            "kn-IN" => CldrCurrencyDataLocaleKnIN.Units,
            "ko-KR" => CldrCurrencyDataLocaleKoKR.Units,
            "lo-LA" => CldrCurrencyDataLocaleLoLA.Units,
            "lt-LT" => CldrCurrencyDataLocaleLtLT.Units,
            "lv-LV" => CldrCurrencyDataLocaleLvLV.Units,
            "mk-MK" => CldrCurrencyDataLocaleMkMK.Units,
            "ml-IN" => CldrCurrencyDataLocaleMlIN.Units,
            "ms-MY" => CldrCurrencyDataLocaleMsMY.Units,
            "nb-NO" => CldrCurrencyDataLocaleNbNO.Units,
            "nl-NL" => CldrCurrencyDataLocaleNlNL.Units,
            "pl-PL" => CldrCurrencyDataLocalePlPL.Units,
            "pt-BR" => CldrCurrencyDataLocalePtBR.Units,
            "pt-PT" => CldrCurrencyDataLocalePtPT.Units,
            "ro-RO" => CldrCurrencyDataLocaleRoRO.Units,
            "ru-RU" => CldrCurrencyDataLocaleRuRU.Units,
            "sk-SK" => CldrCurrencyDataLocaleSkSK.Units,
            "sl-SI" => CldrCurrencyDataLocaleSlSI.Units,
            "sq-AL" => CldrCurrencyDataLocaleSqAL.Units,
            "sr-Latn-RS" => CldrCurrencyDataLocaleSrLatnRS.Units,
            "sv-SE" => CldrCurrencyDataLocaleSvSE.Units,
            "ta-IN" => CldrCurrencyDataLocaleTaIN.Units,
            "te-IN" => CldrCurrencyDataLocaleTeIN.Units,
            "th-TH" => CldrCurrencyDataLocaleThTH.Units,
            "tr-TR" => CldrCurrencyDataLocaleTrTR.Units,
            "uk-UA" => CldrCurrencyDataLocaleUkUA.Units,
            "vi-VN" => CldrCurrencyDataLocaleViVN.Units,
            "zh-CN" => CldrCurrencyDataLocaleZhCN.Units,
            "zh-TW" => CldrCurrencyDataLocaleZhTW.Units,
            _ => null
        };
        if (localized is not null && localized.TryGetValue(unitId, out CldrUnitDisplayData display))
        {
            return display;
        }

        return EnglishUnits.TryGetValue(unitId, out display) ? display : new CldrUnitDisplayData(true, true);
    }

    internal static int GetFractionDigits(string isoCode) => FractionDigitExceptions.TryGetValue(isoCode, out int digits) ? digits : DefaultFractionDigits;
}
