// <auto-generated>
// Generated by Tools/Cldr/GenerateCurrencyData.cs. Do not edit by hand.
// Unicode CLDR 48.2 (release-48-2), Unicode License v3.
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/supplementalData.xml SHA-256: cd2af39aef82fdbfba4d591c87548203350538ad2318486d104b3b38b8d62f1a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/supplemental/likelySubtags.xml SHA-256: b0049bc6420715b1e3010f43d95745dca227c5aa60357d1d89a1bdcb06287312
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/root.xml SHA-256: f69ab139130793ab721b6d1be8c1385b9a051e0b7c5893615533bcfa7bab0448
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en.xml SHA-256: 67607f4c9cf57157e70564987d8ae92a9ddcd73c00a2f1cd6abf79524a969cbd
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/af.xml SHA-256: 20b451a89365e131dea91d7d2d40e41080272b6f7c3316786da209bcff30398f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/af_ZA.xml SHA-256: 801902bcdee20e89b187a78e000ff4981820cc7fd3a8fbd3898a9c9b973e4dc1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/am.xml SHA-256: 3bc0a05c2a9d46ccee8916e0f21acf873d0d08f7c3264091b1a4f3f1b379b1a2
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/am_ET.xml SHA-256: 9c0768faa449f7b76bff9f7beee0ee8980173f643854f91cebe574e83b45160d
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ar.xml SHA-256: 94b2fea65038e61fa34b9b3efd728ab55e12c77644e61d283e63464ff57e13b7
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ar_SA.xml SHA-256: d73a53c609c4ba48079ef0d03d8a40b7da6d6c98e4d246d780ad09b8fd5c4d17
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az.xml SHA-256: 36a770b21b3a3d9eb2f93145539e446a2325feb11bd28e9a92890255a3024cce
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az_Latn.xml SHA-256: b6c1969b63c4697873232d780c90518adb9e881e842beb47b33048136f523868
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/az_Latn_AZ.xml SHA-256: c859b9a884a5d0b0a1ac2ee9115fa5b5ff43f218ece53f8afb8d8ea859450d12
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/bg.xml SHA-256: 05bcf474ad3dc89fbc0216955a3a6279d1aad884e916cade8ff36a22dbca95b7
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/bg_BG.xml SHA-256: 2666dd2e18e5592c313668bf09f535bdd5fad573d51f0ce6887e20dd79fdb3ba
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ca.xml SHA-256: a9ff4dfaae2a5e3a649cbf0f636739943e3b8d25dab60cc35fd5b43a5230daae
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ca_ES.xml SHA-256: f551ca8ff440994082383f616c9c7220623699837c65ba1e635711e54de6ba01
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/cs.xml SHA-256: 151aa6e1d2e24c75e03b0332a8c41d7481fdc994c9b5b04c9e92da48142da063
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/cs_CZ.xml SHA-256: 3b4844952a606994368600b102fcd0fc9326e6d757cf94a64ccc24868e036050
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/da.xml SHA-256: b5aa90916fab9a53b85db89dd5a77ca24f6ec088e002be56493f9b11bd1a540a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/da_DK.xml SHA-256: 0cb179c3339dbe6d8c634f56be47c25a70e7ae0ef88a8c32a74bd293b4c7c2b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/de.xml SHA-256: 15dbc0a59d188b243b9bd781ae245267f700ec8cd1b1d93ed760e5dd1b3cc1c6
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/de_DE.xml SHA-256: 99f0946614cae7042b1ddfe8cc2c9dbdac4e2dae03737458b35f89e203123d12
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/el.xml SHA-256: 54726ba13bd4a441d71c63971595b96507719d977f1f37030d12d2afff90aeef
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/el_GR.xml SHA-256: aa13bf9f2da976ae559f311cf191bdd1a9fa8b0d87d44a6e34973b30cf985d98
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en_001.xml SHA-256: 193f863c209a257ceed90d112a59b43a994dde966e7c5d80c13c6477809dfc10
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/en_GB.xml SHA-256: 5261b3507bf6a396ba22114d1ce5107760f5d14a1752b2689e082ef2958fe97c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es.xml SHA-256: 727d29597d9e0e4f7a1951ebb26aca2f063f89d07190c933ee56451c01334d27
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_419.xml SHA-256: 19b75df6f5c4961ef91cdb855d0f876726b6e2fc2a5b7c0c2a8c0694597f83ca
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_ES.xml SHA-256: d5111fc5c17d178837638fafe0b88573997e833972e3887fba71babe486e307c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/es_MX.xml SHA-256: b994e67254ce8d1435c7e8510d0481e6bebfa4d153cfe54f7125f236e971b292
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/et.xml SHA-256: f0c23e226c9fccf2f154ce5c49ccc788e3f6cb74ea2bee0669c2d79191ebcc5c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/et_EE.xml SHA-256: 7a2d20a32824022444db1f90fc1a10752892f1aeb92fd38c7fccde995ef6e3d9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/eu.xml SHA-256: 8d2775a2934e2c182b590410cde7ddf37e7307b750c2cbec11609abf97bcc44b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/eu_ES.xml SHA-256: 4318c639084c7edb46bd00bac9c289088b8b76a50ebc37b573c9d57d9f2ea146
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fa.xml SHA-256: f71b3b72c6713a4963213f2f1e7452131fa3a4f31201a6d9d6339bb3b340c8f5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fa_IR.xml SHA-256: 5a56adc9c1c28845abf2807548293d568c92364a45d4154493605c3b5d353fe9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fi.xml SHA-256: 62e1cb0f375342d128d4f0b2f2e8c014fdad3b3f891e2e476389c592fe1d5211
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fi_FI.xml SHA-256: 94802b05b89445098cf252a23f0c353c3adb3417952f1a123050b47c6a035137
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fil.xml SHA-256: 35db740e7e262d673979c2ffdbcd2aa1cd603bdc849f579bc47e272bc87304c0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fil_PH.xml SHA-256: 050ca9edbb90b7fffebdcb93b0d5afd9d1aa2debd3a5a0f8d144a15f609dbdd0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr.xml SHA-256: ebc67e303a56940609c892ededb3697e3b291466cf9622dd2c389ad48872e98f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr_CA.xml SHA-256: a97a8db94d3985e98153bccd654fcd3d561508a53dad6b643c2ff51d74743b5b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/fr_FR.xml SHA-256: 318de22de28f6311a2dfb2667d74487e77dc2b15c674d6b4722a08f88bb74fd0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/gl.xml SHA-256: b4bb8c58098d28595a46664dd4bb95c1bac4cc6f44854cd787bca1a45da39b7c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/gl_ES.xml SHA-256: ee882db01a31fa360cbd000b5361825d139373f9055d21ee4c451e372f295450
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/he.xml SHA-256: 7ad7f3e74991ad8f1114af6a17b282e6293a930479ff64c8198ea74786f125ac
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/he_IL.xml SHA-256: 96dea29e402000711a76fec89124cb0e640c8b7107d16aa0ff655b64994b781e
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hi.xml SHA-256: 5fa900f98f3f4ca70f73af23925783f73c62856d84892be9f364e05f4f10b261
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hi_IN.xml SHA-256: 304735ac18a0955ee910e726cab7c99c28ba090302b8a7e4d4f56850de5a522c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hr.xml SHA-256: 596312055725975849e4fe61de314a6457646a04c063daa90fe34da41e7512b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hr_HR.xml SHA-256: f2f47049eb174673601f214f77f5ebcafe319e7646ef6eae7f66b75d3dd0af5f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hu.xml SHA-256: 3bc035f25ceebbee050437f97f2021d18b6c8c818970978eb7f617e2a286eef5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/hu_HU.xml SHA-256: 63c7f180d405d8fbc88f1ed7e65d3200263a6227311ef90335c41daeb946ae49
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/id.xml SHA-256: 361f434ecedb64caba5ab9be046d51540673f890a8d7b0c6a4ba8f9a960f21e5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/id_ID.xml SHA-256: 5357f507d0e2fdbca8d3701c58c86b3a96cc53567611db52d3cfb2f58a738072
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/is.xml SHA-256: 7c9ed6be258df6773db5eae302a77f134d0d674c727f29e5baee4699e418ce67
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/is_IS.xml SHA-256: 6e76fa55260447493bde0335e9efc805eff69ab3752cdaa55d06cb7db488c800
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/it.xml SHA-256: cf1e21c333efa6b61c769be824f8a410503f210f60ee157fa40ed12950dcd632
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/it_IT.xml SHA-256: 10c3b71698aefa3f2ca109728b1264ba1c1eac5e534afb1a554517813821c424
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ja.xml SHA-256: 24bc2347a4fc2d1d331f122f5f4c4f05ce435513f4f5280b16a428aad8753fdc
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ja_JP.xml SHA-256: 98e368020af382040bd1541b5cb718e6a9e6e1989bbfe9c5ca7b9180c2d32036
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kk.xml SHA-256: 6050ee58682d00307e51edcdeb3abe5daada9d3cf729917556c65b499a1a53e5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kk_KZ.xml SHA-256: 48e0343b68f35b6d381bb3b94e3df486ce91dba3552ca24da7e1561218c2335a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/km.xml SHA-256: aeae2c7371d91146ffe626ef4e038d443697055b106b48d964336428541531b8
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/km_KH.xml SHA-256: 452d6b0df9cb1e39b15380b7cd6fb35b6e88f85d30cb55298f271eb672d88ab9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kn.xml SHA-256: 913971145002f04c35fa0f8a439c11be7d761d5fc766462f8f829c2541a392af
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/kn_IN.xml SHA-256: 1c049934ad5fd3f2590217dc77b808ed9e5f3da3d636e1cde2867db14c6baace
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ko.xml SHA-256: d2f0deacc2773eb4f5d9b6afc0f853a5dcd96ca1f0d26341a65c717407edde56
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ko_KR.xml SHA-256: 7d94aaf6deabbe8c1ef0f84876f4c75b53fcbeb6ae7a601ec991ff44678aa6a3
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lo.xml SHA-256: 44d5f488d09ff9c52b17d5ac717701105bdd01b3c62fcc6cefeb4f9e6277ac0a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lo_LA.xml SHA-256: cbc425642c092f8f3d9c70644ce1bc874ebeaa24451dab64143d61c9e2269245
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lt.xml SHA-256: da63b7b3e57e9a3910cb93bd736e897c0b33cf39762fd4e25bc41186c4d89911
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lt_LT.xml SHA-256: 7b5ee89b03bec5cb0cb7113451a678fcecf373d71f4852023cf74be259201ef5
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lv.xml SHA-256: 9a246ca33dae57aa90cede63c3580c3690d10404f633dbf61daa6fd7dcd103d0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/lv_LV.xml SHA-256: ee658897ceb7d0754ffb8d9e71b581195bd812353b5dddd5e69925ac592a2f6a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/mk.xml SHA-256: 4480bf96ff97782538a9ac40dd26cc0ff121809eeb348e84d193d9cbb6928faf
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/mk_MK.xml SHA-256: 4ea1787b13c68f2c77e87405cb419ffa9d211f7a66743fff521fb5a1977b71f1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ml.xml SHA-256: 592a92a419b0af7a87849c9bb64bbc212b6d59ad9d0dd9637e5f5473d0c92d3c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ml_IN.xml SHA-256: 5afa83559120845a6cf52ebb0a44266ab5454f09a003ec2f096217489a527da3
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ms.xml SHA-256: 19cf0c2f2e4126d1b4bb8f0b0c876ba932f0dec0757e845ef9bf8349a7fb6d15
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ms_MY.xml SHA-256: a36c83edb679f54088e52c325295c38cb829b10a27c9ddf8335f4abc97cabd60
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nb.xml SHA-256: 2218b336e54cd0b0474d628c36a88cda121cfaf433d4c82207a4c7a2c287061f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nb_NO.xml SHA-256: 2954184cfd1e331de63a58850aae73e37d63af7efeb6f5edac8342cf2605c5de
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nl.xml SHA-256: 34f1b135e0d5a27a8059c9a4183b54fc548e2b14a8211437d9717fff719203d0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/nl_NL.xml SHA-256: 83a6233d31ae4dca4a05867e89ce566bbe40dde2e07e667d4e887ce0dd53aa0c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/no.xml SHA-256: 8440d3a2c31dcd172bbb8d36a503c338b0f2afa04c2f1b2e21ae47bdb7542a19
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pl.xml SHA-256: 57ebc68f595f449b56ca2a046a3045ff86f16194a45fc0c105e8fa5cae0fc66c
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pl_PL.xml SHA-256: a0eb2483f1e1b65f054072808eed0ce0c9f25577e21aa8161faa79168c4c93cc
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt.xml SHA-256: 8e8bf8174c5b9138f32f6851a337877d175ca171e1a664f758f27f5d12e68b4f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt_BR.xml SHA-256: dc9db3e696e41e91b9c90fc5d4065d38fb5b3096d11676fd2150b6a2c40e9f74
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/pt_PT.xml SHA-256: 53a86f2bb02e7ff9fad112880f7660964f9abeeca0c3ea8b1ccd3a1d8a244ef9
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ro.xml SHA-256: 31a9355f0fffde6c862c9da547b50dcd6913d142c8dc3d71b77c848ee3439a21
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ro_RO.xml SHA-256: 281eb0a628f216f525ead57a92636bf505bfc66d3f0bba6605e210a391e2c311
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ru.xml SHA-256: a90f5d3e76d18e00ee430c369809a1e19f3a1bdf32f86abc0cb3a5f416de18fb
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ru_RU.xml SHA-256: 03937ef221731348143fc9cc073a8ce2e4dde45e5def9c0b316087b408f9abb4
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sk.xml SHA-256: 566e9e95a16afed5b9666872c27895809f35bc513deb3af367f8dcc9d27dbf5b
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sk_SK.xml SHA-256: 5c7738ba9edf247ddcc522b5c8800b1b112e49fe66acae451b3e9b96b4a75791
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sl.xml SHA-256: ad6125d044801afe5c9df6e827f8b49aa4d6cad391d748667e6f2c53f02649f6
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sl_SI.xml SHA-256: 8d41882d6f779a8a6813e696d72d68a6ea294d2e48ebcf52e917766ecc755353
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sq.xml SHA-256: 47717fccd8664c6b9798dcf156dc8baf1187d229f4915b94c0c5253444e51cb0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sq_AL.xml SHA-256: 43a5c40a9767ae9748523958571b3a7b5a806ca2d25503225376df0343948138
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sr_Latn.xml SHA-256: f2176e522d003a85d8b6a9d89939def82493ab6d618134286c15a998827e8f47
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sr_Latn_RS.xml SHA-256: d39c3c5575a90c68621ec0db28412ab95f5d089d512ded0b847bd708e6e80f93
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sv.xml SHA-256: 78a0810bda53074d3f612c2a4204c9181c4535af9d6390d81192e37022275124
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/sv_SE.xml SHA-256: 2252b3c79fea6e76a7cd6e340e59b814f2c186501fe8d237845a33a4f6363016
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ta.xml SHA-256: 7f37db20018f0fd3d6590be9b3cdbda1c6829a53e971a7c5e6df3d314ebb4b15
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/ta_IN.xml SHA-256: 6549ea4b47693b7aef53c279a0eb44bd986e4a7e22e0d107957a9ae84a7aadb0
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/te.xml SHA-256: d429759810b8f472242ca348eeabf8541da7c48c56c81bd43ec5009790efba9a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/te_IN.xml SHA-256: b2b3f615d96cab28cc30029801cfad13656f47976a9757a0868ff671514e735f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/th.xml SHA-256: 01cfee1630fc9c0cdc8196ac8632d173493694e18e2ae9e061b945ecd91809ed
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/th_TH.xml SHA-256: 9fe9e0553c204137e122a0733a210901ff6a631e739c1a3390e0ab02cc8541aa
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/tr.xml SHA-256: 97a18c0727e1e34c297b3fc08ce5d1470ef1b87558fc0e81bdee3336d0241910
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/tr_TR.xml SHA-256: 548c04f06a9c3ff5c2e6b7976836ed9438469de7eed5700455c66ec904aba304
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/uk.xml SHA-256: e1f8b87b56985273082d496cbcf783c9085af854a8c0ed28d698b48e08d7b443
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/uk_UA.xml SHA-256: 9fc882934915c86ce0ccff5f4361fe8e7423e9662d1bc3646be1eab1975a31b1
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/vi.xml SHA-256: 750db13b9bd918fd30216a7508ef3635a12984354454430cdaa4ce419005e66f
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/vi_VN.xml SHA-256: c5ca28c5fdb79539569f65ed6143cef05470efb8e53f4c951d6ce4015f600219
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh.xml SHA-256: b1ef8bcadcf19fa8914d9ba812a7bcec124c72fecbf4acea02e4c8bd2fe51866
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hans.xml SHA-256: 138d8d3b9b646ab10d30628911ce79426ed86d308b13e988fc69f57bc16c91e2
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hans_CN.xml SHA-256: 0a531ee82fcc7e4bfcb4dd2307d9f49ed5221491d178aa71c0d08037df042d0a
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hant.xml SHA-256: 3af22c10d26b47fec92cbb1aeab62e057a45caf8760860dbbe6fdb548a24bc64
// https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/main/zh_Hant_TW.xml SHA-256: b4caff023dae1663820c6eb8be3728748d3552e5d9f499279ca9d9e36903d64b
// </auto-generated>
#nullable enable
using CalculatorApp.ViewModel.Common;

namespace CalculatorApp.ViewModel.DataLoaders;
internal static class CldrCurrencyDataLocaleKoKR
{
    internal static readonly IReadOnlyDictionary<string, CldrCurrencyDisplayData> Values = new Dictionary<string, CldrCurrencyDisplayData>(StringComparer.OrdinalIgnoreCase)
    {
        ["ADP"] = new("안도라 페세타", "ADP", false),
        ["AED"] = new("아랍에미리트 디르함", "AED", false),
        ["AFA"] = new("아프가니 (1927–2002)", "AFA", false),
        ["AFN"] = new("아프가니스탄 아프가니", "AFN", false),
        ["ALL"] = new("알바니아 레크", "ALL", false),
        ["AMD"] = new("아르메니아 드람", "AMD", false),
        ["ANG"] = new("네덜란드령 안틸레스 길더", "ANG", false),
        ["AOA"] = new("앙골라 콴자", "AOA", false),
        ["AOK"] = new("앙골라 콴자 (1977–1990)", "AOK", false),
        ["AON"] = new("앙골라 신콴자 (1990–2000)", "AON", false),
        ["AOR"] = new("앙골라 재조정 콴자 (1995–1999)", "AOR", false),
        ["ARA"] = new("아르헨티나 오스트랄", "ARA", false),
        ["ARL"] = new("아르헨티나 페소 레이 (1970–1983)", "ARL", false),
        ["ARM"] = new("아르헨티나 페소 (18810–1970)", "ARM", false),
        ["ARP"] = new("아르헨티나 페소 (1983–1985)", "ARP", false),
        ["ARS"] = new("아르헨티나 페소", "ARS", false),
        ["ATS"] = new("호주 실링", "ATS", false),
        ["AUD"] = new("호주 달러", "AU$", true),
        ["AWG"] = new("아루바 플로린", "AWG", false),
        ["AZM"] = new("아제르바이젠 마나트(1993–2006)", "AZM", false),
        ["AZN"] = new("아제르바이잔 마나트", "AZN", false),
        ["BAD"] = new("보스니아-헤르체고비나 디나르", "BAD", false),
        ["BAM"] = new("보스니아-헤르체고비나 태환 마르크", "BAM", false),
        ["BAN"] = new("보스니아-헤르체고비나 신디나르 (1994–1997)", "BAN", false),
        ["BBD"] = new("바베이도스 달러", "BBD", false),
        ["BDT"] = new("방글라데시 타카", "BDT", false),
        ["BEC"] = new("벨기에 프랑 (태환)", "BEC", false),
        ["BEF"] = new("벨기에 프랑", "BEF", false),
        ["BEL"] = new("벨기에 프랑 (금융)", "BEL", false),
        ["BGL"] = new("불가리아 동전 렛", "BGL", false),
        ["BGM"] = new("불가리아 사회주의자 렛", "BGM", false),
        ["BGN"] = new("불가리아 레프", "BGN", false),
        ["BGO"] = new("불가리아 렛 (1879–1952)", "BGO", false),
        ["BHD"] = new("바레인 디나르", "BHD", false),
        ["BIF"] = new("부룬디 프랑", "BIF", false),
        ["BMD"] = new("버뮤다 달러", "BMD", false),
        ["BND"] = new("부루나이 달러", "BND", false),
        ["BOB"] = new("볼리비아 볼리비아노", "BOB", false),
        ["BOL"] = new("볼리비아 볼리비아노 (1863–1963)", "BOL", false),
        ["BOP"] = new("볼리비아노 페소", "BOP", false),
        ["BOV"] = new("볼리비아노 Mvdol(기금)", "BOV", false),
        ["BRB"] = new("볼리비아노 크루제이루 노보 (1967–1986)", "BRB", false),
        ["BRC"] = new("브라질 크루자두", "BRC", false),
        ["BRE"] = new("브라질 크루제이루 (1990–1993)", "BRE", false),
        ["BRL"] = new("브라질 레알", "R$", false),
        ["BRN"] = new("브라질 크루자두 노보", "BRN", false),
        ["BRR"] = new("브라질 크루제이루", "BRR", false),
        ["BRZ"] = new("브라질 크루제이루 (1942–1967)", "BRZ", false),
        ["BSD"] = new("바하마 달러", "BSD", false),
        ["BTN"] = new("부탄 눌투눔", "BTN", false),
        ["BUK"] = new("버마 차트", "BUK", false),
        ["BWP"] = new("보츠와나 풀라", "BWP", false),
        ["BYB"] = new("벨라루스 신권 루블 (1994–1999)", "BYB", false),
        ["BYN"] = new("벨라루스 루블", "BYN", false),
        ["BYR"] = new("벨라루스 루블 (2000–2016)", "BYR", false),
        ["BZD"] = new("벨리즈 달러", "BZD", false),
        ["CAD"] = new("캐나다 달러", "CA$", false),
        ["CDF"] = new("콩고 프랑", "CDF", false),
        ["CHE"] = new("유로 (WIR)", "CHE", false),
        ["CHF"] = new("스위스 프랑", "CHF", false),
        ["CHW"] = new("프랑 (WIR)", "CHW", false),
        ["CLE"] = new("칠레 에스쿠도", "CLE", false),
        ["CLF"] = new("칠레 (UF)", "CLF", false),
        ["CLP"] = new("칠레 페소", "CLP", false),
        ["CNH"] = new("중국 위안화(역외)", "CNH", false),
        ["CNY"] = new("중국 위안화", "CN¥", false),
        ["COP"] = new("콜롬비아 페소", "COP", false),
        ["COU"] = new("콜롬비아 실가 단위", "COU", false),
        ["CRC"] = new("코스타리카 콜론", "CRC", false),
        ["CSD"] = new("고 세르비아 디나르", "CSD", false),
        ["CSK"] = new("체코슬로바키아 동전 코루나", "CSK", false),
        ["CUC"] = new("쿠바 태환 페소", "CUC", false),
        ["CUP"] = new("쿠바 페소", "CUP", false),
        ["CVE"] = new("카보베르데 에스쿠도", "CVE", false),
        ["CYP"] = new("싸이프러스 파운드", "CYP", false),
        ["CZK"] = new("체코 코루나", "CZK", false),
        ["DDM"] = new("동독 오스트마르크", "DDM", false),
        ["DEM"] = new("독일 마르크", "DEM", false),
        ["DJF"] = new("지부티 프랑", "DJF", false),
        ["DKK"] = new("덴마크 크로네", "DKK", false),
        ["DOP"] = new("도미니카 페소", "DOP", false),
        ["DZD"] = new("알제리 디나르", "DZD", false),
        ["ECS"] = new("에쿠아도르 수크레", "ECS", false),
        ["ECV"] = new("에콰도르 (UVC)", "ECV", false),
        ["EEK"] = new("에스토니아 크룬", "EEK", false),
        ["EGP"] = new("이집트 파운드", "EGP", false),
        ["ERN"] = new("에리트레아 낙파", "ERN", false),
        ["ESA"] = new("스페인 페세타(예금)", "ESA", false),
        ["ESB"] = new("스페인 페세타(변환 예금)", "ESB", false),
        ["ESP"] = new("스페인 페세타", "ESP", false),
        ["ETB"] = new("에티오피아 비르", "ETB", false),
        ["EUR"] = new("유로", "€", false),
        ["FIM"] = new("핀란드 마르카", "FIM", false),
        ["FJD"] = new("피지 달러", "FJD", false),
        ["FKP"] = new("포클랜드제도 파운드", "FKP", false),
        ["FRF"] = new("프랑스 프랑", "FRF", false),
        ["GBP"] = new("영국 파운드", "£", false),
        ["GEK"] = new("그루지야 지폐 라리트", "GEK", false),
        ["GEL"] = new("조지아 라리", "GEL", false),
        ["GHC"] = new("가나 시디 (1979–2007)", "GHC", false),
        ["GHS"] = new("가나 세디", "GHS", false),
        ["GIP"] = new("지브롤터 파운드", "GIP", false),
        ["GMD"] = new("감비아 달라시", "GMD", false),
        ["GNF"] = new("기니 프랑", "GNF", false),
        ["GNS"] = new("기니 시리", "GNS", false),
        ["GQE"] = new("적도 기니 에쿨 (Ekwele)", "GQE", false),
        ["GRD"] = new("그리스 드라크마", "GRD", false),
        ["GTQ"] = new("과테말라 케트살", "GTQ", false),
        ["GWE"] = new("포르투갈령 기니 에스쿠도", "GWE", false),
        ["GWP"] = new("기네비쏘 페소", "GWP", false),
        ["GYD"] = new("가이아나 달러", "GYD", false),
        ["HKD"] = new("홍콩 달러", "HK$", false),
        ["HNL"] = new("온두라스 렘피라", "HNL", false),
        ["HRD"] = new("크로아티아 디나르", "HRD", false),
        ["HRK"] = new("크로아티아 쿠나", "HRK", false),
        ["HTG"] = new("아이티 구르드", "HTG", false),
        ["HUF"] = new("헝가리 포린트", "HUF", false),
        ["IDR"] = new("인도네시아 루피아", "IDR", false),
        ["IEP"] = new("아일랜드 파운드", "IEP", false),
        ["ILP"] = new("이스라엘 파운드", "ILP", false),
        ["ILS"] = new("이스라엘 신권 세켈", "₪", false),
        ["INR"] = new("인도 루피", "₹", false),
        ["IQD"] = new("이라크 디나르", "IQD", false),
        ["IRR"] = new("이란 리얄", "IRR", false),
        ["ISK"] = new("아이슬란드 크로나", "ISK", false),
        ["ITL"] = new("이탈리아 리라", "ITL", false),
        ["JMD"] = new("자메이카 달러", "JMD", false),
        ["JOD"] = new("요르단 디나르", "JOD", false),
        ["JPY"] = new("일본 엔화", "¥", false),
        ["KES"] = new("케냐 실링", "KES", false),
        ["KGS"] = new("키르기스스탄 솜", "KGS", false),
        ["KHR"] = new("캄보디아 리엘", "KHR", false),
        ["KMF"] = new("코모르 프랑", "KMF", false),
        ["KPW"] = new("조선 민주주의 인민 공화국 원", "KPW", false),
        ["KRH"] = new("대한민국 환 (1953–1962)", "KRH", false),
        ["KRW"] = new("대한민국 원", "₩", false),
        ["KWD"] = new("쿠웨이트 디나르", "KWD", false),
        ["KYD"] = new("케이맨 제도 달러", "KYD", false),
        ["KZT"] = new("카자흐스탄 텡게", "KZT", false),
        ["LAK"] = new("라오스 키프", "LAK", false),
        ["LBP"] = new("레바논 파운드", "LBP", false),
        ["LKR"] = new("스리랑카 루피", "LKR", false),
        ["LRD"] = new("라이베리아 달러", "LRD", false),
        ["LSL"] = new("레소토 로티", "LSL", false),
        ["LTL"] = new("리투아니아 리타", "LTL", false),
        ["LTT"] = new("룩셈부르크 타로나", "LTT", false),
        ["LUC"] = new("룩셈부르크 변환 프랑", "LUC", false),
        ["LUF"] = new("룩셈부르크 프랑", "LUF", false),
        ["LUL"] = new("룩셈부르크 재정 프랑", "LUL", false),
        ["LVL"] = new("라트비아 라트", "LVL", false),
        ["LVR"] = new("라트비아 루블", "LVR", false),
        ["LYD"] = new("리비아 디나르", "LYD", false),
        ["MAD"] = new("모로코 디르함", "MAD", false),
        ["MAF"] = new("모로코 프랑", "MAF", false),
        ["MCF"] = new("모나코 프랑", "MCF", false),
        ["MDC"] = new("몰도바 쿠폰", "MDC", false),
        ["MDL"] = new("몰도바 레이", "MDL", false),
        ["MGA"] = new("마다가스카르 아리아리", "MGA", false),
        ["MGF"] = new("마다가스카르 프랑", "MGF", false),
        ["MKD"] = new("마케도니아 디나르", "MKD", false),
        ["MLF"] = new("말리 프랑", "MLF", false),
        ["MMK"] = new("미얀마 키얏", "MMK", false),
        ["MNT"] = new("몽골 투그릭", "MNT", false),
        ["MOP"] = new("마카오 파타카", "MOP", false),
        ["MRO"] = new("모리타니 우기야 (1973–2017)", "MRO", false),
        ["MRU"] = new("모리타니 우기야", "MRU", false),
        ["MTL"] = new("몰타 리라", "MTL", false),
        ["MTP"] = new("몰타 파운드", "MTP", false),
        ["MUR"] = new("모리셔스 루피", "MUR", false),
        ["MVR"] = new("몰디브 제도 루피아", "MVR", false),
        ["MWK"] = new("말라위 콰차", "MWK", false),
        ["MXN"] = new("멕시코 페소", "MX$", false),
        ["MXP"] = new("멕시코 실버 페소 (1861–1992)", "MXP", false),
        ["MXV"] = new("멕시코 (UDI)", "MXV", false),
        ["MYR"] = new("말레이시아 링깃", "MYR", false),
        ["MZE"] = new("모잠비크 에스쿠도", "MZE", false),
        ["MZM"] = new("고 모잠비크 메티칼", "MZM", false),
        ["MZN"] = new("모잠비크 메티칼", "MZN", false),
        ["NAD"] = new("나미비아 달러", "NAD", false),
        ["NGN"] = new("나이지리아 나이라", "NGN", false),
        ["NIC"] = new("니카라과 코르도바(1988~1991)", "NIC", false),
        ["NIO"] = new("니카라과 코르도바", "NIO", false),
        ["NLG"] = new("네델란드 길더", "NLG", false),
        ["NOK"] = new("노르웨이 크로네", "NOK", false),
        ["NPR"] = new("네팔 루피", "NPR", false),
        ["NZD"] = new("뉴질랜드 달러", "NZ$", false),
        ["OMR"] = new("오만 리알", "OMR", false),
        ["PAB"] = new("파나마 발보아", "PAB", false),
        ["PEI"] = new("페루 인티", "PEI", false),
        ["PEN"] = new("페루 솔", "PEN", false),
        ["PES"] = new("페루 솔 (1863–1965)", "PES", false),
        ["PGK"] = new("파푸아뉴기니 키나", "PGK", false),
        ["PHP"] = new("필리핀 페소", "PHP", true),
        ["PKR"] = new("파키스탄 루피", "PKR", false),
        ["PLN"] = new("폴란드 즈워티", "PLN", false),
        ["PLZ"] = new("폴란드 즐로티 (1950–1995)", "PLZ", false),
        ["PTE"] = new("포르투갈 에스쿠도", "PTE", false),
        ["PYG"] = new("파라과이 과라니", "PYG", false),
        ["QAR"] = new("카타르 리얄", "QAR", false),
        ["RHD"] = new("로디지아 달러", "RHD", false),
        ["ROL"] = new("루마니아 레이", "ROL", false),
        ["RON"] = new("루마니아 레우", "RON", false),
        ["RSD"] = new("세르비아 디나르", "RSD", false),
        ["RUB"] = new("러시아 루블", "RUB", false),
        ["RUR"] = new("러시아 루블 (1991–1998)", "RUR", false),
        ["RWF"] = new("르완다 프랑", "RWF", false),
        ["SAR"] = new("사우디아라비아 리얄", "SAR", false),
        ["SBD"] = new("솔로몬 제도 달러", "SBD", false),
        ["SCR"] = new("세이셸 루피", "SCR", false),
        ["SDD"] = new("수단 디나르", "SDD", false),
        ["SDG"] = new("수단 파운드", "SDG", false),
        ["SDP"] = new("고 수단 파운드", "SDP", false),
        ["SEK"] = new("스웨덴 크로나", "SEK", false),
        ["SGD"] = new("싱가포르 달러", "SGD", false),
        ["SHP"] = new("세인트헬레나 파운드", "SHP", false),
        ["SIT"] = new("슬로베니아 톨라르", "SIT", false),
        ["SKK"] = new("슬로바키아 코루나", "SKK", false),
        ["SLE"] = new("시에라리온 리온", "SLE", false),
        ["SLL"] = new("시에라리온 리온(1964~2022)", "SLL", false),
        ["SOS"] = new("소말리아 실링", "SOS", false),
        ["SRD"] = new("수리남 달러", "SRD", false),
        ["SRG"] = new("수리남 길더", "SRG", false),
        ["SSP"] = new("남수단 파운드", "SSP", false),
        ["STD"] = new("상투메 프린시페 도브라 (1977–2017)", "STD", false),
        ["STN"] = new("상투메 프린시페 도브라", "STN", false),
        ["SUR"] = new("소련 루블", "SUR", false),
        ["SVC"] = new("엘살바도르 콜론", "SVC", false),
        ["SYP"] = new("시리아 파운드", "SYP", false),
        ["SZL"] = new("스와질란드 릴랑게니", "SZL", false),
        ["THB"] = new("태국 바트", "THB", false),
        ["TJR"] = new("타지키스탄 루블", "TJR", false),
        ["TJS"] = new("타지키스탄 소모니", "TJS", false),
        ["TMM"] = new("투르크메니스탄 마나트 (1993–2009)", "TMM", false),
        ["TMT"] = new("투르크메니스탄 마나트", "TMT", false),
        ["TND"] = new("튀니지 디나르", "TND", false),
        ["TOP"] = new("통가 파앙가", "TOP", false),
        ["TPE"] = new("티모르 에스쿠도", "TPE", false),
        ["TRL"] = new("터키 리라(1922~2005)", "TRL", false),
        ["TRY"] = new("튀르키예 리라", "TRY", false),
        ["TTD"] = new("트리니다드 토바고 달러", "TTD", false),
        ["TWD"] = new("신 타이완 달러", "NT$", false),
        ["TZS"] = new("탄자니아 실링", "TZS", false),
        ["UAH"] = new("우크라이나 그리브나", "UAH", false),
        ["UAK"] = new("우크라이나 카보바네츠", "UAK", false),
        ["UGS"] = new("우간다 실링 (1966–1987)", "UGS", false),
        ["UGX"] = new("우간다 실링", "UGX", false),
        ["USD"] = new("미국 달러", "$", false),
        ["USN"] = new("미국 달러(다음날)", "USN", false),
        ["USS"] = new("미국 달러(당일)", "USS", false),
        ["UYI"] = new("우루과이 페소 (UI)", "UYI", false),
        ["UYP"] = new("우루과이 페소 (1975–1993)", "UYP", false),
        ["UYU"] = new("우루과이 페소", "UYU", false),
        ["UZS"] = new("우즈베키스탄 숨", "UZS", false),
        ["VEB"] = new("베네주엘라 볼리바르 (1871–2008)", "VEB", false),
        ["VEF"] = new("베네수엘라 볼리바르 (2008–2018)", "VEF", false),
        ["VES"] = new("베네수엘라 볼리바르", "VES", false),
        ["VND"] = new("베트남 동", "₫", false),
        ["VNN"] = new("베트남 동 (1978–1985)", "VNN", false),
        ["VUV"] = new("바누아투 바투", "VUV", false),
        ["WST"] = new("서 사모아 탈라", "WST", false),
        ["XAF"] = new("중앙아프리카 CFA 프랑", "FCFA", false),
        ["XAG"] = new("은화", "XAG", false),
        ["XAU"] = new("금", "XAU", false),
        ["XBA"] = new("유르코 (유럽 회계 단위)", "XBA", false),
        ["XBB"] = new("유럽 통화 동맹", "XBB", false),
        ["XBC"] = new("유럽 계산 단위 (XBC)", "XBC", false),
        ["XBD"] = new("유럽 계산 단위 (XBD)", "XBD", false),
        ["XCD"] = new("동카리브 달러", "EC$", false),
        ["XCG"] = new("카리브 길더", "XCG", false),
        ["XDR"] = new("특별인출권", "XDR", false),
        ["XEU"] = new("유럽 환율 단위", "XEU", false),
        ["XFO"] = new("프랑스 프랑 (Gold)", "XFO", false),
        ["XFU"] = new("프랑스 프랑 (UIC)", "XFU", false),
        ["XOF"] = new("서아프리카 CFA 프랑", "F CFA", false),
        ["XPD"] = new("팔라듐", "XPD", false),
        ["XPF"] = new("CFP 프랑", "CFPF", false),
        ["XPT"] = new("백금", "XPT", false),
        ["XRE"] = new("RINET 기금", "XRE", false),
        ["XTS"] = new("테스트 통화 코드", "XTS", false),
        ["XXX"] = new("알 수 없는 통화 단위", "XXX", false),
        ["YDD"] = new("예멘 디나르", "YDD", false),
        ["YER"] = new("예멘 리알", "YER", false),
        ["YUD"] = new("유고슬라비아 동전 디나르", "YUD", false),
        ["YUM"] = new("유고슬라비아 노비 디나르", "YUM", false),
        ["YUN"] = new("유고슬라비아 전환 디나르", "YUN", false),
        ["ZAL"] = new("남아프리카 랜드 (금융)", "ZAL", false),
        ["ZAR"] = new("남아프리카 랜드", "ZAR", false),
        ["ZMK"] = new("쟘비아 콰쳐 (1968–2012)", "ZMK", false),
        ["ZMW"] = new("잠비아 콰차", "ZMW", false),
        ["ZRN"] = new("자이르 신권 자이르", "ZRN", false),
        ["ZRZ"] = new("자이르 자이르", "ZRZ", false),
        ["ZWD"] = new("짐바브웨 달러", "ZWD", false),
        ["ZWG"] = new("짐바브웨 골드", "ZWG", false),
        ["ZWL"] = new("짐바브웨 달러 (2009)", "ZWL", false),
        ["ZWR"] = new("짐바브웨 달러 (2008)", "ZWR", false),
    };
    internal static readonly IReadOnlyDictionary<int, CldrUnitDisplayData> Units = new Dictionary<int, CldrUnitDisplayData>
    {
        [(int)UnitConverterUnits.AngleDegree] = new(true, false),
        [(int)UnitConverterUnits.AngleGradian] = new(true, false),
        [(int)UnitConverterUnits.AngleRadian] = new(true, false),
        [(int)UnitConverterUnits.AreaAcre] = new(true, false),
        [(int)UnitConverterUnits.AreaCastle] = new(true, false),
        [(int)UnitConverterUnits.AreaHand] = new(true, false),
        [(int)UnitConverterUnits.AreaHectare] = new(true, false),
        [(int)UnitConverterUnits.AreaPaper] = new(true, false),
        [(int)UnitConverterUnits.AreaPyeong] = new(true, false),
        [(int)UnitConverterUnits.AreaSoccerField] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareCentimeter] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareFoot] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareInch] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareKilometer] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareMeter] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareMile] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareMillimeter] = new(true, false),
        [(int)UnitConverterUnits.AreaSquareYard] = new(true, false),
        [(int)UnitConverterUnits.DataBit] = new(true, false),
        [(int)UnitConverterUnits.DataByte] = new(true, false),
        [(int)UnitConverterUnits.DataCD] = new(true, false),
        [(int)UnitConverterUnits.DataDVD] = new(true, false),
        [(int)UnitConverterUnits.DataExabits] = new(true, false),
        [(int)UnitConverterUnits.DataExabytes] = new(true, false),
        [(int)UnitConverterUnits.DataExbibits] = new(true, false),
        [(int)UnitConverterUnits.DataExbibytes] = new(true, false),
        [(int)UnitConverterUnits.DataFloppyDisk] = new(true, false),
        [(int)UnitConverterUnits.DataGibibits] = new(true, false),
        [(int)UnitConverterUnits.DataGibibytes] = new(true, false),
        [(int)UnitConverterUnits.DataGigabit] = new(true, false),
        [(int)UnitConverterUnits.DataGigabyte] = new(true, false),
        [(int)UnitConverterUnits.DataKibibits] = new(true, false),
        [(int)UnitConverterUnits.DataKibibytes] = new(true, false),
        [(int)UnitConverterUnits.DataKilobit] = new(true, false),
        [(int)UnitConverterUnits.DataKilobyte] = new(true, false),
        [(int)UnitConverterUnits.DataMebibits] = new(true, false),
        [(int)UnitConverterUnits.DataMebibytes] = new(true, false),
        [(int)UnitConverterUnits.DataMegabit] = new(true, false),
        [(int)UnitConverterUnits.DataMegabyte] = new(true, false),
        [(int)UnitConverterUnits.DataNibble] = new(true, false),
        [(int)UnitConverterUnits.DataPebibits] = new(true, false),
        [(int)UnitConverterUnits.DataPebibytes] = new(true, false),
        [(int)UnitConverterUnits.DataPetabit] = new(true, false),
        [(int)UnitConverterUnits.DataPetabyte] = new(true, false),
        [(int)UnitConverterUnits.DataTebibits] = new(true, false),
        [(int)UnitConverterUnits.DataTebibytes] = new(true, false),
        [(int)UnitConverterUnits.DataTerabit] = new(true, false),
        [(int)UnitConverterUnits.DataTerabyte] = new(true, false),
        [(int)UnitConverterUnits.DataYobibits] = new(true, false),
        [(int)UnitConverterUnits.DataYobibytes] = new(true, false),
        [(int)UnitConverterUnits.DataYottabit] = new(true, false),
        [(int)UnitConverterUnits.DataYottabyte] = new(true, false),
        [(int)UnitConverterUnits.DataZebibits] = new(true, false),
        [(int)UnitConverterUnits.DataZebibytes] = new(true, false),
        [(int)UnitConverterUnits.DataZetabits] = new(true, false),
        [(int)UnitConverterUnits.DataZetabytes] = new(true, false),
        [(int)UnitConverterUnits.EnergyBanana] = new(true, false),
        [(int)UnitConverterUnits.EnergyBattery] = new(true, false),
        [(int)UnitConverterUnits.EnergyBritishThermalUnit] = new(true, false),
        [(int)UnitConverterUnits.EnergyCalorie] = new(true, false),
        [(int)UnitConverterUnits.EnergyElectronVolt] = new(true, false),
        [(int)UnitConverterUnits.EnergyFootPound] = new(true, false),
        [(int)UnitConverterUnits.EnergyJoule] = new(true, false),
        [(int)UnitConverterUnits.EnergyKilocalorie] = new(true, false),
        [(int)UnitConverterUnits.EnergyKilojoule] = new(true, false),
        [(int)UnitConverterUnits.EnergyKilowatthour] = new(true, false),
        [(int)UnitConverterUnits.EnergySliceOfCake] = new(true, false),
        [(int)UnitConverterUnits.LengthAngstrom] = new(true, false),
        [(int)UnitConverterUnits.LengthCentimeter] = new(true, false),
        [(int)UnitConverterUnits.LengthFoot] = new(true, false),
        [(int)UnitConverterUnits.LengthHand] = new(true, false),
        [(int)UnitConverterUnits.LengthInch] = new(true, false),
        [(int)UnitConverterUnits.LengthJumboJet] = new(true, false),
        [(int)UnitConverterUnits.LengthKilometer] = new(true, false),
        [(int)UnitConverterUnits.LengthMeter] = new(true, false),
        [(int)UnitConverterUnits.LengthMicron] = new(true, false),
        [(int)UnitConverterUnits.LengthMile] = new(true, false),
        [(int)UnitConverterUnits.LengthMillimeter] = new(true, false),
        [(int)UnitConverterUnits.LengthNanometer] = new(true, false),
        [(int)UnitConverterUnits.LengthNauticalMile] = new(true, false),
        [(int)UnitConverterUnits.LengthPaperclip] = new(true, false),
        [(int)UnitConverterUnits.LengthYard] = new(true, false),
        [(int)UnitConverterUnits.PowerBritishThermalUnitPerMinute] = new(true, false),
        [(int)UnitConverterUnits.PowerFootPoundPerMinute] = new(true, false),
        [(int)UnitConverterUnits.PowerHorse] = new(true, false),
        [(int)UnitConverterUnits.PowerHorsepower] = new(true, false),
        [(int)UnitConverterUnits.PowerKilowatt] = new(true, false),
        [(int)UnitConverterUnits.PowerLightBulb] = new(true, false),
        [(int)UnitConverterUnits.PowerTrainEngine] = new(true, false),
        [(int)UnitConverterUnits.PowerWatt] = new(true, false),
        [(int)UnitConverterUnits.PressureAtmosphere] = new(true, false),
        [(int)UnitConverterUnits.PressureBar] = new(true, false),
        [(int)UnitConverterUnits.PressureKiloPascal] = new(true, false),
        [(int)UnitConverterUnits.PressureMillimeterOfMercury] = new(true, false),
        [(int)UnitConverterUnits.PressurePSI] = new(true, false),
        [(int)UnitConverterUnits.PressurePascal] = new(true, false),
        [(int)UnitConverterUnits.SpeedCentimetersPerSecond] = new(true, false),
        [(int)UnitConverterUnits.SpeedFeetPerSecond] = new(true, false),
        [(int)UnitConverterUnits.SpeedHorse] = new(true, false),
        [(int)UnitConverterUnits.SpeedJet] = new(true, false),
        [(int)UnitConverterUnits.SpeedKilometersPerHour] = new(true, false),
        [(int)UnitConverterUnits.SpeedKnot] = new(true, false),
        [(int)UnitConverterUnits.SpeedMach] = new(true, false),
        [(int)UnitConverterUnits.SpeedMetersPerSecond] = new(true, false),
        [(int)UnitConverterUnits.SpeedMilesPerHour] = new(true, false),
        [(int)UnitConverterUnits.SpeedTurtle] = new(true, false),
        [(int)UnitConverterUnits.TemperatureKelvin] = new(true, false),
        [(int)UnitConverterUnits.TimeDay] = new(true, false),
        [(int)UnitConverterUnits.TimeHour] = new(true, false),
        [(int)UnitConverterUnits.TimeMicrosecond] = new(true, false),
        [(int)UnitConverterUnits.TimeMillisecond] = new(true, false),
        [(int)UnitConverterUnits.TimeMinute] = new(true, false),
        [(int)UnitConverterUnits.TimeSecond] = new(true, false),
        [(int)UnitConverterUnits.TimeWeek] = new(true, false),
        [(int)UnitConverterUnits.TimeYear] = new(true, false),
        [(int)UnitConverterUnits.VolumeBathtub] = new(true, false),
        [(int)UnitConverterUnits.VolumeCoffeeCup] = new(true, false),
        [(int)UnitConverterUnits.VolumeCubicCentimeter] = new(true, false),
        [(int)UnitConverterUnits.VolumeCubicFoot] = new(true, false),
        [(int)UnitConverterUnits.VolumeCubicInch] = new(true, false),
        [(int)UnitConverterUnits.VolumeCubicMeter] = new(true, false),
        [(int)UnitConverterUnits.VolumeCubicYard] = new(true, false),
        [(int)UnitConverterUnits.VolumeCupUS] = new(true, false),
        [(int)UnitConverterUnits.VolumeFluidOunceUK] = new(true, false),
        [(int)UnitConverterUnits.VolumeFluidOunceUS] = new(true, false),
        [(int)UnitConverterUnits.VolumeGallonUK] = new(true, false),
        [(int)UnitConverterUnits.VolumeGallonUS] = new(true, false),
        [(int)UnitConverterUnits.VolumeLiter] = new(true, false),
        [(int)UnitConverterUnits.VolumeMilliliter] = new(true, false),
        [(int)UnitConverterUnits.VolumePintUS] = new(true, false),
        [(int)UnitConverterUnits.VolumeQuartUK] = new(true, false),
        [(int)UnitConverterUnits.VolumeQuartUS] = new(true, false),
        [(int)UnitConverterUnits.VolumeSwimmingPool] = new(true, false),
        [(int)UnitConverterUnits.VolumeTablespoonUK] = new(true, false),
        [(int)UnitConverterUnits.VolumeTablespoonUS] = new(true, false),
        [(int)UnitConverterUnits.VolumeTeaspoonUK] = new(true, false),
        [(int)UnitConverterUnits.VolumeTeaspoonUS] = new(true, false),
        [(int)UnitConverterUnits.WeightCarat] = new(true, false),
        [(int)UnitConverterUnits.WeightCentigram] = new(true, false),
        [(int)UnitConverterUnits.WeightDecagram] = new(true, false),
        [(int)UnitConverterUnits.WeightDecigram] = new(true, false),
        [(int)UnitConverterUnits.WeightElephant] = new(true, false),
        [(int)UnitConverterUnits.WeightGram] = new(true, false),
        [(int)UnitConverterUnits.WeightHectogram] = new(true, false),
        [(int)UnitConverterUnits.WeightKilogram] = new(true, false),
        [(int)UnitConverterUnits.WeightLongTon] = new(true, false),
        [(int)UnitConverterUnits.WeightMilligram] = new(true, false),
        [(int)UnitConverterUnits.WeightOunce] = new(true, false),
        [(int)UnitConverterUnits.WeightPound] = new(true, false),
        [(int)UnitConverterUnits.WeightShortTon] = new(true, false),
        [(int)UnitConverterUnits.WeightSnowflake] = new(true, false),
        [(int)UnitConverterUnits.WeightSoccerBall] = new(true, false),
        [(int)UnitConverterUnits.WeightStone] = new(true, false),
        [(int)UnitConverterUnits.WeightTonne] = new(true, false),
        [(int)UnitConverterUnits.WeightWhale] = new(true, false),
    };
}
