namespace Graphing
{
    public enum ContextualActionType
    {
        None = 0,
        SolveEquation = 1,
        Compare = 2,
        Expand = 3,
        Graph2D = 4,
        ListGraph2D = 5,
        GraphBothSides2D = 6,
        Graph3D = 7,
        GraphBothSides3D = 8,
        GraphInequality = 9,
        Assign = 10,
        Factor = 11,
        Deriv = 12,
        IndefiniteIntegral = 13,
        Graph2DExpression = 14,
        Graph3DExpression = 15,
        SolveInequality = 16,
        Calculate = 17,
        Round = 18,
        Floor = 19,
        Ceiling = 20,
        MatrixMask = 21,
        MatrixDeterminant = 22,
        MatrixInverse = 23,
        MatrixTrace = 24,
        MatrixTranspose = 25,
        MatrixSize = 26,
        MatrixReduce = 27,
        ListMask = 28,
        ListSort = 29,
        ListMean = 30,
        ListMedian = 31,
        ListMode = 32,
        ListLcm = 33,
        ListGcf = 34,
        ListSum = 35,
        ListProduct = 36,
        ListMax = 37,
        ListMin = 38,
        ListVariance = 39,
        ListStdDev = 40,
        ShowVerboseSolution = 41,
        TypeMask = 42,
        Informational = 43
    }
}
