<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Graphing</RootNamespace>
    <AssemblyName>GraphingInterfaces</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Include="GraphingInterfaces.manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\Calculator\Vendor\MathComposer\src\MathComposer.Core\MathComposer.Core.csproj" />
  </ItemGroup>
</Project>
