namespace Calculator.BrowserHost;

internal sealed class TelemetryUiSnapshot
{
    public long Sequence { get; set; }
    public long CapturedAtUnixMs { get; set; }
    public double UptimeMs { get; set; }
    public string? BootStage { get; set; }
    public string? Visibility { get; set; }
    public bool HasFocus { get; set; }
    public long FrameCountTotal { get; set; }
    public int FramesSinceLast { get; set; }
    public double FrameRate { get; set; }
    public double MaxFrameGapMs { get; set; }
    public double MaxFrameGapTotalMs { get; set; }
    public long LongFrameCountTotal { get; set; }
    public long LongTaskCountTotal { get; set; }
    public double LongTaskDurationSinceLastMs { get; set; }
    public double MaxLongTaskMs { get; set; }
    public long PointerDownTotal { get; set; }
    public long PointerMoveTotal { get; set; }
    public int PointerMoveSinceLast { get; set; }
    public long PointerUpTotal { get; set; }
    public long PointerCancelTotal { get; set; }
    public long WheelTotal { get; set; }
    public int WheelSinceLast { get; set; }
    public int ActivePointers { get; set; }
    public double LastPointerAgeMs { get; set; }
    public long GotPointerCaptureTotal { get; set; }
    public long LostPointerCaptureTotal { get; set; }
    public bool CanvasFound { get; set; }
    public int CanvasWidth { get; set; }
    public int CanvasHeight { get; set; }
    public double CanvasCssWidth { get; set; }
    public double CanvasCssHeight { get; set; }
    public long CanvasPresentTotal { get; set; }
    public int CanvasPresentSinceLast { get; set; }
    public double CanvasPresentAgeMs { get; set; }
    public long CanvasFrameReceivedTotal { get; set; }
    public long CanvasFramePresentedTotal { get; set; }
    public long CanvasFrameDroppedTotal { get; set; }
    public int CanvasFramePending { get; set; }
    public int InputQueueDepth { get; set; }
    public int InputQueueHighWater { get; set; }
    public long InputQueueDequeued { get; set; }
    public long InputQueueRetries { get; set; }
    public long InputQueueShed { get; set; }
    public bool WebGlContextLost { get; set; }
    public long WebGlContextLosses { get; set; }
    public long WebGlContextRestores { get; set; }
    public long KeyDownTotal { get; set; }
    public long BeforeInputTotal { get; set; }
    public long InputTotal { get; set; }
    public long SelectionChangeTotal { get; set; }
    public long ContextMenuTotal { get; set; }
    public long FocusInTotal { get; set; }
    public long FocusOutTotal { get; set; }
    public string? ActiveElement { get; set; }
    public bool NativeInputFocused { get; set; }
    public int NativeInputValueLength { get; set; }
    public int NativeSelectionStart { get; set; }
    public int NativeSelectionEnd { get; set; }
    public double VisualViewportWidth { get; set; }
    public double VisualViewportHeight { get; set; }
    public double VisualViewportScale { get; set; }
    public double VisualViewportOffsetTop { get; set; }
    public int InnerWidth { get; set; }
    public int InnerHeight { get; set; }
    public double DevicePixelRatio { get; set; }
    public double WasmMemoryBytes { get; set; }
    public double WasmMemoryMaxBytes { get; set; }
    public double JsHeapBytes { get; set; }
    public bool GraphPipelineProbeStarted { get; set; }
    public bool GraphPipelineProbeInFlight { get; set; }
    public long GraphRequestedGeneration { get; set; }
    public long GraphWorkerGeneration { get; set; }
    public long GraphCompletedGeneration { get; set; }
    public long GraphPublishedGeneration { get; set; }
    public long GraphCommittedGeneration { get; set; }
    public int GraphWorkerActive { get; set; }
    public int GraphCompletedStatus { get; set; }
    public int GraphCommitStatus { get; set; }
    public long GraphRequestCount { get; set; }
    public long GraphWorkerStartCount { get; set; }
    public long GraphWorkerCompletionCount { get; set; }
    public long GraphCommitCount { get; set; }
    public long GraphCommitMissCount { get; set; }
    public long GraphSettlementTimerCount { get; set; }
    public long GraphSettlementRequestCount { get; set; }
    public long GraphRenderCount { get; set; }
    public int GraphRendererActiveCount { get; set; }
    public long GraphRendererCreatedCount { get; set; }
    public long GraphRendererDisposedCount { get; set; }
    public int ConverterStage { get; set; }
    public int ConverterStageTick { get; set; }
    public int ConverterStageThreadId { get; set; }
    public int ConverterUiThreadId { get; set; }
    public long ConverterRequestCount { get; set; }
    public long ConverterCompletionCount { get; set; }
    public long ConverterFailureCount { get; set; }
    public int ConverterFailureKind { get; set; }
    public long GraphPublishSequence { get; set; }
    public int ApplicationRootMode { get; set; }
    public int MainPageCount { get; set; }
    public int RootMainPageId { get; set; }
    public int LastNavigatedMainPageId { get; set; }
    public int LastNavigatedMode { get; set; }
}
