using System.Collections.Immutable;

namespace Graphing.Symbolics;

internal sealed record SingleHarmonicRangeCertificateReplayReplayFourier(ImmutableSortedDictionary<int, SingleHarmonicRangeCertificateReplayReplayComplex> Coefficients);
