namespace Graphing.Symbolics;

internal sealed record ZeroBaseTangentPowerCertificateReplayReplayEvidence(string ExponentCanonical, ZeroBaseTangentPowerCertificateReplayReplayPattern Pattern, PeriodicIntervalSet Domain, ExactReal Period);
