<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GraphingRaster.Skia</RootNamespace>
    <AssemblyName>GraphingRaster.Skia</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphingInterfaces\GraphingInterfaces.csproj" />
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
  </ItemGroup>
</Project>
