<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CalculatorApp.ViewModel.Tests</RootNamespace>
    <AssemblyName>CalculatorApp.ViewModel.Tests</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DefineConstants>NETFX_CORE;WINDOWS_UWP</DefineConstants>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.26100.4948" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalculatorApp.ViewModel\CalculatorApp.ViewModel.csproj" />
  </ItemGroup>
</Project>
