namespace CalcManagerManaged.Resources;

public static class DefaultCombinedCalcResource
{
    public static Dictionary<string, string> StringResources = new()
    {
        {"sDecimal", "."},
        {"sThousand", ","},
        {"sGrouping", "3;0"},
        {"Square meters-Acres", "4046.8564224"},
        {"Square meters-Square meters", "1"},
        {"Square meters-Square feet", "0.09290304"},
        {"Square meters-Square yards", "0.83612736"},
        {"Square meters-Square millimeters", "0.000001"},
        {"Square meters-Square centimeters", "0.0001"},
        {"Square meters-Square inches", "0.00064516"},
        {"Square meters-Square miles", "2589988.110336"},
        {"Square meters-Square kilometers", "1000000"},
        {"Square meters-Hectares", "10000"},
        {"Square meters-hands", "0.012516104"},
        {"Square meters-sheets of paper", "0.06032246"},
        {"Square meters-soccer fields", "10869.66"},
        {"Square meters-castles", "100000"},
        {"Megabytes-Bits", "0.000000125"},
        {"Megabytes-Nibble", "0.0000005"},
        {"Megabytes-Bytes", "0.000001"},
        {"Megabytes-Kilobytes", "0.001"},
        {"Megabytes-Megabytes", "1"},
        {"Megabytes-Gigabytes", "1000"},
        {"Megabytes-Terabytes", "1000000"},
        {"Megabytes-Petabytes", "1000000000"},
        {"Megabytes-Exabytes", "1000000000000"},
        {"Megabytes-Zetabytes", "1000000000000000"},
        {"Megabytes-Yottabyte", "1000000000000000000"},
        {"Megabytes-Kilobits", "0.000125"},
        {"Megabytes-Megabits", "0.125"},
        {"Megabytes-Gigabits", "125"},
        {"Megabytes-Terabits", "125000"},
        {"Megabytes-Petabits", "125000000"},
        {"Megabytes-Exabits", "125000000000"},
        {"Megabytes-Zetabits", "125000000000000"},
        {"Megabytes-Yottabit", "125000000000000000"},
        {"Megabytes-Gibibits", "134.217728"},
        {"Megabytes-Gibibytes", "1073.741824"},
        {"Megabytes-Kibibits", "0.000128"},
        {"Megabytes-Kibibytes", "0.001024"},
        {"Megabytes-Mebibits", "0.131072"},
        {"Megabytes-Mebibytes", "1.048576"},
        {"Megabytes-Pebibits", "140737488.355328"},
        {"Megabytes-Pebibytes", "1125899906.842624"},
        {"Megabytes-Tebibits", "137438.953472"},
        {"Megabytes-Tebibytes", "1099511.627776"},
        {"Megabytes-Exbibits", "144115188075.855872"},
        {"Megabytes-Exbibytes", "1152921504606.846976"},
        {"Megabytes-Zebibits", "147573952589676.412928"},
        {"Megabytes-Zebibytes", "1180591620717411.303424"},
        {"Megabytes-Yobibits", "151115727451828646.838272"},
        {"Megabytes-Yobibytes", "1208925819614629174.706176"},
        {"Megabytes-floppy disks", "1.474560"},
        {"Megabytes-CDs", "734.003200"},
        {"Megabytes-DVDs", "5046.586573"},
        {"Joules-Thermal calories", "4.184"},
        {"Joules-Food calories", "4184"},
        {"Joules-British thermal units", "1055.056"},
        {"Joules-Kilojoules", "1000"},
        {"Joules-FahrenheitVolt", "0.0000000000000000001602176565"},
        {"Joules-Joules", "1"},
        {"Joules-Foot-pounds", "1.3558179483314"},
        {"Joules-batteries", "9000"},
        {"Joules-bananas", "439614"},
        {"Joules-slices of cake", "1046700"},
        {"Meters-Inches", "0.0254"},
        {"Meters-Feet", "0.3048"},
        {"Meters-Yards", "0.9144"},
        {"Meters-Miles", "1609.344"},
        {"Meters-Microns", "0.000001"},
        {"Meters-Millimeters", "0.001"},
        {"Meters-Nanometers", "0.000000001"},
        {"Meters-Centimeters", "0.01"},
        {"Meters-Meters", "1"},
        {"Meters-Kilometers", "1000"},
        {"Meters-Nautical Miles", "1852"},
        {"Meters-paperclips", "0.035052"},
        {"Meters-hands", "0.18669"},
        {"Meters-jumbo jets", "76"},
        {"Watts-British thermal unitsPerMinute", "17.58426666666667"},
        {"Watts-Foot-pounds/minute", "0.0225969658055233"},
        {"Watts-Watts", "1"},
        {"Watts-Kilowatts", "1000"},
        {"Watts-Horsepower (US)", "745.69987158227022"},
        {"Watts-light bulbs", "60"},
        {"Watts-horses", "745.7"},
        {"Watts-train engines", "2982799.486329081"},
        {"Seconds-Days", "86400"},
        {"Seconds-Seconds", "1"},
        {"Seconds-Weeks", "604800"},
        {"Seconds-Years", "31557600"},
        {"Seconds-Milliseconds", "0.001"},
        {"Seconds-Microseconds", "0.000001"},
        {"Seconds-Minutes", "60"},
        {"Seconds-Hours", "3600"},
        {"Cubic centimeters-Cups (US)", "236.588237"},
        {"Cubic centimeters-Pints (US)", "473.176473"},
        {"Cubic centimeters-Pints (UK)", "568.26125"},
        {"Cubic centimeters-Quarts (US)", "946.352946"},
        {"Cubic centimeters-Quarts (UK)", "1136.5225"},
        {"Cubic centimeters-Gallons (US)", "3785.411784"},
        {"Cubic centimeters-Gallons (UK)", "4546.09"},
        {"Cubic centimeters-Liters", "1000"},
        {"Cubic centimeters-Teaspoons (US)", "4.928922"},
        {"Cubic centimeters-Tablespoons (US)", "14.786765"},
        {"Cubic centimeters-Cubic centimeters", "1"},
        {"Cubic centimeters-Cubic yards", "764554.857984"},
        {"Cubic centimeters-Cubic meters", "1000000"},
        {"Cubic centimeters-Milliliters", "1"},
        {"Cubic centimeters-Cubic inches", "16.387064"},
        {"Cubic centimeters-Cubic feet", "28316.846592"},
        {"Cubic centimeters-Fluid ounces (US)", "29.5735295625"},
        {"Cubic centimeters-Fluid ounces (UK)", "28.4130625"},
        {"Cubic centimeters-Teaspoons (UK)", "5.91938802083333333333"},
        {"Cubic centimeters-Tablespoons (UK)", "17.7581640625"},
        {"Cubic centimeters-coffee cups", "236.5882"},
        {"Cubic centimeters-bathtubs", "378541.2"},
        {"Cubic centimeters-swimming pools", "3750000000"},
        {"Kilograms-Kilograms", "1"},
        {"Kilograms-Hectograms", "0.1"},
        {"Kilograms-Dekagrams", "0.01"},
        {"Kilograms-Grams", "0.001"},
        {"Kilograms-Pounds", "0.45359237"},
        {"Kilograms-Ounces", "0.028349523125"},
        {"Kilograms-Milligrams", "0.000001"},
        {"Kilograms-Centigrams", "0.00001"},
        {"Kilograms-Decigrams", "0.0001"},
        {"Kilograms-Long tons (UK)", "1016.0469088"},
        {"Kilograms-Metric tonnes", "1000"},
        {"Kilograms-Stone", "6.35029318"},
        {"Kilograms-Carats", "0.0002"},
        {"Kilograms-Short tons (US)", "907.18474"},
        {"Kilograms-snowflakes", "0.000002"},
        {"Kilograms-soccer balls", "0.4325"},
        {"Kilograms-elephants", "4000"},
        {"Kilograms-whales", "90000"},
        {"CentimetersPerSecond-CentimetersPerSecond", "1"},
        {"CentimetersPerSecond-Feet per second", "30.48"},
        {"CentimetersPerSecond-Kilometers per hour", "27.777777777777777777778"},
        {"CentimetersPerSecond-Knots", "51.44"},
        {"CentimetersPerSecond-Mach", "34030"},
        {"CentimetersPerSecond-Meters per second", "100"},
        {"CentimetersPerSecond-Miles per hour", "44.7"},
        {"CentimetersPerSecond-turtles", "8.94"},
        {"CentimetersPerSecond-horses", "2011.5"},
        {"CentimetersPerSecond-jets", "24585"},
        {"Degrees-Degrees", "1"},
        {"Degrees-Radians", "57.29577951308233"},
        {"Degrees-Gradians", "0.9"},
        {"Atmospheres-Atmospheres", "1"},
        {"Atmospheres-Bars", "0.9869232667160128"},
        {"Atmospheres-Kilopascals", "0.0098692326671601"},
        {"Atmospheres-Millimeters of mercury ", "0.0013155687145324"},
        {"Atmospheres-Pascals", "9.869232667160128e-6"},
        {"Atmospheres-Pounds per square inch", "0.068045961016531"},
        {"Liters-Cubic meters-2", "0.002"},
        {"Milliliters-Cubic centimeters", "1"},
        {"Milliliters-Cubic centimeters-1", "1"},
        {"Milliliters-Liters", "1000"},
        {"Milliliters-Milliliters", "1"},
        {"Nanometers-Microns-3", "0.003"},
        {"Joules-Kilowatthour", "3600000"},
        {"AppName", "Calculator"},
        {"DevAppName", "Calculator [Dev]"},
        {"AppStoreName", "Windows Calculator"},
        {"DevAppStoreName", "Windows Calculator [Dev]"},
        {"AppDescription", "Calculator"},
        {"DevAppDescription", "Calculator [Dev]"},
        {"AppUpdateResource", "AppUpdate2"},
        {"decimalButton.Tag", "DEC"},
        {"binaryButton.Tag", "BIN"},
        {"hexButton.Tag", "HEX"},
        {"octButton.Tag", "OCT"},
        {"copyMenuItem", "Copy"},
        {"pasteMenuItem", "Paste"},
        {"SupplementaryResultsHeader.Text", "About equal to"},
        {"ClearHistory.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlShiftChord", "D"},
        {"HistoryButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "H"},
        {"memButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "M"},
        {"clearButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Escape"},
        {"clearEntryButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Delete"},
        {"closeParenthesisButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", ")"},
        {"cosButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "O"},
        {"coshButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "O"},
        {"expButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "X"},
        {"dmsButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "M"},
        {"decimalSeparatorButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Decimal"},
        {"divideButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "/"},
        {"equalButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "="},
        {"equalButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Enter"},
        {"factorialButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "!"},
        {"ftoeButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "V"},
        {"invertButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "R"},
        {"logBase10Button.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "L"},
        {"logBaseEButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "N"},
        {"minusButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "-"},
        {"modButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "%"},
        {"negateButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F9"},
        {"converterNegateButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F9"},
        {"converterNegateButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "-"},
        {"num0Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "0"},
        {"num1Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "1"},
        {"num2Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "2"},
        {"num3Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "3"},
        {"num4Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "4"},
        {"num5Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "5"},
        {"num6Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "6"},
        {"num7Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "7"},
        {"num8Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "8"},
        {"num9Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "9"},
        {"aButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "A"},
        {"bButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "B"},
        {"cButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "C"},
        {"dButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "D"},
        {"eButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "E"},
        {"fButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F"},
        {"aButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "A"},
        {"bButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "B"},
        {"cButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "C"},
        {"dButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "D"},
        {"eButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "E"},
        {"fButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "F"},
        {"openParenthesisButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "("},
        {"percentButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "%"},
        {"piButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "P"},
        {"plusButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "+"},
        {"powerButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Y"},
        {"powerButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "^"},
        {"powerOf10Button.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "G"},
        {"sinButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "S"},
        {"sinhButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "S"},
        {"squareRootButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "@"},
        {"tanButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "T"},
        {"tanhButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "T"},
        {"xpower2Button.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Q"},
        {"xpower3Button.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "#"},
        {"ySquareRootButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "Y"},
        {"backSpaceButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Back"},
        {"multiplyButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "*"},
        {"orButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "|"},
        {"notButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "~"},
        {"andButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "&"},
        {"lshButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "<"},
        {"rshButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", ">"},
        {"xorButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "^"},
        {"rolButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "<"},
        {"rorButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", ">"},
        {"decimalButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F6"},
        {"hexButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F5"},
        {"octButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F7"},
        {"binaryButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F8"},
        {"degreeButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "D"},
        {"invcosButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "O"},
        {"invcoshButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlShiftChord", "O"},
        {"invsinButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "S"},
        {"invsinhButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlShiftChord", "S"},
        {"invtanButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "T"},
        {"invtanhButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlShiftChord", "T"},
        {"powerOfEButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "N"},
        {"copyButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "C"},
        {"copyButtonAlternate.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "Insert"},
        {"pasteButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "V"},
        {"pasteButtonAlternate.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "Insert"},
        {"BitFlipItemAutomationName", "%1, value %2"},
        {"BitPosition", "%1 bit"},
        {"63", "63rd"},
        {"62", "62nd"},
        {"61", "61st"},
        {"60", "60th"},
        {"59", "59th"},
        {"58", "58th"},
        {"57", "57th"},
        {"56", "56th"},
        {"55", "55th"},
        {"54", "54th"},
        {"53", "53rd"},
        {"52", "52nd"},
        {"51", "51st"},
        {"50", "50th"},
        {"49", ")"},
        {"48", "("},
        {"47", "Exp"},
        {"46", "46th"},
        {"45", "45th"},
        {"44", "44th"},
        {"43", "43rd"},
        {"42", "42nd"},
        {"41", "="},
        {"40", "Pi"},
        {"39", "39th"},
        {"38", "%"},
        {"37", "10^"},
        {"36", "36th"},
        {"35", "dms"},
        {"34", "34th"},
        {"33", "33rd"},
        {"32", "32nd"},
        {"31", "31st"},
        {"30", "√"},
        {"29", "log"},
        {"28", "ln"},
        {"27", "tanh"},
        {"26", "cosh"},
        {"25", "sinh"},
        {"24", "tan"},
        {"23", "cis"},
        {"22", "sin"},
        {"21", "NOT"},
        {"20", "RoR"},
        {"19", "RoL"},
        {"18", "Int"},
        {"17", "^"},
        {"16", "yroot"},
        {"15", "Mod"},
        {"14", "-"},
        {"13", "+"},
        {"12", "×"},
        {"11", "÷"},
        {"10", "Rsh"},
        {"9", "Lsh"},
        {"8", "XOR"},
        {"7", "OR"},
        {"6", "AND"},
        {"5", "5th"},
        {"4", "."},
        {"3", "3rd"},
        {"2", "CE"},
        {"1", "1st"},
        {"LeastSignificantBit", "least significant bit"},
        {"MemoryButton_Open", "Open memory flyout"},
        {"MemoryButton_Close", "Close memory flyout"},
        {"AlwaysOnTop_Enter", "Keep on top"},
        {"AlwaysOnTop_Exit", "Back to full view"},
        {"MemoryButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Memory"},
        {"HistoryButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "History (Ctrl+H)"},
        {"bitFlip.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Bit toggling keypad"},
        {"fullKeypad.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Full keypad"},
        {"ClearMemoryButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "L"},
        {"ClearMemoryButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Clear all memory (Ctrl+L)"},
        {"MemRecall.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "R"},
        {"MemPlus.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "P"},
        {"MemMinus.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "Q"},
        {"MemoryLabel.Text", "Memory"},
        {"MemoryPivotItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Memory"},
        {"HistoryLabel.Text", "History"},
        {"HistoryPivotItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "History"},
        {"LeftChevron.Text", "<<"},
        {"converterModeButton.Content", "Converter"},
        {"scientificModeButton.Content", "Scientific"},
        {"standardModeButton.Content", "Standard"},
        {"converterModeButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Converter mode"},
        {"scientificModeButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scientific mode"},
        {"standardModeButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Standard mode"},
        {"ClearHistory.Name", "Clear all history"},
        {"ClearHistory.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Clear all history"},
        {"HideHistory.Name", "Hide"},
        {"StandardModeText", "Standard"},
        {"ScientificModeText", "Scientific"},
        {"ProgrammerModeText", "Programmer"},
        {"ConverterModeText", "Converter"},
        {"CalculatorModeText", "Calculator"},
        {"ConverterModeTextCaps", "Converter"},
        {"CalculatorModeTextCaps", "Calculator"},
        {"ConverterModePluralText", "Converters"},
        {"CalculatorModePluralText", "Calculators"},
        {"Format_CalculatorResults", "Display is %1"},
        {"Format_CalculatorAlwaysOnTopResults", "Expression is %1, Current input is %2"},
        {"Format_CalculatorResults_Decimal", "Display is %1 point"},
        {"Format_CalculatorExpression", "Expression is %1"},
        {"Display_Copied", "Display value copied to clipboard"},
        {"HistoryPane", "History"},
        {"MemoryPane", "Memory"},
        {"Format_HexButtonValue", "HexaDecimal %1"},
        {"Format_DecButtonValue", "Decimal %1"},
        {"Format_OctButtonValue", "Octal %1"},
        {"Format_BinButtonValue", "Binary %1"},
        {"ClearHistory.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Clear all history"},
        {"HistoryList_Cleared", "History cleared"},
        {"HideHistory.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hide history"},
        {"HistoryButton_Open", "Open history flyout"},
        {"HistoryButton_Close", "Close history flyout"},
        {"memButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Memory store"},
        {"memButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Memory store (Ctrl+M)"},
        {"ClearMemoryButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Clear all memory"},
        {"Memory_Cleared", "Memory cleared"},
        {"MemRecall.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Memory recall"},
        {"MemRecall.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Memory recall (Ctrl+R)"},
        {"MemPlus.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Memory add"},
        {"MemPlus.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Memory add (Ctrl+P)"},
        {"MemMinus.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Memory subtract"},
        {"MemMinus.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Memory subtract (Ctrl+Q)"},
        {"ClearMemoryItemButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Clear memory item"},
        {"ClearMemoryItemButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Clear memory item"},
        {"MemPlusItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Add to memory item"},
        {"MemPlusItem.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Add to memory item"},
        {"MemMinusItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Subtract from memory item"},
        {"MemMinusItem.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Subtract from memory item"},
        {"ClearMemorySwipeItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Clear memory item"},
        {"ClearMemoryMenuItem.Text", "Clear memory item"},
        {"MemPlusSwipeItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Add to memory item"},
        {"MemPlusMenuItem.Text", "Add to memory item"},
        {"MemMinusSwipeItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Subtract from memory item"},
        {"MemMinusMenuItem.Text", "Subtract from memory item"},
        {"DeleteHistorySwipeItem.Text", "Delete"},
        {"CopyHistoryMenuItem.Text", "Copy"},
        {"DeleteHistoryMenuItem.Text", "Delete"},
        {"DeleteHistorySwipeItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Delete history item"},
        {"DeleteHistoryMenuItem.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Delete history item"},
        {"backSpaceButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Backspace"},
        {"BinaryZero.Text", "0"},
        {"BinaryOne.Text", "1"},
        {"num0Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Zero"},
        {"num1Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "One"},
        {"num2Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Two"},
        {"num3Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Three"},
        {"num4Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Four"},
        {"num5Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Five"},
        {"num6Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Six"},
        {"num7Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Seven"},
        {"num8Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Eight"},
        {"num9Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Nine"},
        {"aButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "A"},
        {"bButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "B"},
        {"cButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "C"},
        {"dButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "D"},
        {"eButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "E"},
        {"fButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "F"},
        {"andButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "And"},
        {"orButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Or"},
        {"notButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Not"},
        {"rolButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Rotate on left"},
        {"rorButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Rotate on right"},
        {"lshButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Left shift"},
        {"rshButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Right shift"},
        {"xorButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Exclusive or"},
        {"qwordButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Quadruple Word toggle"},
        {"dwordButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Double Word toggle"},
        {"wordButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Word toggle"},
        {"byteButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Byte toggle"},
        {"bitFlip.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Bit toggling keypad"},
        {"fullKeypad.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Full keypad"},
        {"decimalSeparatorButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Decimal separator"},
        {"clearEntryButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Clear entry"},
        {"clearButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Clear"},
        {"divideButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Divide by"},
        {"multiplyButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Multiply by"},
        {"equalButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Equals"},
        {"shiftButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Inverse function"},
        {"minusButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Minus"},
        {"minus", "Minus"},
        {"plusButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Plus"},
        {"squareRootButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Square root"},
        {"percentButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Percent"},
        {"negateButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Positive negative"},
        {"converterNegateButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Positive negative"},
        {"invertButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Reciprocal"},
        {"openParenthesisButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Left parenthesis"},
        {"Format_OpenParenthesisAutomationNamePrefix", "Left parenthesis, open parenthesis count %1"},
        {"closeParenthesisButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Right parenthesis"},
        {"Format_OpenParenthesisCountAutomationNamePrefix", "Open parenthesis count %1"},
        {"NoRightParenthesisAdded_Announcement", "There are no open parentheses to close."},
        {"ftoeButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scientific notation"},
        {"hyperbolicButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic function"},
        {"piButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Pi"},
        {"sinButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Sine"},
        {"cosButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Cosine"},
        {"tanButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Tangent"},
        {"sinhButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic sine"},
        {"coshButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic cosine"},
        {"tanhButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic tangent"},
        {"xpower2Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Square"},
        {"xpower3Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Cube"},
        {"invsinButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Arc sine"},
        {"invcosButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Arc cosine"},
        {"invtanButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Arc tangent"},
        {"invsinhButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic arc sine"},
        {"invcoshButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic arc cosine"},
        {"invtanhButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic arc tangent"},
        {"powerButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "'X' to the exponent"},
        {"powerOf10Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Ten to the exponent"},
        {"powerOfEButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "'e' to the exponent"},
        {"ySquareRootButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "'y' root of 'x'"},
        {"logBase10Button.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Log"},
        {"logBaseEButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Natural log"},
        {"modButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Modulo"},
        {"expButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Exponential"},
        {"dmsButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Degree minute second"},
        {"degreesButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Degrees"},
        {"intButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Integer part"},
        {"fractButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Fractional part"},
        {"factorialButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Factorial"},
        {"degButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Degrees toggle"},
        {"gradButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Gradians toggle"},
        {"radButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Radians toggle"},
        {"FlyoutNav.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Mode dropdown"},
        {"Categories.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Categories dropdown"},
        {"EnterAlwaysOnTopButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Keep on top"},
        {"ExitAlwaysOnTopButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Back to full view"},
        {"EnterAlwaysOnTopButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Keep on top (Alt+Up)"},
        {"ExitAlwaysOnTopButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Back to full view (Alt+Down)"},
        {"Format_ValueFrom", "Convert from %1 %2"},
        {"Format_ValueFrom_Decimal", "Convert from %1 point %2"},
        {"Format_ValueTo", "Converts into %1 %2"},
        {"Format_ConversionResult", "%1 %2 is %3 %4"},
        {"InputUnit_Name", "Input unit"},
        {"OutputUnit_Name", "Output unit"},
        {"CategoryName_AreaText", "Area"},
        {"CategoryName_DataText", "Data"},
        {"CategoryName_EnergyText", "Energy"},
        {"CategoryName_LengthText", "Length"},
        {"CategoryName_PowerText", "Power"},
        {"CategoryName_SpeedText", "Speed"},
        {"CategoryName_TimeText", "Time"},
        {"CategoryName_VolumeText", "Volume"},
        {"CategoryName_TemperatureText", "Temperature"},
        {"CategoryName_WeightText", "Weight and mass"},
        {"CategoryName_PressureText", "Pressure"},
        {"CategoryName_AngleText", "Angle"},
        {"CategoryName_CurrencyText", "Currency"},
        {"UnitName_FluidOunceUK", "Fluid ounces (UK)"},
        {"UnitAbbreviation_FluidOunceUK", "fl oz (UK)"},
        {"UnitName_FluidOunceUS", "Fluid ounces (US)"},
        {"UnitAbbreviation_FluidOunceUS", "fl oz (US)"},
        {"UnitName_GallonUK", "Gallons (UK)"},
        {"UnitAbbreviation_GallonUK", "gal (UK)"},
        {"UnitName_GallonUS", "Gallons (US)"},
        {"UnitAbbreviation_GallonUS", "gal (US)"},
        {"UnitName_Liter", "Liters"},
        {"UnitAbbreviation_Liter", "L"},
        {"UnitName_Milliliter", "Milliliters"},
        {"UnitAbbreviation_Milliliter", "mL"},
        {"UnitName_PintUK", "Pints (UK)"},
        {"UnitAbbreviation_PintUK", "pt (UK)"},
        {"UnitName_PintUS", "Pints (US)"},
        {"UnitAbbreviation_PintUS", "pt (US)"},
        {"UnitName_TablespoonUS", "Tablespoons (US)"},
        {"UnitAbbreviation_TablespoonUS", "tbsp. (US)"},
        {"UnitName_TeaspoonUS", "Teaspoons (US)"},
        {"UnitAbbreviation_TeaspoonUS", "tsp. (US)"},
        {"UnitName_TablespoonUK", "Tablespoons (UK)"},
        {"UnitAbbreviation_TablespoonUK", "tbsp. (UK)"},
        {"UnitName_TeaspoonUK", "Teaspoons (UK)"},
        {"UnitAbbreviation_TeaspoonUK", "tsp. (UK)"},
        {"UnitName_QuartUK", "Quarts (UK)"},
        {"UnitAbbreviation_QuartUK", "qt (UK)"},
        {"UnitName_QuartUS", "Quarts (US)"},
        {"UnitAbbreviation_QuartUS", "qt (US)"},
        {"UnitName_CupUS", "Cups (US)"},
        {"UnitAbbreviation_CupUS", "cup (US)"},
        {"UnitAbbreviation_Acre", "ac"},
        {"UnitAbbreviation_Bit", "b"},
        {"UnitAbbreviation_BritishThermalUnit", "BTU"},
        {"UnitAbbreviation_BTUPerMinute", "BTU/min"},
        {"UnitAbbreviation_Byte", "B"},
        {"UnitAbbreviation_Calorie", "cal"},
        {"UnitAbbreviation_Centimeter", "cm"},
        {"UnitAbbreviation_CentimetersPerSecond", "cm/s"},
        {"UnitAbbreviation_CubicCentimeter", "cm³"},
        {"UnitAbbreviation_CubicFoot", "ft³"},
        {"UnitAbbreviation_CubicInch", "in³"},
        {"UnitAbbreviation_CubicMeter", "m³"},
        {"UnitAbbreviation_CubicYard", "yd³"},
        {"UnitAbbreviation_Day", "d"},
        {"UnitAbbreviation_DegreesCelsius", "°C"},
        {"UnitAbbreviation_DegreesFahrenheit", "°F"},
        {"UnitAbbreviation_Electron-Volt", "eV"},
        {"UnitAbbreviation_Foot", "ft"},
        {"UnitAbbreviation_FeetPerSecond", "ft/s"},
        {"UnitAbbreviation_Foot-Pound", "ft•lb"},
        {"UnitAbbreviation_Gigabit", "Gb"},
        {"UnitAbbreviation_Gigabyte", "GB"},
        {"UnitAbbreviation_Hectare", "ha"},
        {"UnitAbbreviation_Horsepower", "hp (US)"},
        {"UnitAbbreviation_Hour", "hr"},
        {"UnitAbbreviation_Inch", "in"},
        {"UnitAbbreviation_Joule", "J"},
        {"UnitAbbreviation_Kilowatthour", "kWh"},
        {"UnitAbbreviation_Kelvin", "K"},
        {"UnitAbbreviation_Kilobit", "Kb"},
        {"UnitAbbreviation_Kilobyte", "KB"},
        {"UnitAbbreviation_Kilocalorie", "kcal"},
        {"UnitAbbreviation_Kilojoule", "kJ"},
        {"UnitAbbreviation_Kilometer", "km"},
        {"UnitAbbreviation_KilometersPerHour", "km/h"},
        {"UnitAbbreviation_Kilowatt", "kW"},
        {"UnitAbbreviation_Knot", "kn"},
        {"UnitAbbreviation_Mach", "M"},
        {"UnitAbbreviation_Megabit", "Mb"},
        {"UnitAbbreviation_Megabyte", "MB"},
        {"UnitAbbreviation_Meter", "m"},
        {"UnitAbbreviation_MetersPerSecond", "m/s"},
        {"UnitAbbreviation_Micron", "µm"},
        {"UnitAbbreviation_Microsecond", "µs"},
        {"UnitAbbreviation_Mile", "mi"},
        {"UnitAbbreviation_MilesPerHour", "mph"},
        {"UnitAbbreviation_Millimeter", "mm"},
        {"UnitAbbreviation_Millisecond", "ms"},
        {"UnitAbbreviation_Minute", "min"},
        {"UnitAbbreviation_Nanometer", "nm"},
        {"UnitAbbreviation_NauticalMile", "nmi"},
        {"UnitAbbreviation_Petabit", "Pb"},
        {"UnitAbbreviation_Petabyte", "PB"},
        {"UnitAbbreviation_Foot-PoundPerMinute", "ft•lb/min"},
        {"UnitAbbreviation_Second", "s"},
        {"UnitAbbreviation_SquareCentimeter", "cm²"},
        {"UnitAbbreviation_SquareFoot", "ft²"},
        {"UnitAbbreviation_SquareInch", "in²"},
        {"UnitAbbreviation_SquareKilometer", "km²"},
        {"UnitAbbreviation_SquareMeter", "m²"},
        {"UnitAbbreviation_SquareMile", "mi²"},
        {"UnitAbbreviation_SquareMillimeter", "mm²"},
        {"UnitAbbreviation_SquareYard", "yd²"},
        {"UnitAbbreviation_Terabit", "Tb"},
        {"UnitAbbreviation_Terabyte", "TB"},
        {"UnitAbbreviation_Watt", "W"},
        {"UnitAbbreviation_Week", "wk"},
        {"UnitAbbreviation_Yard", "yd"},
        {"UnitAbbreviation_Year", "yr"},
        {"UnitAbbreviation_Gibibits", "Gi"},
        {"UnitAbbreviation_Gibibytes", "GiB"},
        {"UnitAbbreviation_Kibibits", "Ki"},
        {"UnitAbbreviation_Kibibytes", "KiB"},
        {"UnitAbbreviation_Mebibits", "Mi"},
        {"UnitAbbreviation_Mebibytes", "MiB"},
        {"UnitAbbreviation_Nibble", "nybl"},
        {"UnitAbbreviation_Pebibits", "Pi"},
        {"UnitAbbreviation_Pebibytes", "PiB"},
        {"UnitAbbreviation_Tebibits", "Ti"},
        {"UnitAbbreviation_Tebibytes", "TiB"},
        {"UnitAbbreviation_Exabits", "E"},
        {"UnitAbbreviation_Exabytes", "EB"},
        {"UnitAbbreviation_Exbibits", "Ei"},
        {"UnitAbbreviation_Exbibytes", "EiB"},
        {"UnitAbbreviation_Zetabits", "Z"},
        {"UnitAbbreviation_Zetabytes", "ZB"},
        {"UnitAbbreviation_Zebibits", "Zi"},
        {"UnitAbbreviation_Zebibytes", "ZiB"},
        {"UnitAbbreviation_Yottabit", "Y"},
        {"UnitAbbreviation_Yottabyte", "YB"},
        {"UnitAbbreviation_Yobibits", "Yi"},
        {"UnitAbbreviation_Yobibytes", "YiB"},
        {"UnitName_Acre", "Acres"},
        {"UnitName_Bit", "Bits"},
        {"UnitName_BritishThermalUnit", "British thermal units"},
        {"UnitName_BTUPerMinute", "BTUs/minute"},
        {"UnitName_Byte", "Bytes"},
        {"UnitName_Calorie", "Thermal calories"},
        {"UnitName_Centimeter", "Centimeters"},
        {"UnitName_CentimetersPerSecond", "Centimeters per second"},
        {"UnitName_CubicCentimeter", "Cubic centimeters"},
        {"UnitName_CubicFoot", "Cubic feet"},
        {"UnitName_CubicInch", "Cubic inches"},
        {"UnitName_CubicMeter", "Cubic meters"},
        {"UnitName_CubicYard", "Cubic yards"},
        {"UnitName_Day", "Days"},
        {"UnitName_DegreesCelsius", "Celsius"},
        {"UnitName_DegreesFahrenheit", "Fahrenheit"},
        {"UnitName_Electron-Volt", "Electron volts"},
        {"UnitName_Foot", "Feet"},
        {"UnitName_FeetPerSecond", "Feet per second"},
        {"UnitName_Foot-Pound", "Foot-pounds"},
        {"UnitName_Foot-PoundPerMinute", "Foot-pounds/minute"},
        {"UnitName_Gigabit", "Gigabits"},
        {"UnitName_Gigabyte", "Gigabytes"},
        {"UnitName_Hectare", "Hectares"},
        {"UnitName_Horsepower", "Horsepower (US)"},
        {"UnitName_Hour", "Hours"},
        {"UnitName_Inch", "Inches"},
        {"UnitName_Joule", "Joules"},
        {"UnitName_Kilowatthour", "Kilowatt-hours"},
        {"UnitName_Kelvin", "Kelvin"},
        {"UnitName_Kilobit", "Kilobits"},
        {"UnitName_Kilobyte", "Kilobytes"},
        {"UnitName_Kilocalorie", "Food calories"},
        {"UnitName_Kilojoule", "Kilojoules"},
        {"UnitName_Kilometer", "Kilometers"},
        {"UnitName_KilometersPerHour", "Kilometers per hour"},
        {"UnitName_Kilowatt", "Kilowatts"},
        {"UnitName_Knot", "Knots"},
        {"UnitName_Mach", "Mach"},
        {"UnitName_Megabit", "Megabits"},
        {"UnitName_Megabyte", "Megabytes"},
        {"UnitName_Meter", "Meters"},
        {"UnitName_MetersPerSecond", "Meters per second"},
        {"UnitName_Micron", "Microns"},
        {"UnitName_Microsecond", "Microseconds"},
        {"UnitName_Mile", "Miles"},
        {"UnitName_MilesPerHour", "Miles per hour"},
        {"UnitName_Millimeter", "Millimeters"},
        {"UnitName_Millisecond", "Milliseconds"},
        {"UnitName_Minute", "Minutes"},
        {"UnitName_Nibble", "Nibble"},
        {"UnitName_Nanometer", "Nanometers"},
        {"UnitName_NauticalMile", "Nautical miles"},
        {"UnitName_Petabit", "Petabits"},
        {"UnitName_Petabyte", "Petabytes"},
        {"UnitName_Second", "Seconds"},
        {"UnitName_SquareCentimeter", "Square centimeters"},
        {"UnitName_SquareFoot", "Square feet"},
        {"UnitName_SquareInch", "Square inches"},
        {"UnitName_SquareKilometer", "Square kilometers"},
        {"UnitName_SquareMeter", "Square meters"},
        {"UnitName_SquareMile", "Square miles"},
        {"UnitName_SquareMillimeter", "Square millimeters"},
        {"UnitName_SquareYard", "Square yards"},
        {"UnitName_Terabit", "Terabits"},
        {"UnitName_Terabyte", "Terabytes"},
        {"UnitName_Watt", "Watts"},
        {"UnitName_Week", "Weeks"},
        {"UnitName_Yard", "Yards"},
        {"UnitName_Year", "Years"},
        {"UnitAbbreviation_Carat", "CD"},
        {"UnitAbbreviation_Degree", "deg"},
        {"UnitAbbreviation_Radian", "rad"},
        {"UnitAbbreviation_Gradian", "grad"},
        {"UnitAbbreviation_Atmosphere", "atm"},
        {"UnitAbbreviation_Bar", "ba"},
        {"UnitAbbreviation_KiloPascal", "kPa"},
        {"UnitAbbreviation_MillimeterOfMercury", "mmHg"},
        {"UnitAbbreviation_Pascal", "Pa"},
        {"UnitAbbreviation_PSI", "psi"},
        {"UnitAbbreviation_Centigram", "cg"},
        {"UnitAbbreviation_Decagram", "dag"},
        {"UnitAbbreviation_Decigram", "dg"},
        {"UnitAbbreviation_Gram", "g"},
        {"UnitAbbreviation_Hectogram", "hg"},
        {"UnitAbbreviation_Kilogram", "kg"},
        {"UnitAbbreviation_LongTon", "ton (UK)"},
        {"UnitAbbreviation_Milligram", "mg"},
        {"UnitAbbreviation_Ounce", "oz"},
        {"UnitAbbreviation_Pound", "lb"},
        {"UnitAbbreviation_ShortTon", "ton (US)"},
        {"UnitAbbreviation_Stone", "st"},
        {"UnitAbbreviation_Tonne", "t"},
        {"UnitName_Carat", "Carats"},
        {"UnitName_Degree", "Degrees"},
        {"UnitName_Radian", "Radians"},
        {"UnitName_Gradian", "Gradians"},
        {"UnitName_Atmosphere", "Atmospheres"},
        {"UnitName_Bar", "Bars"},
        {"UnitName_KiloPascal", "Kilopascals"},
        {"UnitName_MillimeterOfMercury", "Millimeters of mercury "},
        {"UnitName_Pascal", "Pascals"},
        {"UnitName_PSI", "Pounds per square inch"},
        {"UnitName_Centigram", "Centigrams"},
        {"UnitName_Decagram", "Dekagrams"},
        {"UnitName_Decigram", "Decigrams"},
        {"UnitName_Gram", "Grams"},
        {"UnitName_Hectogram", "Hectograms"},
        {"UnitName_Kilogram", "Kilograms"},
        {"UnitName_LongTon", "Long tons (UK)"},
        {"UnitName_Milligram", "Milligrams"},
        {"UnitName_Ounce", "Ounces"},
        {"UnitName_Pound", "Pounds"},
        {"UnitName_ShortTon", "Short tons (US)"},
        {"UnitName_Stone", "Stone"},
        {"UnitName_Tonne", "Metric tonnes"},
        {"UnitName_CD", "CDs"},
        {"UnitAbbreviation_CD", "CDs"},
        {"UnitName_SoccerField", "soccer fields"},
        {"UnitAbbreviation_SoccerField", "soccer fields"},
        {"UnitName_FloppyDisk", "floppy disks"},
        {"UnitAbbreviation_FloppyDisk", "floppy disks"},
        {"UnitName_DVD", "DVDs"},
        {"UnitAbbreviation_DVD", "DVDs"},
        {"UnitName_Battery", "batteries"},
        {"UnitAbbreviation_Battery", "batteries"},
        {"UnitName_Paperclip", "paperclips"},
        {"UnitAbbreviation_Paperclip", "paperclips"},
        {"UnitName_JumboJet", "jumbo jets"},
        {"UnitAbbreviation_JumboJet", "jumbo jets"},
        {"UnitName_LightBulb", "light bulbs"},
        {"UnitAbbreviation_LightBulb", "light bulbs"},
        {"UnitName_Horse", "horses"},
        {"UnitAbbreviation_Horse", "horses"},
        {"UnitName_Bathtub", "bathtubs"},
        {"UnitAbbreviation_Bathtub", "bathtubs"},
        {"UnitName_Snowflake", "snowflakes"},
        {"UnitAbbreviation_Snowflake", "snowflakes"},
        {"UnitName_Elephant", "elephants"},
        {"UnitAbbreviation_Elephant", "elephants"},
        {"UnitName_Turtle", "turtles"},
        {"UnitAbbreviation_Turtle", "turtles"},
        {"UnitName_Jet", "jets"},
        {"UnitAbbreviation_Jet", "jets"},
        {"UnitName_Whale", "whales"},
        {"UnitAbbreviation_Whale", "whales"},
        {"UnitName_CoffeeCup", "coffee cups"},
        {"UnitAbbreviation_CoffeeCup", "coffee cups"},
        {"UnitName_SwimmingPool", "swimming pools"},
        {"UnitAbbreviation_SwimmingPool", "swimming pools"},
        {"UnitName_Hand", "hands"},
        {"UnitAbbreviation_Hand", "hands"},
        {"UnitName_Paper", "sheets of paper"},
        {"UnitAbbreviation_Paper", "sheets of paper"},
        {"UnitName_Castle", "castles"},
        {"UnitAbbreviation_Castle", "castles"},
        {"UnitName_Banana", "bananas"},
        {"UnitAbbreviation_Banana", "bananas"},
        {"UnitName_SliceOfCake", "slices of cake"},
        {"UnitAbbreviation_SliceOfCake", "slices of cake"},
        {"UnitName_TrainEngine", "train engines"},
        {"UnitAbbreviation_TrainEngine", "train engines"},
        {"UnitName_SoccerBall", "soccer balls"},
        {"UnitAbbreviation_SoccerBall", "soccer balls"},
        {"degButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F4"},
        {"radButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F5"},
        {"gradButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F3"},
        {"MemoryItemHelpText", "Memory item"},
        {"SupplementaryUnit_AutomationName", "%1 %2"},
        {"AboutControlBackButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Back"},
        {"AboutControlBackButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Back"},
        {"AboutEULA.Text", "Microsoft Software License Terms"},
        {"PreviewTag.Text", "Preview"},
        {"AboutControlPrivacyStatement.Text", "Microsoft Privacy Statement"},
        {"AboutControlCopyright", "© %1 Microsoft. All rights reserved."},
        {"AboutControlContribute", "To learn how you can contribute to Windows Calculator, check out the project on %HL%GitHub%HL%."},
        {"AboutGroupTitle.Text", "About"},
        {"FeedbackButton.Content", "Send feedback"},
        {"LocalizedFontFamilyOverride", "RESERVED_FOR_FONTLOC"},
        {"LocalizedFontWeightOverride", "RESERVED_FOR_FONTLOC"},
        {"LocalizedUICaptionFontSizeFactorOverride", "RESERVED_FOR_FONTLOC"},
        {"LocalizedUITextFontSizeFactorOverride", "RESERVED_FOR_FONTLOC"},
        {"Bin", "BIN"},
        {"Dec", "DEC"},
        {"Hex", "HEX"},
        {"Oct", "OCT"},
        {"HistoryEmpty.Text", "There’s no history yet."},
        {"MemoryPaneEmpty.Text", "There’s nothing saved in memory."},
        {"MemoryFlyout.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Memory"},
        {"CannotPaste", "This expression cannot be pasted"},
        {"wordButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F4"},
        {"qwordButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F2"},
        {"byteButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F12"},
        {"dwordButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "F3"},
        {"UnitName_Gibibits", "Gibibits"},
        {"UnitName_Gibibytes", "Gibibytes"},
        {"UnitName_Kibibits", "Kibibits"},
        {"UnitName_Kibibytes", "Kibibytes"},
        {"UnitName_Mebibits", "Mebibits"},
        {"UnitName_Mebibytes", "Mebibytes"},
        {"UnitName_Pebibits", "Pebibits"},
        {"UnitName_Pebibytes", "Pebibytes"},
        {"UnitName_Tebibits", "Tebibits"},
        {"UnitName_Tebibytes", "Tebibytes"},
        {"UnitName_Exabits", "Exabits"},
        {"UnitName_Exabytes", "Exabytes"},
        {"UnitName_Exbibits", "Exbibits"},
        {"UnitName_Exbibytes", "Exbibytes"},
        {"UnitName_Zetabits", "Zetabits"},
        {"UnitName_Zetabytes", "Zetabytes"},
        {"UnitName_Zebibits", "Zebibits"},
        {"UnitName_Zebibytes", "Zebibytes"},
        {"UnitName_Yottabit", "Yottabits"},
        {"UnitName_Yottabyte", "Yottabytes"},
        {"UnitName_Yobibits", "Yobibits"},
        {"UnitName_Yobibytes", "Yobibytes"},
        {"DateCalculationModeText", "Date calculation"},
        {"DateCalculationOption.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Calculation mode"},
        {"AddOption.Content", "Add"},
        {"Date_AddSubtractOption.Content", "Add or subtract days"},
        {"DateLabel.Text", "Date"},
        {"Date_DifferenceOption.Content", "Difference between dates"},
        {"DaysLabel.Text", "Days"},
        {"Date_DifferenceLabel.Text", "Difference"},
        {"DateDiff_FromHeader.Header", "From"},
        {"MonthsLabel.Text", "Months"},
        {"SubtractOption.Content", "Subtract"},
        {"DateDiff_ToHeader.Header", "To"},
        {"YearsLabel.Text", "Years"},
        {"Date_OutOfBoundMessage", "Date out of Bound"},
        {"Date_Day", "day"},
        {"Date_Days", "days"},
        {"Date_Month", "month"},
        {"Date_Months", "months"},
        {"Date_SameDates", "Same dates"},
        {"Date_Week", "week"},
        {"Date_Weeks", "weeks"},
        {"Date_Year", "year"},
        {"Date_Years", "years"},
        {"Date_DifferenceResultAutomationName", "Difference %1"},
        {"Date_ResultingDateAutomationName", "Resulting date %1"},
        {"HeaderAutomationName_Calculator", "%1 Calculator mode"},
        {"HeaderAutomationName_Converter", "%1 Converter mode"},
        {"HeaderAutomationName_Date", "Date calculation mode"},
        {"DockPanel.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "History and Memory lists"},
        {"MemoryPanel.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Memory controls"},
        {"StandardFunctions.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Standard functions"},
        {"DisplayControls.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Display controls"},
        {"StandardOperators.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Standard operators"},
        {"NumberPad.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Number pad"},
        {"ScientificAngleOperators.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Angle operators"},
        {"ScientificFunctions.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scientific functions"},
        {"RadixGroup.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Radix selection"},
        {"ProgrammerOperators.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Programmer operators"},
        {"InputModeSelectionGroup.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Input mode selection"},
        {"BitFlipPanel.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Bit toggling keypad"},
        {"scrollLeft.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scroll expression left"},
        {"scrollRight.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scroll expression right"},
        {"Format_MaxDigitsReached", "Max digits reached. %1"},
        {"Format_ButtonPressAuditoryFeedback", "%1 %2"},
        {"Format_MemorySave", "%1 saved to memory"},
        {"Format_MemorySlotChanged", "Memory slot %1 is %2"},
        {"Format_MemorySlotCleared", "Memory slot %1 cleared"},
        {"divideButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "divided by"},
        {"multiplyButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "times"},
        {"minusButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "minus"},
        {"plusButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "plus"},
        {"powerButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "to the power of"},
        {"ySquareRootButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "y root"},
        {"modButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "mod"},
        {"lshButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "left shift"},
        {"rshButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "right shift"},
        {"orButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "or"},
        {"xorButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "x or"},
        {"andButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "and"},
        {"CurrencyFromToRatioFormat", "%1 %2 = %3 %4"},
        {"CurrencyTimestampFormat", "Updated %1 %2"},
        {"RefreshButtonText.Content", "Update rates"},
        {"DataChargesMayApply", "Data charges may apply."},
        {"FailedToRefresh", "Couldn’t get new rates. Try again later."},
        {"OfflineStatusHyperlinkText", "Offline. Please check your%HL%Network Settings%HL%"},
        {"UpdatingCurrencyRates", "Updating currency rates"},
        {"CurrencyRatesUpdated", "Currency rates updated"},
        {"CurrencyRatesUpdateFailed", "Could not update rates"},
        {"HistoryButton.AccessKey", "I"},
        {"MemoryButton.AccessKey", "M"},
        {"NavView.AccessKey", "H"},
        {"CategoryName_AngleAccessKey", "AN"},
        {"CategoryName_AreaAccessKey", "AR"},
        {"CategoryName_CurrencyAccessKey", "C"},
        {"CategoryName_DataAccessKey", "D"},
        {"CategoryName_EnergyAccessKey", "E"},
        {"CategoryName_LengthAccessKey", "L"},
        {"CategoryName_PowerAccessKey", "PO"},
        {"CategoryName_PressureAccessKey", "PR"},
        {"CategoryName_SpeedAccessKey", "S"},
        {"CategoryName_TimeAccessKey", "TI"},
        {"CategoryName_VolumeAccessKey", "V"},
        {"CategoryName_WeightAccessKey", "W"},
        {"CategoryName_TemperatureAccessKey", "TE"},
        {"ClearHistory.AccessKey", "C"},
        {"ClearMemory.AccessKey", "C"},
        {"ClearMemory.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Clear all memory (Ctrl+L)"},
        {"ClearMemory.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Clear all memory"},
        {"HistoryLabel.AccessKey", "I"},
        {"MemoryLabel.AccessKey", "M"},
        {"SineDegrees", "sine degrees"},
        {"SineRadians", "sine radians"},
        {"SineGradians", "sine gradians"},
        {"InverseSineDegrees", "inverse sine degrees"},
        {"InverseSineRadians", "inverse sine radians"},
        {"InverseSineGradians", "inverse sine gradians"},
        {"HyperbolicSine", "hyperbolic sine"},
        {"InverseHyperbolicSine", "inverse hyperbolic sine"},
        {"CosineDegrees", "cosine degrees"},
        {"CosineRadians", "cosine radians"},
        {"CosineGradians", "cosine gradians"},
        {"InverseCosineDegrees", "inverse cosine degrees"},
        {"InverseCosineRadians", "inverse cosine radians"},
        {"InverseCosineGradians", "inverse cosine gradians"},
        {"HyperbolicCosine", "hyperbolic cosine"},
        {"InverseHyperbolicCosine", "inverse hyperbolic cosine"},
        {"TangentDegrees", "tangent degrees"},
        {"TangentRadians", "tangent radians"},
        {"TangentGradians", "tangent gradians"},
        {"InverseTangentDegrees", "inverse tangent degrees"},
        {"InverseTangentRadians", "inverse tangent radians"},
        {"InverseTangentGradians", "inverse tangent gradians"},
        {"HyperbolicTangent", "hyperbolic tangent"},
        {"InverseHyperbolicTangent", "inverse hyperbolic tangent"},
        {"SecantDegrees", "secant degrees"},
        {"SecantRadians", "secant radians"},
        {"SecantGradians", "secant gradians"},
        {"InverseSecantDegrees", "inverse secant degrees"},
        {"InverseSecantRadians", "inverse secant radians"},
        {"InverseSecantGradians", "inverse secant gradians"},
        {"HyperbolicSecant", "hyperbolic secant"},
        {"InverseHyperbolicSecant", "inverse hyperbolic secant"},
        {"CosecantDegrees", "cosecant degrees"},
        {"CosecantRadians", "cosecant radians"},
        {"CosecantGradians", "cosecant gradians"},
        {"InverseCosecantDegrees", "inverse cosecant degrees"},
        {"InverseCosecantRadians", "inverse cosecant radians"},
        {"InverseCosecantGradians", "inverse cosecant gradians"},
        {"HyperbolicCosecant", "hyperbolic cosecant"},
        {"InverseHyperbolicCosecant", "inverse hyperbolic cosecant"},
        {"CotangentDegrees", "cotangent degrees"},
        {"CotangentRadians", "Cotangent radians"},
        {"CotangentGradians", "cotangent gradians"},
        {"InverseCotangentDegrees", "inverse cotangent degrees"},
        {"InverseCotangentRadians", "inverse cotangent radians"},
        {"InverseCotangentGradians", "inverse cotangent gradians"},
        {"HyperbolicCotangent", "hyperbolic cotangent"},
        {"InverseHyperbolicCotangent", "inverse hyperbolic cotangent"},
        {"CubeRoot", "cuberoot"},
        {"Logy", "Log base"},
        {"AbsoluteValue", "Absolute value"},
        {"LeftShift", "left shift"},
        {"RightShift", "right shift"},
        {"Factorial", "factorial"},
        {"DegreeMinuteSecond", "degree minute second"},
        {"NaturalLog", "natural log"},
        {"Square", "square"},
        {"YRoot", "y root"},
        {"NavCategoryItem_AutomationNameFormat", "%1 %2"},
        {"NavCategoryHeader_AutomationNameFormat", "%1 category"},
        {"AboutControlServicesAgreement.Text", "Microsoft Services Agreement"},
        {"UnitAbbreviation_Pyeong", "Pyeong"},
        {"UnitName_Pyeong", "Pyeong"},
        {"AddSubtract_Date_FromHeader.Header", "From"},
        {"CalculationResultScrollLeft.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scroll calculation result left"},
        {"CalculationResultScrollRight.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scroll calculation result right"},
        {"CalculationFailed", "Calculation failed"},
        {"logBaseY.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Log base Y"},
        {"logBaseY.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "L"},
        {"trigButton.Text", "Trigonometry"},
        {"funcButton.Text", "Function"},
        {"inequalityButton.Text", "Inequalities"},
        {"inequalityButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Inequalities"},
        {"bitwiseButton.Text", "Bitwise"},
        {"bitShiftButton.Text", "Bit shift"},
        {"trigShiftButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Inverse function"},
        {"hypButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic function"},
        {"secButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Secant"},
        {"secButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "U"},
        {"sechButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic secant"},
        {"sechButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "U"},
        {"invsecButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Arc secant"},
        {"invsecButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "U"},
        {"invsechButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic arc secant"},
        {"invsechButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlShiftChord", "U"},
        {"cscButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Cosecant"},
        {"cscButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "I"},
        {"cschButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic cosecant"},
        {"cschButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "I"},
        {"invcscButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Arc cosecant"},
        {"invcscButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "I"},
        {"invcschButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic arc cosecant"},
        {"invcschButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlShiftChord", "I"},
        {"cotButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Cotangent"},
        {"cotButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "J"},
        {"cothButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic cotangent"},
        {"cothButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "J"},
        {"invcotButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Arc cotangent"},
        {"invcotButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "J"},
        {"invcothButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Hyperbolic arc cotangent"},
        {"invcothButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlShiftChord", "J"},
        {"floorButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Floor"},
        {"floorButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "["},
        {"ceilButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Ceiling"},
        {"ceilButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "]"},
        {"randButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Random"},
        {"randButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "R"},
        {"absButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Absolute value"},
        {"absButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "|"},
        {"eulerButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Euler's number"},
        {"eulerButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyShiftChord", "E"},
        {"twoPowerXButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Two to the exponent"},
        {"twoPowerXButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "G"},
        {"nandButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Nand"},
        {"nandButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "."},
        {"nandButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "Nand"},
        {"norButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Nor"},
        {"norButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "\\"},
        {"norButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "Nor"},
        {"rolCarryButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Rotate on left with carry"},
        {"rolCarryButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "<"},
        {"rorCarryButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Rotate on right with carry"},
        {"rorCarryButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", ">"},
        {"lshLogicalButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Left shift"},
        {"lshLogicalButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "<"},
        {"lshLogicalButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "Left shift"},
        {"rshLogicalButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Right shift"},
        {"rshLogicalButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", ">"},
        {"rshLogicalButton.[using:CalculatorApp.Controls]CalculatorButton.AuditoryFeedback", "Right shift"},
        {"arithmeticShiftButton.Content", "Arithmetic shift"},
        {"logicalShiftButton.Content", "Logical shift"},
        {"rotateCircularButton.Content", "Rotate circular shift"},
        {"rotateCarryShiftButton.Content", "Rotate through carry circular shift"},
        {"cubeRootButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Cube root"},
        {"cubeRootButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "B"},
        {"trigButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Trigonometry"},
        {"funcButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Functions"},
        {"bitwiseButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Bitwise"},
        {"bitShiftButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Bitshift"},
        {"ScientificOperatorPanel.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Scientific operator panels"},
        {"ProgrammerOperatorPanel.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Programmer operator panels"},
        {"MostSignificantBit", "most significant bit"},
        {"GraphingCalculatorModeText", "Graphing"},
        {"plotButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Enter"},
        {"plotButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Plot"},
        {"xButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "X"},
        {"yButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKey", "Y"},
        {"graphingPowerButton.[using:CalculatorApp.Common]KeyboardShortcutManager.Character", "^"},
        {"graphViewButton.[using:CalculatorApp.Common]KeyboardShortcutManager.VirtualKeyControlChord", "Home"},
        {"graphViewButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Refresh view automatically (Ctrl + 0)"},
        {"graphViewButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Graph view"},
        {"GraphViewAutomaticBestFitAnnouncement", "Automatic best fit"},
        {"GraphViewManualAdjustmentAnnouncement", "Manual adjustment"},
        {"GridResetAnnouncement", "Graph view has been reset"},
        {"zoomInButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Zoom in (Ctrl + plus)"},
        {"zoomInButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Zoom in"},
        {"zoomOutButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Zoom out (Ctrl + minus)"},
        {"zoomOutButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Zoom out"},
        {"EquationTextBoxAddPanel.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Add equation"},
        {"ShareActionErrorMessage", "Unable to share at this time."},
        {"ShareActionErrorOk", "OK"},
        {"ShareActionTitle", "Look what I graphed with Windows Calculator"},
        {"EquationsShareHeader", "Equations"},
        {"VariablesShareHeader", "Variables"},
        {"GraphImageAltText", "Image of a graph with equations"},
        {"VaiablesHeader.Text", "Variables"},
        {"StepTextBlock.Text", "Step"},
        {"MinTextBlock.Text", "Min"},
        {"MaxTextBlock.Text", "Max"},
        {"LineColorText.Text", "Color"},
        {"StyleChooserBoxHeading.Text", "Style"},
        {"KeyGraphFeaturesLabel.Text", "Function analysis"},
        {"KGFHorizontalAsymptotesNone", "The function does not have any horizontal asymptotes."},
        {"KGFInflectionPointsNone", "The function does not have any inflection points."},
        {"KGFMaximaNone", "The function does not have any maxima points."},
        {"KGFMinimaNone", "The function does not have any minima points."},
        {"KGFMonotonicityConstant", "Constant"},
        {"KGFMonotonicityDecreasing", "Decreasing"},
        {"KGFMonotonicityError", "Unable to determine the monotonicity of the function."},
        {"KGFMonotonicityIncreasing", "Increasing"},
        {"KGFMonotonicityUnknown", "The monotonicity of the function is unknown."},
        {"KGFObliqueAsymptotesNone", "The function does not have any oblique aysmptotes."},
        {"KGFParityError", "Unable to determine the parity of the function."},
        {"KGFParityEven", "The function is even."},
        {"KGFParityNeither", "The function is neither even nor odd."},
        {"KGFParityOdd", "The function is odd."},
        {"KGFParityUnknown", "The function parity is unknown."},
        {"KGFPeriodicityError", "Periodicity is not supported for this function."},
        {"KGFPeriodicityNotPeriodic", "The function is not periodic."},
        {"KGFPeriodicityUnknown", "The function periodicity is unknown."},
        {"KGFTooComplexFeaturesError", "These features are too complex for Calculator to calculate:"},
        {"KGFVerticalAsymptotesNone", "The function does not have any vertical asymptotes."},
        {"KGFXInterceptNone", "The function does not have any x-intercepts."},
        {"KGFYInterceptNone", "The function does not have any y-intercepts."},
        {"Domain", "Domain"},
        {"HorizontalAsymptotes", "Horizontal asymptotes"},
        {"InflectionPoints", "Inflection points"},
        {"KGFAnalysisNotSupported", "Analysis is not supported for this function."},
        {"KGFVariableIsNotX", "Analysis is only supported for functions in the f(x) format. Example: y=x"},
        {"Maxima", "Maxima"},
        {"Minima", "Minima"},
        {"Monotonicity", "Monotonicity"},
        {"ObliqueAsymptotes", "Oblique asymptotes"},
        {"Parity", "Parity"},
        {"Periodicity", "Period"},
        {"Range", "Range"},
        {"VerticalAsymptotes", "Vertical asymptotes"},
        {"XIntercept", "X-Intercept"},
        {"YIntercept", "Y-Intercept"},
        {"KGFAnalysisCouldNotBePerformed", "Analysis could not be performed for the function."},
        {"KGFDomainNone", "Unable to calculate the domain for this function."},
        {"KGFRangeNone", "Unable to calculate the range for this function."},
        {"Overflow", "Overflow (the number is too large)"},
        {"RequireRadiansMode", "Radians mode is required to graph this equation."},
        {"TooComplexToSolve", "This function is too complex to graph"},
        {"RequireDegreesMode", "Degrees mode is required to graph this function"},
        {"FactorialInvalidArgument", "The factorial function has an invalid argument"},
        {"FactorialCannotPerformOnLargeNumber", "The factorial function has an argument that is too large to graph"},
        {"ModuloCannotPerformOnFloat", "Modulo can only be used with whole numbers"},
        {"EquationHasNoSolution", "The equation has no solution"},
        {"DivideByZero", "Cannot divide by zero"},
        {"MutuallyExclusiveConditions", "The equation contains logical conditions that are mutually exclusive"},
        {"OutOfDomain", "Equation is out of domain"},
        {"GE_NotSupported", "Graphing this equation is not supported"},
        {"ParenthesisMismatch", "The equation is missing an opening parenthesis"},
        {"UnmatchedParenthesis", "The equation is missing a closing parenthesis"},
        {"TooManyDecimalPoints", "There are too many decimal points in a number"},
        {"DecimalPointWithoutDigits", "A decimal point is missing digits"},
        {"UnexpectedEndOfExpression", "Unexpected end of expression"},
        {"UnexpectedToken", "Unexpected characters in the expression"},
        {"InvalidToken", "Invalid characters in the expression"},
        {"TooManyEquals", "There are too many equal signs"},
        {"EqualWithoutGraphVariable", "The function must contain at least one x or y variable"},
        {"InvalidEquationSyntax", "Invalid expression"},
        {"EmptyExpression", "The expression is empty"},
        {"EqualWithoutEquation", "Equal was used without an equation"},
        {"ExpectParenthesisAfterFunctionName", "Parenthesis missing after function name"},
        {"IncorrectNumParameter", "A mathematical operation has the incorrect number of parameters"},
        {"InvalidVariableNameFormat", "A variable name is invalid"},
        {"BracketMismatch", "The equation is missing an opening bracket"},
        {"UnmatchedBracket", "The equation is missing a closing bracket"},
        {"CannotUseIInReal", "\"i\" and \"I\" cannot be used as variable names"},
        {"GeneralError", "The equation could not be graphed"},
        {"InvalidNumberDigit", "The digit could not be resolved for the given base"},
        {"InvalidNumberBase", "The base must be greater than 2 and less than 36"},
        {"InvalidVariableSpecification", "A mathematical operation requires one of its parameters to be a variable"},
        {"ExpectingLogicalOperands", "Equation is mixing logical and scalar operands"},
        {"CannotUseIndexVarInOpLimits", "x or y cannot be used in the upper or lower limits"},
        {"CannotUseIndexVarInLimPoint", "x or y cannot be used in the limit point"},
        {"CannotUseComplexInfinityInReal", "Cannot use complex infinity"},
        {"CannotUseIInInequalitySolving", "Cannot use complex numbers in inequalities"},
        {"equationAnalysisBack.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Back to function list"},
        {"equationAnalysisBack.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Back to function list"},
        {"functionAnalysisButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Analyze function"},
        {"functionAnalysisButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Analyze function"},
        {"functionAnalysisMenuItem", "Analyze function"},
        {"removeButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Remove equation"},
        {"removeButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Remove equation"},
        {"removeMenuItem", "Remove equation"},
        {"shareButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Share"},
        {"shareButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Share"},
        {"colorChooserButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Change equation style"},
        {"colorChooserButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Change equation style"},
        {"colorChooserMenuItem", "Change equation style"},
        {"showEquationButtonToolTip", "Show equation"},
        {"hideEquationButtonToolTip", "Hide equation"},
        {"showEquationButtonAutomationName", "Show equation %1"},
        {"hideEquationButtonAutomationName", "Hide equation %1"},
        {"disableTracingButtonToolTip", "Stop tracing"},
        {"enableTracingButtonToolTip", "Start tracing"},
        {"graphAutomationName", "Graph viewing window, x-axis bounded by %1 and %2, y-axis bounded by %3 and %4, displaying %5 equations"},
        {"sliderOptionsButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Configure slider"},
        {"sliderOptionsButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Configure slider"},
        {"GraphSwitchToEquationMode", "Switch to equation mode"},
        {"GraphSwitchToGraphMode", "Switch to graph mode"},
        {"SwitchModeToggleButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Switch to equation mode"},
        {"GraphSwitchedToEquationModeAnnouncement", "Current mode is equation mode"},
        {"GraphSwitchedToGraphModeAnnouncement", "Current mode is graph mode"},
        {"GridHeading.Text", "Window"},
        {"TrigModeDegrees.Content", "Degrees"},
        {"TrigModeGradians.Content", "Gradians"},
        {"TrigModeRadians.Content", "Radians"},
        {"UnitsHeading.Text", "Units"},
        {"ResetViewButton.Content", "Reset view"},
        {"GraphSettingsXMax.Header", "X-Max"},
        {"GraphSettingsXMin.Header", "X-Min"},
        {"GraphSettingsYMax.Header", "Y-Max"},
        {"GraphSettingsYMin.Header", "Y-Min"},
        {"graphSettingsButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Graph options"},
        {"graphSettingsButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Graph options"},
        {"GraphOptionsHeading.Text", "Graph options"},
        {"VariableAreaSettings.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable options"},
        {"VariableAreaSettings.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", "Toggle variable options"},
        {"LineThicknessBoxHeading.Text", "Line thickness"},
        {"LineOptionsHeading.Text", "Line options"},
        {"SmallLineWidthAutomationName", "Small line width"},
        {"MediumLineWidthAutomationName", "Medium line width"},
        {"LargeLineWidthAutomationName", "Large line width"},
        {"ExtraLargeLineWidthAutomationName", "Extra large line width"},
        {"mathRichEditBox.PlaceholderText", "Enter an expression"},
        {"GraphCopyMenuItem.Text", "Copy"},
        {"cutEquationMenuItem.Text", "Cut"},
        {"copyEquationMenuItem.Text", "Copy"},
        {"pasteEquationMenuItem.Text", "Paste"},
        {"undoEquationMenuItem.Text", "Undo"},
        {"selectAllEquationMenuItem.Text", "Select all"},
        {"EquationInputButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Function input"},
        {"EquationInputList.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Function input"},
        {"EquationInputPanel.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Function input panel"},
        {"VariableStackPanel.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable panel"},
        {"VariableListView.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable list"},
        {"VariableListViewItem", "Variable %1 list item"},
        {"VariableValueTextBox.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable value textbox"},
        {"VariableValueSlider.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable value slider"},
        {"VariableMinTextBox.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable minimum value textbox"},
        {"VariableStepTextBox.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable step value textbox"},
        {"VariableMaxTextBox.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Variable maximum value textbox"},
        {"solidLineStyleAutomationName", "Solid line style"},
        {"dotLineStyleAutomationName", "Dot line style"},
        {"dashLineStyleAutomationName", "Dash line style"},
        {"equationColor1AutomationName", "Navy blue"},
        {"equationColor2AutomationName", "Seafoam"},
        {"equationColor3AutomationName", "Violet"},
        {"equationColor4AutomationName", "Green"},
        {"equationColor5AutomationName", "Mint green"},
        {"equationColor6AutomationName", "Dark green"},
        {"equationColor7AutomationName", "Charcoal"},
        {"equationColor8AutomationName", "Red"},
        {"equationColor9AutomationName", "Plum light"},
        {"equationColor10AutomationName", "Magenta"},
        {"equationColor11AutomationName", "Yellow gold"},
        {"equationColor12AutomationName", "Orange bright"},
        {"equationColor13AutomationName", "Brown"},
        {"equationColor14BlackAutomationName", "Black"},
        {"equationColor14WhiteAutomationName", "White"},
        {"equationHighContrastColor1AutomationName", "Color 1"},
        {"equationHighContrastColor2AutomationName", "Color 2"},
        {"equationHighContrastColor3AutomationName", "Color 3"},
        {"equationHighContrastColor4AutomationName", "Color 4"},
        {"GraphThemeHeading.Text", "Graph theme"},
        {"AlwaysLightTheme.Content", "Always light"},
        {"MatchAppTheme.Content", "Match app theme"},
        {"GraphThemeHeading.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Theme"},
        {"AlwaysLightTheme.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Always light"},
        {"MatchAppTheme.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Match app theme"},
        {"FunctionRemovedAnnouncement", "Function removed"},
        {"KGFEquationTextBox.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Function analysis equation box"},
        {"graphingEqualButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Equals"},
        {"lessThanFlyoutButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Less than"},
        {"lessThanOrEqualFlyoutButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Less than or equal"},
        {"equalsFlyoutButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Equal"},
        {"greaterThanOrEqualFlyoutButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Greater than or equal"},
        {"greaterThanFlyoutButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Greater than"},
        {"xButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "X"},
        {"yButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Y"},
        {"submitButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Submit"},
        {"FunctionAnalysisGrid.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Function analysis"},
        {"GraphSettingsGrid.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Graph options"},
        {"DockPanel_HistoryMemoryLists", "History and Memory lists"},
        {"DockPanel_MemoryList", "Memory list"},
        {"Format_HistorySlotCleared", "History slot %1 cleared"},
        {"CalcAlwaysOnTop", "Calculator always on top"},
        {"CalcBackToFullView", "Calculator back to full view"},
        {"arithmeticShiftButtonSelected", "Arithmetic shift selected"},
        {"logicalShiftButtonSelected", "Logical shift selected"},
        {"rotateCircularButtonSelected", "Rotate circular shift selected"},
        {"rotateCarryShiftButtonSelected", "Rotate through carry circular shift selected"},
        {"SettingsHeader.Text", "Settings"},
        {"SettingsAppearance.Text", "Appearance"},
        {"AppThemeExpander.Header", "App theme"},
        {"AppThemeExpander.Description", "Select which app theme to display"},
        {"LightThemeRadioButton.Content", "Light"},
        {"DarkThemeRadioButton.Content", "Dark"},
        {"SystemThemeRadioButton.Content", "Use system setting"},
        {"TitleBarBackButton.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Back"},
        {"SettingsPageOpenedAnnouncement", "Settings page"},
        {"MathRichEditBox.[using:Windows.UI.Xaml.Automation]AutomationProperties.Name", "Open the context menu for available actions"},
        {"ErrorButtonOk", "OK"},
        {"SnapshotRestoreError", "Couldn't restore this snapshot."},
        {"100", "Invalid input"},
        {"101", "Result is undefined"},
        {"105", "Not enough memory"},
        {"107", "Overflow"},
        {"108", "Result not defined"},
        {"118", "Result not defined"},
        {"119", "Overflow"},
        {"120", "Overflow"},
        {"66", "frac"},
        {"67", "sin₀"},
        {"68", "cos₀"},
        {"69", "tan₀"},
        {"70", "sin₀⁻¹"},
        {"71", "cos₀⁻¹"},
        {"72", "tan₀⁻¹"},
        {"73", "sinᵣ"},
        {"74", "cosᵣ"},
        {"75", "tanᵣ"},
        {"76", "sinᵣ⁻¹"},
        {"77", "cosᵣ⁻¹"},
        {"78", "tanᵣ⁻¹"},
        {"79", "sin₉"},
        {"80", "cos₉"},
        {"81", "tan₉"},
        {"82", "sin₉⁻¹"},
        {"83", "cos₉⁻¹"},
        {"84", "tan₉⁻¹"},
        {"85", "sinh⁻¹"},
        {"86", "cosh⁻¹"},
        {"87", "tanh⁻¹"},
        {"88", "e^"},
        {"89", "10^"},
        {"90", "√"},
        {"91", "sqr"},
        {"92", "cube"},
        {"94", "fact"},
        {"95", "1/"},
        {"96", "degrees"},
        {"97", "negate"},
        {"99", "Cannot divide by zero"},
        {"SecDeg", "sec₀"},
        {"SecRad", "secᵣ"},
        {"SecGrad", "sec₉"},
        {"InverseSecDeg", "sec₀⁻¹"},
        {"InverseSecRad", "secᵣ⁻¹"},
        {"InverseSecGrad", "sec₉⁻¹"},
        {"CscDeg", "csc₀"},
        {"CscRad", "cscᵣ"},
        {"CscGrad", "csc₉"},
        {"InverseCscDeg", "csc₀⁻¹"},
        {"InverseCscRad", "cscᵣ⁻¹"},
        {"InverseCscGrad", "csc₉⁻¹"},
        {"CotDeg", "cot₀"},
        {"CotRad", "cotᵣ"},
        {"CotGrad", "cot₉"},
        {"InverseCotDeg", "cot₀⁻¹"},
        {"InverseCotRad", "cotᵣ⁻¹"},
        {"InverseCotGrad", "cot₉⁻¹"},
        {"Sech", "sech"},
        {"InverseSech", "sech⁻¹"},
        {"Csch", "csch"},
        {"InverseCsch", "csch⁻¹"},
        {"Coth", "coth"},
        {"InverseCoth", "coth⁻¹"},
        {"TwoPowX", "2^"},
        {"LogBaseY", "log base"},
        {"Abs", "abs"},
        {"Ceil", "ceil"},
        {"Floor", "floor"},
        {"Nand", "NAND"},
        {"Nor", "NOR"},
        {"ProgrammerMod", "%"},
    };
}
